# TCN Receptor-Level Holdout Experiments
This notebook tracks commands and results for rerunning TCN experiments under **receptor-level holdout** (within-family generalization), to complement the existing cross-family results.

## Motivation
With the paper reframed to lead with within-family generalization as the primary evaluation, we need:
1. Handcrafted features (scalar, TICA, combined) under receptor-level holdout → expected to still fail, confirming failure is not split-dependent
2. Oracle/sanity check features under receptor-level holdout → upper bound under easier evaluation setting


## Summary of Results (filled in based on below completed experiments)
| Feature | Model | Dim | AUROC (receptor) | AUROC (family) | Behaviour |
|---------|-------|-----|-----------------|----------------|-----------|
Scalar | TCN | 3 | 0.682 | 0.500 | Degenerate 
TICA projections | TCN | 5 | 0.782 | 0.500 | Degenerate 
Combined | TCN | 58 | 0.564 | 0.543 | Degenerate 
ESM-2 | LR | 1280 | 0.688 | 0.541 | Near-chance 
ESM-2 | RF | 1280 | 0.560 | 0.513 | Near-chance 
ESM-2 | MLP | 1280 | 0.521 | 0.529 | Near-chance 
ESMDance | LR | 480 | 0.554 | 0.494 | Near-chance 
ESMDance | RF | 480 | 0.577 | 0.523 | Near-chance 
ESMDance | MLP | 480 | 0.619 | 0.500 | Degenerate 
ESM-IF (mean-pooled) | LR | 512 | -- | 0.541 | Near-chance 
ESM-IF (mean-pooled) | RF | 512 | -- | 0.513 | Near-chance 
ESM-IF (mean-pooled) | MLP | 512 | -- | 0.529 | Near-chance 
Oracle (10\%) | TCN | 7 | 0.836 | 0.783 | Real signal 
Oracle (50\%) | TCN | 7 | 0.862 | 0.811 | Real signal 
Oracle (90\%) | TCN | 7 | 0.974 | 0.933 | Real signal

## Step 1: Generate Receptor-Level Split Files
Uses `within-protein` split mode from `generate_split_files.py`.
This holds out 20% of receptors, allowing the same family to appear in both train and test.

In [10]:
# # Scalar + combined features at 50%
# !python src/data/generate_split_files.py within-protein \
#     --metadata_csv data/metadata/metadata.csv \
#     --feature_type combined \
#     --trajectory_pct 50 \
#     --output_dir data/metadata/splits

# # Sanity check features at 50%
# !python src/data/generate_split_files.py within-protein \
#     --metadata_csv data/metadata/metadata.csv \
#     --feature_type sanity_check \
#     --trajectory_pct 50 \
#     --output_dir data/metadata/splits

# # Sanity check features at 90%
# !python src/data/generate_split_files.py within-protein \
#     --metadata_csv data/metadata/metadata.csv \
#     --feature_type sanity_check \
#     --trajectory_pct 90 \
#     --output_dir data/metadata/splits

## Step 2: Train TCN Models Under Receptor-Level Holdout
Run 3 seeds each for variance estimation, consistent with trajectory sweep methodology.

In [ ]:
# --- Handcrafted features (scalar) at 50% ---
# Expected: still chance-level, confirming failure is not split-dependent

for seed in [0, 1, 2]:
    !python train_tcn.py \
        --train_csv ../../data/metadata/splits/protein_level_train.csv \
        --test_csv ../../data/metadata/splits/protein_level_test.csv \
        --npy_dir ../../../gcs_mount/data/features_50pct/scalar \
        --batch_size 1 --num_workers 0 \
        --patience 50 --epochs 200 \
        --output_dir ../../results/tcn_scalar_50pct_receptor

Using device: cpu
Output directory: ../../results/tcn_scalar_50pct_receptor/tcn_20260312_150355

Loading datasets...
Loaded 203 samples
  Multi: 62.0 (30.5%)
  Single: 141 (69.5%)
  Using frac=1.0 of each trajectory
Loaded 43 samples
  Multi: 9.0 (20.9%)
  Single: 34 (79.1%)
  Using frac=1.0 of each trajectory
  Auto-detected 3 features from data

Initializing TCN with 3 input features...
TCN Summary:
  Receptive field:   61 timesteps
  Pooling:           mean
  Parameters:        13,676
  Architecture:      [25, 25, 25, 25]

Using pos_weight=1.0 for imbalanced data

Starting training...
Epoch 1/200
  Train: Loss=10.1845, Bal Acc=0.511, AUROC=0.549, AP=0.339
  Test:  Loss=5.3012, Bal Acc=0.515, AUROC=0.418, AP=0.186
   New best AUROC: 0.418
Epoch 2/200
  Train: Loss=2.2483, Bal Acc=0.486, AUROC=0.439, AP=0.267
  Test:  Loss=0.7758, Bal Acc=0.500, AUROC=0.748, AP=0.503
   New best AUROC: 0.748
Epoch 3/200
  Train: Loss=1.8082, Bal Acc=0.500, AUROC=0.555, AP=0.348
  Test:  Loss=0.7742, Bal Acc=0.500, AUROC=0.748, AP=0.617
Epoch 4/200
  Train: Loss=1.6387, Bal Acc=0.496, AUROC=0.570, AP=0.344
  Test:  Loss=1.4425, Bal Acc=0.500, AUROC=0.814, AP=0.555
   New best AUROC: 0.814
Epoch 5/200
  Train: Loss=1.8216, Bal Acc=0.500, AUROC=0.496, AP=0.298
  Test:  Loss=0.8884, Bal Acc=0.500, AUROC=0.833, AP=0.565
   New best AUROC: 0.833
Epoch 6/200
  Train: Loss=1.6444, Bal Acc=0.500, AUROC=0.580, AP=0.359
  Test:  Loss=0.9959, Bal Acc=0.500, AUROC=0.837, AP=0.579
   New best AUROC: 0.837
Epoch 7/200
  Train: Loss=1.6197, Bal Acc=0.500, AUROC=0.565, AP=0.338
  Test:  Loss=0.8019, Bal Acc=0.500, AUROC=0.833, AP=0.573
Epoch 8/200
  Train: Loss=1.7113, Bal Acc=0.500, AUROC=0.551, AP=0.337
  Test:  Loss=0.9607, Bal Acc=0.500, AUROC=0.833, AP=0.574
Epoch 9/200
  Train: Loss=1.5796, Bal Acc=0.500, AUROC=0.602, AP=0.358
  Test:  Loss=0.9659, Bal Acc=0.500, AUROC=0.837, AP=0.563
   New best AUROC: 0.837
Epoch 10/200
  Train: Loss=1.6436, Bal Acc=0.500, AUROC=0.547, AP=0.306
  Test:  Loss=1.0266, Bal Acc=0.500, AUROC=0.827, AP=0.567
Epoch 11/200
  Train: Loss=1.6576, Bal Acc=0.500, AUROC=0.583, AP=0.344
  Test:  Loss=0.8087, Bal Acc=0.500, AUROC=0.807, AP=0.550
Epoch 12/200
  Train: Loss=1.6936, Bal Acc=0.500, AUROC=0.582, AP=0.366
  Test:  Loss=0.9180, Bal Acc=0.500, AUROC=0.824, AP=0.568
Epoch 13/200
  Train: Loss=1.6165, Bal Acc=0.500, AUROC=0.570, AP=0.360
  Test:  Loss=0.9958, Bal Acc=0.500, AUROC=0.820, AP=0.544
Epoch 14/200
  Train: Loss=1.5640, Bal Acc=0.500, AUROC=0.634, AP=0.408
  Test:  Loss=0.9437, Bal Acc=0.500, AUROC=0.837, AP=0.551
Epoch 15/200
  Train: Loss=1.5878, Bal Acc=0.500, AUROC=0.605, AP=0.347
  Test:  Loss=0.7347, Bal Acc=0.500, AUROC=0.817, AP=0.542
Epoch 16/200
  Train: Loss=1.5753, Bal Acc=0.500, AUROC=0.596, AP=0.398
  Test:  Loss=0.6059, Bal Acc=0.500, AUROC=0.794, AP=0.508
Epoch 17/200
  Train: Loss=1.6315, Bal Acc=0.500, AUROC=0.563, AP=0.333
  Test:  Loss=0.9665, Bal Acc=0.500, AUROC=0.843, AP=0.554
   New best AUROC: 0.843
Epoch 18/200
  Train: Loss=1.6006, Bal Acc=0.500, AUROC=0.566, AP=0.359
  Test:  Loss=1.0887, Bal Acc=0.500, AUROC=0.840, AP=0.552
Epoch 19/200
  Train: Loss=1.6248, Bal Acc=0.500, AUROC=0.591, AP=0.380
  Test:  Loss=1.1753, Bal Acc=0.500, AUROC=0.843, AP=0.563
   New best AUROC: 0.843
Epoch 20/200
  Train: Loss=1.5152, Bal Acc=0.500, AUROC=0.623, AP=0.407
  Test:  Loss=1.0448, Bal Acc=0.500, AUROC=0.853, AP=0.578
   New best AUROC: 0.853
Epoch 21/200
  Train: Loss=1.6292, Bal Acc=0.500, AUROC=0.578, AP=0.343
  Test:  Loss=1.0457, Bal Acc=0.500, AUROC=0.850, AP=0.565
Epoch 22/200
  Train: Loss=1.5217, Bal Acc=0.500, AUROC=0.617, AP=0.387
  Test:  Loss=0.8090, Bal Acc=0.500, AUROC=0.837, AP=0.548
Epoch 23/200
  Train: Loss=1.5563, Bal Acc=0.500, AUROC=0.582, AP=0.386
  Test:  Loss=1.1240, Bal Acc=0.500, AUROC=0.853, AP=0.569
Epoch 24/200
  Train: Loss=1.6022, Bal Acc=0.500, AUROC=0.570, AP=0.364
  Test:  Loss=0.9320, Bal Acc=0.500, AUROC=0.843, AP=0.555
Epoch 25/200
  Train: Loss=1.5554, Bal Acc=0.500, AUROC=0.615, AP=0.433
  Test:  Loss=0.7640, Bal Acc=0.500, AUROC=0.824, AP=0.536
Epoch 26/200
  Train: Loss=1.5423, Bal Acc=0.500, AUROC=0.641, AP=0.416
  Test:  Loss=0.7239, Bal Acc=0.500, AUROC=0.817, AP=0.531
Epoch 27/200
  Train: Loss=1.4848, Bal Acc=0.500, AUROC=0.620, AP=0.414
  Test:  Loss=1.1056, Bal Acc=0.500, AUROC=0.843, AP=0.560
Epoch 28/200
  Train: Loss=1.5820, Bal Acc=0.500, AUROC=0.579, AP=0.348
  Test:  Loss=1.0457, Bal Acc=0.500, AUROC=0.833, AP=0.545
Epoch 29/200
  Train: Loss=1.5725, Bal Acc=0.500, AUROC=0.579, AP=0.394
  Test:  Loss=1.0437, Bal Acc=0.500, AUROC=0.837, AP=0.548
Epoch 30/200
  Train: Loss=1.5721, Bal Acc=0.500, AUROC=0.587, AP=0.377
  Test:  Loss=0.8141, Bal Acc=0.500, AUROC=0.817, AP=0.531
Epoch 31/200
  Train: Loss=1.5504, Bal Acc=0.500, AUROC=0.552, AP=0.351
  Test:  Loss=0.9867, Bal Acc=0.500, AUROC=0.837, AP=0.548
Epoch 32/200
  Train: Loss=1.5572, Bal Acc=0.500, AUROC=0.607, AP=0.424
  Test:  Loss=0.8981, Bal Acc=0.500, AUROC=0.824, AP=0.532
Epoch 33/200
  Train: Loss=1.5406, Bal Acc=0.500, AUROC=0.594, AP=0.384
  Test:  Loss=0.9126, Bal Acc=0.500, AUROC=0.827, AP=0.538
Epoch 34/200
  Train: Loss=1.5206, Bal Acc=0.500, AUROC=0.605, AP=0.401
  Test:  Loss=0.9225, Bal Acc=0.500, AUROC=0.833, AP=0.547
Epoch 35/200
  Train: Loss=1.5511, Bal Acc=0.500, AUROC=0.590, AP=0.367
  Test:  Loss=1.0003, Bal Acc=0.500, AUROC=0.843, AP=0.554
Epoch 36/200
  Train: Loss=1.5542, Bal Acc=0.500, AUROC=0.598, AP=0.391
  Test:  Loss=0.9115, Bal Acc=0.500, AUROC=0.837, AP=0.550
Epoch 37/200
  Train: Loss=1.5086, Bal Acc=0.508, AUROC=0.611, AP=0.391
  Test:  Loss=1.0657, Bal Acc=0.500, AUROC=0.846, AP=0.555
Epoch 38/200
  Train: Loss=1.5473, Bal Acc=0.500, AUROC=0.597, AP=0.390
  Test:  Loss=1.0221, Bal Acc=0.500, AUROC=0.846, AP=0.555
Epoch 39/200
  Train: Loss=1.5258, Bal Acc=0.500, AUROC=0.624, AP=0.406
  Test:  Loss=0.9837, Bal Acc=0.500, AUROC=0.850, AP=0.565
Epoch 40/200
  Train: Loss=1.5050, Bal Acc=0.500, AUROC=0.607, AP=0.405
  Test:  Loss=1.0374, Bal Acc=0.500, AUROC=0.846, AP=0.562
Epoch 41/200
  Train: Loss=1.5439, Bal Acc=0.508, AUROC=0.618, AP=0.422
  Test:  Loss=0.8375, Bal Acc=0.500, AUROC=0.817, AP=0.530
Epoch 42/200
  Train: Loss=1.5333, Bal Acc=0.500, AUROC=0.592, AP=0.380
  Test:  Loss=0.9226, Bal Acc=0.500, AUROC=0.843, AP=0.555
Epoch 43/200
  Train: Loss=1.5135, Bal Acc=0.508, AUROC=0.611, AP=0.408
  Test:  Loss=0.8879, Bal Acc=0.500, AUROC=0.840, AP=0.552
Epoch 44/200
  Train: Loss=1.5450, Bal Acc=0.500, AUROC=0.635, AP=0.439
  Test:  Loss=0.9189, Bal Acc=0.500, AUROC=0.846, AP=0.557
Epoch 45/200
  Train: Loss=1.4911, Bal Acc=0.500, AUROC=0.610, AP=0.398
  Test:  Loss=0.9434, Bal Acc=0.500, AUROC=0.856, AP=0.565
   New best AUROC: 0.856
Epoch 46/200
  Train: Loss=1.5255, Bal Acc=0.508, AUROC=0.634, AP=0.407
  Test:  Loss=0.9275, Bal Acc=0.500, AUROC=0.856, AP=0.565
Epoch 47/200
  Train: Loss=1.5299, Bal Acc=0.508, AUROC=0.619, AP=0.409
  Test:  Loss=0.8758, Bal Acc=0.500, AUROC=0.837, AP=0.546
Epoch 48/200
  Train: Loss=1.4957, Bal Acc=0.508, AUROC=0.611, AP=0.385
  Test:  Loss=0.9349, Bal Acc=0.500, AUROC=0.843, AP=0.555
Epoch 49/200
  Train: Loss=1.5211, Bal Acc=0.500, AUROC=0.625, AP=0.438
  Test:  Loss=0.9290, Bal Acc=0.500, AUROC=0.850, AP=0.560
Epoch 50/200
  Train: Loss=1.4573, Bal Acc=0.508, AUROC=0.644, AP=0.426
  Test:  Loss=1.0165, Bal Acc=0.500, AUROC=0.859, AP=0.573
   New best AUROC: 0.859
Epoch 51/200
  Train: Loss=1.5353, Bal Acc=0.508, AUROC=0.617, AP=0.393
  Test:  Loss=0.9300, Bal Acc=0.500, AUROC=0.859, AP=0.573
Epoch 52/200
  Train: Loss=1.5140, Bal Acc=0.508, AUROC=0.596, AP=0.384
  Test:  Loss=0.9463, Bal Acc=0.500, AUROC=0.853, AP=0.567
Epoch 53/200
  Train: Loss=1.5212, Bal Acc=0.508, AUROC=0.593, AP=0.405
  Test:  Loss=0.9091, Bal Acc=0.500, AUROC=0.856, AP=0.566
Epoch 54/200
  Train: Loss=1.5087, Bal Acc=0.508, AUROC=0.639, AP=0.430
  Test:  Loss=0.9522, Bal Acc=0.500, AUROC=0.856, AP=0.566
Epoch 55/200
  Train: Loss=1.5236, Bal Acc=0.500, AUROC=0.619, AP=0.398
  Test:  Loss=0.9924, Bal Acc=0.500, AUROC=0.856, AP=0.566
Epoch 56/200
  Train: Loss=1.4888, Bal Acc=0.508, AUROC=0.632, AP=0.430
  Test:  Loss=0.9680, Bal Acc=0.500, AUROC=0.863, AP=0.577
   New best AUROC: 0.863
Epoch 57/200
  Train: Loss=1.5410, Bal Acc=0.508, AUROC=0.601, AP=0.395
  Test:  Loss=0.9301, Bal Acc=0.500, AUROC=0.859, AP=0.570
Epoch 58/200
  Train: Loss=1.4890, Bal Acc=0.508, AUROC=0.608, AP=0.410
  Test:  Loss=0.9641, Bal Acc=0.500, AUROC=0.863, AP=0.577
Epoch 59/200
  Train: Loss=1.5311, Bal Acc=0.508, AUROC=0.620, AP=0.408
  Test:  Loss=0.9132, Bal Acc=0.500, AUROC=0.856, AP=0.567
Epoch 60/200
  Train: Loss=1.5038, Bal Acc=0.508, AUROC=0.629, AP=0.403
  Test:  Loss=0.8687, Bal Acc=0.500, AUROC=0.846, AP=0.557
Epoch 61/200
  Train: Loss=1.5137, Bal Acc=0.508, AUROC=0.632, AP=0.425
  Test:  Loss=0.8784, Bal Acc=0.500, AUROC=0.853, AP=0.563
Epoch 62/200
  Train: Loss=1.4660, Bal Acc=0.508, AUROC=0.617, AP=0.400
  Test:  Loss=0.9763, Bal Acc=0.500, AUROC=0.859, AP=0.571
Epoch 63/200
  Train: Loss=1.5072, Bal Acc=0.508, AUROC=0.630, AP=0.400
  Test:  Loss=0.9839, Bal Acc=0.500, AUROC=0.866, AP=0.581
   New best AUROC: 0.866
Epoch 64/200
  Train: Loss=1.5295, Bal Acc=0.508, AUROC=0.641, AP=0.424
  Test:  Loss=0.9339, Bal Acc=0.500, AUROC=0.859, AP=0.572
Epoch 65/200
  Train: Loss=1.5040, Bal Acc=0.508, AUROC=0.635, AP=0.401
  Test:  Loss=0.9066, Bal Acc=0.500, AUROC=0.856, AP=0.568
Epoch 66/200
  Train: Loss=1.5223, Bal Acc=0.508, AUROC=0.622, AP=0.416
  Test:  Loss=0.9008, Bal Acc=0.500, AUROC=0.859, AP=0.580
Epoch 67/200
  Train: Loss=1.4694, Bal Acc=0.508, AUROC=0.618, AP=0.420
  Test:  Loss=0.9766, Bal Acc=0.500, AUROC=0.869, AP=0.588
   New best AUROC: 0.869
Epoch 68/200
  Train: Loss=1.4951, Bal Acc=0.508, AUROC=0.646, AP=0.422
  Test:  Loss=0.9929, Bal Acc=0.500, AUROC=0.866, AP=0.582
Epoch 69/200
  Train: Loss=1.5283, Bal Acc=0.508, AUROC=0.620, AP=0.411
  Test:  Loss=0.9305, Bal Acc=0.500, AUROC=0.869, AP=0.584
Epoch 70/200
  Train: Loss=1.4973, Bal Acc=0.508, AUROC=0.623, AP=0.410
  Test:  Loss=0.9918, Bal Acc=0.500, AUROC=0.859, AP=0.575
Epoch 71/200
  Train: Loss=1.4748, Bal Acc=0.508, AUROC=0.644, AP=0.423
  Test:  Loss=1.0147, Bal Acc=0.500, AUROC=0.866, AP=0.580
Epoch 72/200
  Train: Loss=1.5152, Bal Acc=0.508, AUROC=0.644, AP=0.436
  Test:  Loss=0.9724, Bal Acc=0.500, AUROC=0.866, AP=0.585
Epoch 73/200
  Train: Loss=1.5006, Bal Acc=0.508, AUROC=0.647, AP=0.439
  Test:  Loss=0.9536, Bal Acc=0.500, AUROC=0.866, AP=0.586
Epoch 74/200
  Train: Loss=1.5575, Bal Acc=0.508, AUROC=0.605, AP=0.394
  Test:  Loss=0.9098, Bal Acc=0.500, AUROC=0.846, AP=0.559
Epoch 75/200
  Train: Loss=1.4601, Bal Acc=0.508, AUROC=0.630, AP=0.442
  Test:  Loss=0.9637, Bal Acc=0.500, AUROC=0.863, AP=0.577
Epoch 76/200
  Train: Loss=1.5501, Bal Acc=0.508, AUROC=0.624, AP=0.428
  Test:  Loss=0.9451, Bal Acc=0.500, AUROC=0.853, AP=0.565
Epoch 77/200
  Train: Loss=1.4528, Bal Acc=0.508, AUROC=0.627, AP=0.423
  Test:  Loss=0.9967, Bal Acc=0.500, AUROC=0.866, AP=0.580
Epoch 78/200
  Train: Loss=1.5404, Bal Acc=0.508, AUROC=0.631, AP=0.455
  Test:  Loss=0.8399, Bal Acc=0.500, AUROC=0.840, AP=0.547
Epoch 79/200
  Train: Loss=1.4391, Bal Acc=0.508, AUROC=0.661, AP=0.434
  Test:  Loss=0.9297, Bal Acc=0.500, AUROC=0.853, AP=0.564
Epoch 80/200
  Train: Loss=1.4852, Bal Acc=0.508, AUROC=0.642, AP=0.434
  Test:  Loss=0.9446, Bal Acc=0.500, AUROC=0.853, AP=0.563
Epoch 81/200
  Train: Loss=1.5129, Bal Acc=0.508, AUROC=0.659, AP=0.446
  Test:  Loss=0.9232, Bal Acc=0.500, AUROC=0.853, AP=0.563
Epoch 82/200
  Train: Loss=1.5010, Bal Acc=0.508, AUROC=0.624, AP=0.414
  Test:  Loss=0.9214, Bal Acc=0.500, AUROC=0.853, AP=0.563
Epoch 83/200
  Train: Loss=1.4708, Bal Acc=0.508, AUROC=0.662, AP=0.447
  Test:  Loss=0.9609, Bal Acc=0.500, AUROC=0.853, AP=0.563
Epoch 84/200
  Train: Loss=1.4934, Bal Acc=0.508, AUROC=0.644, AP=0.427
  Test:  Loss=0.9429, Bal Acc=0.500, AUROC=0.850, AP=0.560
Epoch 85/200
  Train: Loss=1.5055, Bal Acc=0.508, AUROC=0.630, AP=0.423
  Test:  Loss=0.9417, Bal Acc=0.500, AUROC=0.856, AP=0.566
Epoch 86/200
  Train: Loss=1.4803, Bal Acc=0.508, AUROC=0.645, AP=0.435
  Test:  Loss=0.9626, Bal Acc=0.500, AUROC=0.853, AP=0.563
Epoch 87/200
  Train: Loss=1.5016, Bal Acc=0.508, AUROC=0.634, AP=0.412
  Test:  Loss=0.9461, Bal Acc=0.500, AUROC=0.856, AP=0.566
Epoch 88/200
  Train: Loss=1.5055, Bal Acc=0.508, AUROC=0.633, AP=0.435
  Test:  Loss=0.9519, Bal Acc=0.500, AUROC=0.856, AP=0.571
Epoch 89/200
  Train: Loss=1.4831, Bal Acc=0.508, AUROC=0.636, AP=0.426
  Test:  Loss=0.9596, Bal Acc=0.500, AUROC=0.859, AP=0.574
Epoch 90/200
  Train: Loss=1.5248, Bal Acc=0.508, AUROC=0.656, AP=0.446
  Test:  Loss=0.9311, Bal Acc=0.500, AUROC=0.859, AP=0.574
Epoch 91/200
  Train: Loss=1.4783, Bal Acc=0.508, AUROC=0.658, AP=0.443
  Test:  Loss=0.9391, Bal Acc=0.500, AUROC=0.856, AP=0.568
Epoch 92/200
  Train: Loss=1.4806, Bal Acc=0.508, AUROC=0.661, AP=0.439
  Test:  Loss=0.9417, Bal Acc=0.500, AUROC=0.853, AP=0.563
Epoch 93/200
  Train: Loss=1.4762, Bal Acc=0.508, AUROC=0.637, AP=0.433
  Test:  Loss=0.9520, Bal Acc=0.500, AUROC=0.853, AP=0.563
Epoch 94/200
  Train: Loss=1.5175, Bal Acc=0.508, AUROC=0.673, AP=0.454
  Test:  Loss=0.9370, Bal Acc=0.500, AUROC=0.850, AP=0.560
Epoch 95/200
  Train: Loss=1.4897, Bal Acc=0.508, AUROC=0.658, AP=0.439
  Test:  Loss=0.9279, Bal Acc=0.500, AUROC=0.850, AP=0.560
Epoch 96/200
  Train: Loss=1.4761, Bal Acc=0.508, AUROC=0.658, AP=0.450
  Test:  Loss=0.9309, Bal Acc=0.500, AUROC=0.853, AP=0.564
Epoch 97/200
  Train: Loss=1.4970, Bal Acc=0.508, AUROC=0.647, AP=0.431
  Test:  Loss=0.9320, Bal Acc=0.500, AUROC=0.856, AP=0.566
Epoch 98/200
  Train: Loss=1.4531, Bal Acc=0.508, AUROC=0.643, AP=0.448
  Test:  Loss=0.9621, Bal Acc=0.500, AUROC=0.853, AP=0.567
Epoch 99/200
  Train: Loss=1.5115, Bal Acc=0.508, AUROC=0.659, AP=0.437
  Test:  Loss=0.9390, Bal Acc=0.500, AUROC=0.859, AP=0.574
Epoch 100/200
  Train: Loss=1.4906, Bal Acc=0.508, AUROC=0.663, AP=0.446
  Test:  Loss=0.9450, Bal Acc=0.500, AUROC=0.856, AP=0.566
Epoch 101/200
  Train: Loss=1.4869, Bal Acc=0.508, AUROC=0.671, AP=0.455
  Test:  Loss=0.9421, Bal Acc=0.500, AUROC=0.853, AP=0.563
Epoch 102/200
  Train: Loss=1.4961, Bal Acc=0.508, AUROC=0.648, AP=0.438
  Test:  Loss=0.9413, Bal Acc=0.500, AUROC=0.856, AP=0.566
Epoch 103/200
  Train: Loss=1.4809, Bal Acc=0.508, AUROC=0.673, AP=0.456
  Test:  Loss=0.9382, Bal Acc=0.500, AUROC=0.853, AP=0.564
Epoch 104/200
  Train: Loss=1.4965, Bal Acc=0.508, AUROC=0.653, AP=0.435
  Test:  Loss=0.9418, Bal Acc=0.500, AUROC=0.856, AP=0.566
Epoch 105/200
  Train: Loss=1.4974, Bal Acc=0.508, AUROC=0.645, AP=0.437
  Test:  Loss=0.9376, Bal Acc=0.500, AUROC=0.853, AP=0.564
Epoch 106/200
  Train: Loss=1.5027, Bal Acc=0.508, AUROC=0.645, AP=0.431
  Test:  Loss=0.9279, Bal Acc=0.500, AUROC=0.853, AP=0.564
Epoch 107/200
  Train: Loss=1.4836, Bal Acc=0.508, AUROC=0.673, AP=0.450
  Test:  Loss=0.9314, Bal Acc=0.500, AUROC=0.853, AP=0.564
Epoch 108/200
  Train: Loss=1.4869, Bal Acc=0.508, AUROC=0.661, AP=0.446
  Test:  Loss=0.9322, Bal Acc=0.500, AUROC=0.853, AP=0.564
Epoch 109/200
  Train: Loss=1.4922, Bal Acc=0.508, AUROC=0.658, AP=0.432
  Test:  Loss=0.9350, Bal Acc=0.500, AUROC=0.853, AP=0.564
Epoch 110/200
  Train: Loss=1.4817, Bal Acc=0.508, AUROC=0.662, AP=0.452
  Test:  Loss=0.9309, Bal Acc=0.500, AUROC=0.853, AP=0.564
Epoch 111/200
  Train: Loss=1.4776, Bal Acc=0.508, AUROC=0.652, AP=0.439
  Test:  Loss=0.9363, Bal Acc=0.500, AUROC=0.853, AP=0.564
Epoch 112/200
  Train: Loss=1.4827, Bal Acc=0.508, AUROC=0.658, AP=0.445
  Test:  Loss=0.9357, Bal Acc=0.500, AUROC=0.853, AP=0.564
Epoch 113/200
  Train: Loss=1.4806, Bal Acc=0.508, AUROC=0.651, AP=0.451
  Test:  Loss=0.9393, Bal Acc=0.500, AUROC=0.853, AP=0.564
Epoch 114/200
  Train: Loss=1.4927, Bal Acc=0.508, AUROC=0.641, AP=0.437
  Test:  Loss=0.9382, Bal Acc=0.500, AUROC=0.853, AP=0.564
Epoch 115/200
  Train: Loss=1.4957, Bal Acc=0.508, AUROC=0.634, AP=0.419
  Test:  Loss=0.9408, Bal Acc=0.500, AUROC=0.850, AP=0.559
Epoch 116/200
  Train: Loss=1.4993, Bal Acc=0.508, AUROC=0.642, AP=0.441
  Test:  Loss=0.9376, Bal Acc=0.500, AUROC=0.853, AP=0.564
Epoch 117/200
  Train: Loss=1.4737, Bal Acc=0.508, AUROC=0.670, AP=0.468
  Test:  Loss=0.9354, Bal Acc=0.500, AUROC=0.850, AP=0.559

Early stopping at epoch 117 (no improvement for 50 epochs)

================================================================================
FINAL EVALUATION (best model)
================================================================================

Test Metrics:
  Balanced Accuracy: 0.500
  AUROC: 0.869
  Avg Precision: 0.588

Confusion Matrix:
  TN=34, FP=0
  FN=9, TP=0

Classification Report:
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
              precision    recall  f1-score   support

single_state       0.79      1.00      0.88        34
 multi_state       0.00      0.00      0.00         9

    accuracy                           0.79        43
   macro avg       0.40      0.50      0.44        43
weighted avg       0.63      0.79      0.70        43


 Results saved to ../../results/tcn_scalar_50pct_receptor/tcn_20260312_150355
Using device: cpu
Output directory: ../../results/tcn_scalar_50pct_receptor/tcn_20260312_151413

Loading datasets...
Loaded 203 samples
  Multi: 62.0 (30.5%)
  Single: 141 (69.5%)
  Using frac=1.0 of each trajectory
Loaded 43 samples
  Multi: 9.0 (20.9%)
  Single: 34 (79.1%)
  Using frac=1.0 of each trajectory
  Auto-detected 3 features from data

Initializing TCN with 3 input features...
TCN Summary:
  Receptive field:   61 timesteps
  Pooling:           mean
  Parameters:        13,676
  Architecture:      [25, 25, 25, 25]

Using pos_weight=1.0 for imbalanced data

Starting training...
Epoch 1/200
  Train: Loss=50.9315, Bal Acc=0.534, AUROC=0.533, AP=0.322
  Test:  Loss=0.7420, Bal Acc=0.456, AUROC=0.572, AP=0.263
   New best AUROC: 0.572
Epoch 2/200
  Train: Loss=1.8553, Bal Acc=0.502, AUROC=0.530, AP=0.319
  Test:  Loss=1.8134, Bal Acc=0.500, AUROC=0.676, AP=0.334
   New best AUROC: 0.676
Epoch 3/200
  Train: Loss=1.8583, Bal Acc=0.494, AUROC=0.507, AP=0.301
  Test:  Loss=0.8998, Bal Acc=0.500, AUROC=0.582, AP=0.264
Epoch 4/200
  Train: Loss=1.8411, Bal Acc=0.500, AUROC=0.496, AP=0.324
  Test:  Loss=1.5310, Bal Acc=0.500, AUROC=0.670, AP=0.330
Epoch 5/200
  Train: Loss=10.3629, Bal Acc=0.500, AUROC=0.543, AP=0.336
  Test:  Loss=20.9302, Bal Acc=0.500, AUROC=0.500, AP=0.209
Epoch 6/200
  Train: Loss=30.5419, Bal Acc=0.500, AUROC=0.489, AP=0.305
  Test:  Loss=20.9302, Bal Acc=0.500, AUROC=0.500, AP=0.209
Epoch 7/200
  Train: Loss=30.5419, Bal Acc=0.500, AUROC=0.489, AP=0.305
  Test:  Loss=20.9302, Bal Acc=0.500, AUROC=0.500, AP=0.209
Epoch 8/200
  Train: Loss=30.5419, Bal Acc=0.500, AUROC=0.489, AP=0.305
  Test:  Loss=20.9302, Bal Acc=0.500, AUROC=0.500, AP=0.209
Epoch 9/200
  Train: Loss=30.5419, Bal Acc=0.500, AUROC=0.489, AP=0.305
  Test:  Loss=20.9302, Bal Acc=0.500, AUROC=0.500, AP=0.209
Epoch 10/200
  Train: Loss=30.5419, Bal Acc=0.500, AUROC=0.489, AP=0.305

In [ ]:
# --- Handcrafted features (TICA) at 50% ---
# Expected: still chance-level, confirming failure is not split-dependent

for seed in [0, 1, 2]:
    !python train_tcn.py \
        --train_csv ../../data/metadata/splits/protein_level_tica_train.csv \
        --test_csv ../../data/metadata/splits/protein_level_test.csv \
        --npy_dir ../../../gcs_mount/data/features_50pct/tica/projections \
        --batch_size 1 --num_workers 0 \
        --patience 50 --epochs 200 \
        --output_dir ../../results/tcn_tica_50pct_receptor

Using device: cpu
Output directory: ../../results/tcn_tica_50pct_receptor/tcn_20260312_154322

Loading datasets...
Loaded 200 samples
  Multi: 62.0 (31.0%)
  Single: 138 (69.0%)
  Using frac=1.0 of each trajectory
Loaded 43 samples
  Multi: 9.0 (20.9%)
  Single: 34 (79.1%)
  Using frac=1.0 of each trajectory
  Auto-detected 5 features from data

Initializing TCN with 5 input features...
TCN Summary:
  Receptive field:   61 timesteps
  Pooling:           mean
  Parameters:        13,876
  Architecture:      [25, 25, 25, 25]

Using pos_weight=1.0 for imbalanced data

Starting training...
Epoch 1/200
  Train: Loss=1.7045, Bal Acc=0.500, AUROC=0.393, AP=0.264
  Test:  Loss=0.8035, Bal Acc=0.500, AUROC=0.660, AP=0.448
   New best AUROC: 0.660
Epoch 2/200
  Train: Loss=1.1784, Bal Acc=0.500, AUROC=0.537, AP=0.328
  Test:  Loss=0.7345, Bal Acc=0.500, AUROC=0.706, AP=0.552
   New best AUROC: 0.706
Epoch 3/200
  Train: Loss=1.0430, Bal Acc=0.500, AUROC=0.589, AP=0.360
  Test:  Loss=0.5327, Bal Acc=0.500, AUROC=0.729, AP=0.453
   New best AUROC: 0.729
Epoch 4/200
  Train: Loss=0.9232, Bal Acc=0.500, AUROC=0.630, AP=0.380
  Test:  Loss=0.5938, Bal Acc=0.500, AUROC=0.752, AP=0.607
   New best AUROC: 0.752
Epoch 5/200
  Train: Loss=0.8935, Bal Acc=0.500, AUROC=0.622, AP=0.419
  Test:  Loss=0.6960, Bal Acc=0.500, AUROC=0.735, AP=0.574
Epoch 6/200
  Train: Loss=0.9004, Bal Acc=0.500, AUROC=0.659, AP=0.443
  Test:  Loss=0.5762, Bal Acc=0.500, AUROC=0.732, AP=0.570
Epoch 7/200
  Train: Loss=0.8158, Bal Acc=0.500, AUROC=0.697, AP=0.480
  Test:  Loss=0.5678, Bal Acc=0.500, AUROC=0.725, AP=0.593
Epoch 8/200
  Train: Loss=0.7962, Bal Acc=0.500, AUROC=0.744, AP=0.550
  Test:  Loss=0.6812, Bal Acc=0.500, AUROC=0.699, AP=0.517
Epoch 9/200
  Train: Loss=0.8146, Bal Acc=0.500, AUROC=0.735, AP=0.522
  Test:  Loss=0.4664, Bal Acc=0.500, AUROC=0.748, AP=0.632
Epoch 10/200
  Train: Loss=0.8148, Bal Acc=0.513, AUROC=0.735, AP=0.570
  Test:  Loss=0.6880, Bal Acc=0.500, AUROC=0.732, AP=0.616
Epoch 11/200
  Train: Loss=0.8035, Bal Acc=0.508, AUROC=0.740, AP=0.546
  Test:  Loss=0.5425, Bal Acc=0.500, AUROC=0.725, AP=0.594
Epoch 12/200
  Train: Loss=0.7601, Bal Acc=0.546, AUROC=0.749, AP=0.575
  Test:  Loss=0.6188, Bal Acc=0.611, AUROC=0.683, AP=0.550
Epoch 13/200
  Train: Loss=0.8357, Bal Acc=0.563, AUROC=0.739, AP=0.565
  Test:  Loss=0.5117, Bal Acc=0.693, AUROC=0.712, AP=0.606
Epoch 14/200
  Train: Loss=0.7253, Bal Acc=0.617, AUROC=0.778, AP=0.595
  Test:  Loss=0.9041, Bal Acc=0.500, AUROC=0.641, AP=0.533
Epoch 15/200
  Train: Loss=0.7824, Bal Acc=0.623, AUROC=0.769, AP=0.648
  Test:  Loss=1.0192, Bal Acc=0.613, AUROC=0.716, AP=0.572
Epoch 16/200
  Train: Loss=0.6849, Bal Acc=0.709, AUROC=0.789, AP=0.663
  Test:  Loss=0.8442, Bal Acc=0.693, AUROC=0.624, AP=0.500
Epoch 17/200
  Train: Loss=0.6934, Bal Acc=0.667, AUROC=0.817, AP=0.655
  Test:  Loss=0.9477, Bal Acc=0.693, AUROC=0.618, AP=0.459
Epoch 18/200
  Train: Loss=0.7328, Bal Acc=0.676, AUROC=0.825, AP=0.667
  Test:  Loss=1.0530, Bal Acc=0.590, AUROC=0.663, AP=0.501
Epoch 19/200
  Train: Loss=0.7782, Bal Acc=0.686, AUROC=0.822, AP=0.701
  Test:  Loss=1.0261, Bal Acc=0.634, AUROC=0.631, AP=0.443
Epoch 20/200
  Train: Loss=0.8139, Bal Acc=0.684, AUROC=0.814, AP=0.691
  Test:  Loss=1.0996, Bal Acc=0.649, AUROC=0.582, AP=0.422
Epoch 21/200
  Train: Loss=0.7424, Bal Acc=0.688, AUROC=0.828, AP=0.714
  Test:  Loss=1.1981, Bal Acc=0.605, AUROC=0.578, AP=0.416
Epoch 22/200
  Train: Loss=0.8250, Bal Acc=0.705, AUROC=0.818, AP=0.709
  Test:  Loss=1.3960, Bal Acc=0.587, AUROC=0.663, AP=0.490
Epoch 23/200
  Train: Loss=0.7394, Bal Acc=0.709, AUROC=0.836, AP=0.743
  Test:  Loss=1.1811, Bal Acc=0.605, AUROC=0.578, AP=0.418
Epoch 24/200
  Train: Loss=0.7388, Bal Acc=0.709, AUROC=0.835, AP=0.725
  Test:  Loss=1.2308, Bal Acc=0.649, AUROC=0.575, AP=0.361
Epoch 25/200
  Train: Loss=0.7851, Bal Acc=0.725, AUROC=0.819, AP=0.744
  Test:  Loss=1.2154, Bal Acc=0.663, AUROC=0.578, AP=0.422
Epoch 26/200
  Train: Loss=0.7133, Bal Acc=0.707, AUROC=0.853, AP=0.735
  Test:  Loss=1.2226, Bal Acc=0.608, AUROC=0.546, AP=0.401
Epoch 27/200
  Train: Loss=0.6914, Bal Acc=0.717, AUROC=0.864, AP=0.774
  Test:  Loss=1.2754, Bal Acc=0.593, AUROC=0.552, AP=0.402
Epoch 28/200
  Train: Loss=0.6439, Bal Acc=0.749, AUROC=0.887, AP=0.781
  Test:  Loss=1.3171, Bal Acc=0.593, AUROC=0.569, AP=0.408
Epoch 29/200
  Train: Loss=0.6992, Bal Acc=0.725, AUROC=0.870, AP=0.775
  Test:  Loss=1.3041, Bal Acc=0.649, AUROC=0.582, AP=0.416
Epoch 30/200
  Train: Loss=0.6762, Bal Acc=0.728, AUROC=0.881, AP=0.789
  Test:  Loss=1.3622, Bal Acc=0.634, AUROC=0.598, AP=0.420
Epoch 31/200
  Train: Loss=0.7211, Bal Acc=0.717, AUROC=0.877, AP=0.796
  Test:  Loss=1.3385, Bal Acc=0.634, AUROC=0.588, AP=0.413
Epoch 32/200
  Train: Loss=0.6295, Bal Acc=0.769, AUROC=0.880, AP=0.808
  Test:  Loss=1.3443, Bal Acc=0.608, AUROC=0.575, AP=0.415
Epoch 33/200
  Train: Loss=0.7140, Bal Acc=0.736, AUROC=0.885, AP=0.801
  Test:  Loss=1.3589, Bal Acc=0.663, AUROC=0.598, AP=0.421
Epoch 34/200
  Train: Loss=0.6215, Bal Acc=0.785, AUROC=0.888, AP=0.818
  Test:  Loss=1.3971, Bal Acc=0.663, AUROC=0.592, AP=0.420
Epoch 35/200
  Train: Loss=0.6870, Bal Acc=0.761, AUROC=0.890, AP=0.811
  Test:  Loss=1.3964, Bal Acc=0.663, AUROC=0.601, AP=0.422
Epoch 36/200
  Train: Loss=0.6824, Bal Acc=0.741, AUROC=0.887, AP=0.824
  Test:  Loss=1.3880, Bal Acc=0.634, AUROC=0.611, AP=0.426
Epoch 37/200
  Train: Loss=0.6382, Bal Acc=0.761, AUROC=0.892, AP=0.818
  Test:  Loss=1.4182, Bal Acc=0.663, AUROC=0.618, AP=0.428
Epoch 38/200
  Train: Loss=0.6516, Bal Acc=0.761, AUROC=0.896, AP=0.815
  Test:  Loss=1.4347, Bal Acc=0.634, AUROC=0.618, AP=0.428
Epoch 39/200
  Train: Loss=0.5799, Bal Acc=0.773, AUROC=0.912, AP=0.847
  Test:  Loss=1.5061, Bal Acc=0.619, AUROC=0.621, AP=0.411
Epoch 40/200
  Train: Loss=0.5710, Bal Acc=0.797, AUROC=0.913, AP=0.839
  Test:  Loss=1.4665, Bal Acc=0.634, AUROC=0.627, AP=0.431
Epoch 41/200
  Train: Loss=0.5218, Bal Acc=0.796, AUROC=0.921, AP=0.848
  Test:  Loss=1.5281, Bal Acc=0.552, AUROC=0.621, AP=0.430
Epoch 42/200
  Train: Loss=0.6338, Bal Acc=0.784, AUROC=0.904, AP=0.836
  Test:  Loss=1.4747, Bal Acc=0.649, AUROC=0.627, AP=0.432
Epoch 43/200
  Train: Loss=0.6087, Bal Acc=0.777, AUROC=0.912, AP=0.829
  Test:  Loss=1.5086, Bal Acc=0.649, AUROC=0.621, AP=0.429
Epoch 44/200
  Train: Loss=0.6008, Bal Acc=0.765, AUROC=0.920, AP=0.859
  Test:  Loss=1.5654, Bal Acc=0.634, AUROC=0.624, AP=0.431
Epoch 45/200
  Train: Loss=0.5298, Bal Acc=0.796, AUROC=0.921, AP=0.871
  Test:  Loss=1.6146, Bal Acc=0.552, AUROC=0.618, AP=0.428
Epoch 46/200
  Train: Loss=0.6165, Bal Acc=0.789, AUROC=0.917, AP=0.842
  Test:  Loss=1.5946, Bal Acc=0.634, AUROC=0.621, AP=0.430
Epoch 47/200
  Train: Loss=0.5461, Bal Acc=0.786, AUROC=0.919, AP=0.858
  Test:  Loss=1.6019, Bal Acc=0.552, AUROC=0.621, AP=0.413
Epoch 48/200
  Train: Loss=0.6054, Bal Acc=0.785, AUROC=0.921, AP=0.844
  Test:  Loss=1.5709, Bal Acc=0.663, AUROC=0.621, AP=0.413
Epoch 49/200
  Train: Loss=0.6154, Bal Acc=0.792, AUROC=0.919, AP=0.855
  Test:  Loss=1.5874, Bal Acc=0.634, AUROC=0.627, AP=0.433
Epoch 50/200
  Train: Loss=0.5901, Bal Acc=0.793, AUROC=0.918, AP=0.861
  Test:  Loss=1.5952, Bal Acc=0.634, AUROC=0.627, AP=0.433
Epoch 51/200
  Train: Loss=0.5222, Bal Acc=0.793, AUROC=0.928, AP=0.875
  Test:  Loss=1.5962, Bal Acc=0.663, AUROC=0.627, AP=0.433
Epoch 52/200
  Train: Loss=0.5623, Bal Acc=0.777, AUROC=0.931, AP=0.879
  Test:  Loss=1.6109, Bal Acc=0.634, AUROC=0.631, AP=0.434
Epoch 53/200
  Train: Loss=0.5247, Bal Acc=0.797, AUROC=0.929, AP=0.867
  Test:  Loss=1.6018, Bal Acc=0.663, AUROC=0.627, AP=0.433
Epoch 54/200
  Train: Loss=0.5575, Bal Acc=0.777, AUROC=0.935, AP=0.877
  Test:  Loss=1.6026, Bal Acc=0.634, AUROC=0.631, AP=0.434

Early stopping at epoch 54 (no improvement for 50 epochs)

================================================================================
FINAL EVALUATION (best model)
================================================================================

Test Metrics:
  Balanced Accuracy: 0.500
  AUROC: 0.752
  Avg Precision: 0.607

Confusion Matrix:
  TN=34, FP=0
  FN=9, TP=0

Classification Report:
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
              precision    recall  f1-score   support

single_state       0.79      1.00      0.88        34
 multi_state       0.00      0.00      0.00         9

    accuracy                           0.79        43
   macro avg       0.40      0.50      0.44        43
weighted avg       0.63      0.79      0.70        43


 Results saved to ../../results/tcn_tica_50pct_receptor/tcn_20260312_154322
Using device: cpu
Output directory: ../../results/tcn_tica_50pct_receptor/tcn_20260312_154726

Loading datasets...
Loaded 200 samples
  Multi: 62.0 (31.0%)
  Single: 138 (69.0%)
  Using frac=1.0 of each trajectory
Loaded 43 samples
  Multi: 9.0 (20.9%)
  Single: 34 (79.1%)
  Using frac=1.0 of each trajectory
  Auto-detected 5 features from data

Initializing TCN with 5 input features...
TCN Summary:
  Receptive field:   61 timesteps
  Pooling:           mean
  Parameters:        13,876
  Architecture:      [25, 25, 25, 25]

Using pos_weight=1.0 for imbalanced data

Starting training...
Epoch 1/200
  Train: Loss=2.2592, Bal Acc=0.483, AUROC=0.453, AP=0.280
  Test:  Loss=0.8693, Bal Acc=0.500, AUROC=0.732, AP=0.406
   New best AUROC: 0.732
Epoch 2/200
  Train: Loss=1.2776, Bal Acc=0.500, AUROC=0.568, AP=0.343
  Test:  Loss=0.6057, Bal Acc=0.500, AUROC=0.732, AP=0.415
Epoch 3/200
  Train: Loss=1.1496, Bal Acc=0.500, AUROC=0.620, AP=0.390
  Test:  Loss=0.5778, Bal Acc=0.500, AUROC=0.748, AP=0.545
   New best AUROC: 0.748
Epoch 4/200
  Train: Loss=1.1087, Bal Acc=0.500, AUROC=0.609, AP=0.372
  Test:  Loss=0.6321, Bal Acc=0.500, AUROC=0.745, AP=0.506
Epoch 5/200
  Train: Loss=1.0310, Bal Acc=0.500, AUROC=0.659, AP=0.419
  Test:  Loss=0.4839, Bal Acc=0.500, AUROC=0.722, AP=0.512
Epoch 6/200
  Train: Loss=0.9988, Bal Acc=0.508, AUROC=0.644, AP=0.506
  Test:  Loss=0.5272, Bal Acc=0.500, AUROC=0.739, AP=0.568
Epoch 7/200
  Train: Loss=0.8863, Bal Acc=0.505, AUROC=0.724, AP=0.517
  Test:  Loss=0.5427, Bal Acc=0.500, AUROC=0.716, AP=0.559
Epoch 8/200
  Train: Loss=0.8272, Bal Acc=0.502, AUROC=0.742, AP=0.534
  Test:  Loss=0.4751, Bal Acc=0.667, AUROC=0.732, AP=0.612
Epoch 9/200
  Train: Loss=0.8300, Bal Acc=0.545, AUROC=0.757, AP=0.587
  Test:  Loss=0.7754, Bal Acc=0.611, AUROC=0.725, AP=0.591
Epoch 10/200
  Train: Loss=0.8771, Bal Acc=0.599, AUROC=0.731, AP=0.588
  Test:  Loss=0.5251, Bal Acc=0.693, AUROC=0.706, AP=0.586
Epoch 11/200
  Train: Loss=0.8836, Bal Acc=0.607, AUROC=0.741, AP=0.576
  Test:  Loss=0.4701, Bal Acc=0.667, AUROC=0.712, AP=0.572
Epoch 12/200
  Train: Loss=0.7879, Bal Acc=0.607, AUROC=0.775, AP=0.628
  Test:  Loss=0.5745, Bal Acc=0.652, AUROC=0.722, AP=0.590
Epoch 13/200
  Train: Loss=0.8664, Bal Acc=0.631, AUROC=0.767, AP=0.615
  Test:  Loss=0.5816, Bal Acc=0.652, AUROC=0.663, AP=0.546
Epoch 14/200
  Train: Loss=0.7715, Bal Acc=0.643, AUROC=0.802, AP=0.671
  Test:  Loss=0.6823, Bal Acc=0.652, AUROC=0.696, AP=0.550
Epoch 15/200
  Train: Loss=0.7856, Bal Acc=0.643, AUROC=0.821, AP=0.691
  Test:  Loss=0.6561, Bal Acc=0.678, AUROC=0.690, AP=0.567
Epoch 16/200
  Train: Loss=0.7848, Bal Acc=0.644, AUROC=0.836, AP=0.698
  Test:  Loss=0.6132, Bal Acc=0.652, AUROC=0.660, AP=0.537
Epoch 17/200
  Train: Loss=0.7243, Bal Acc=0.652, AUROC=0.847, AP=0.707
  Test:  Loss=0.7424, Bal Acc=0.652, AUROC=0.654, AP=0.533
Epoch 18/200
  Train: Loss=0.7575, Bal Acc=0.648, AUROC=0.829, AP=0.701
  Test:  Loss=0.6428, Bal Acc=0.608, AUROC=0.673, AP=0.537
Epoch 19/200
  Train: Loss=0.7522, Bal Acc=0.648, AUROC=0.856, AP=0.736
  Test:  Loss=0.7152, Bal Acc=0.593, AUROC=0.683, AP=0.538
Epoch 20/200
  Train: Loss=0.7308, Bal Acc=0.681, AUROC=0.855, AP=0.737
  Test:  Loss=0.7487, Bal Acc=0.649, AUROC=0.712, AP=0.573
Epoch 21/200
  Train: Loss=0.7048, Bal Acc=0.693, AUROC=0.861, AP=0.728
  Test:  Loss=0.8470, Bal Acc=0.652, AUROC=0.650, AP=0.548
Epoch 22/200
  Train: Loss=0.7329, Bal Acc=0.651, AUROC=0.866, AP=0.765
  Test:  Loss=0.7875, Bal Acc=0.619, AUROC=0.699, AP=0.581
Epoch 23/200
  Train: Loss=0.6758, Bal Acc=0.705, AUROC=0.878, AP=0.767
  Test:  Loss=0.9144, Bal Acc=0.619, AUROC=0.703, AP=0.581
Epoch 24/200
  Train: Loss=0.7497, Bal Acc=0.742, AUROC=0.852, AP=0.746
  Test:  Loss=0.8982, Bal Acc=0.678, AUROC=0.680, AP=0.572
Epoch 25/200
  Train: Loss=0.6361, Bal Acc=0.760, AUROC=0.886, AP=0.810
  Test:  Loss=1.2903, Bal Acc=0.575, AUROC=0.722, AP=0.576
Epoch 26/200
  Train: Loss=0.5629, Bal Acc=0.790, AUROC=0.900, AP=0.816
  Test:  Loss=1.0276, Bal Acc=0.649, AUROC=0.716, AP=0.586
Epoch 27/200
  Train: Loss=0.5681, Bal Acc=0.806, AUROC=0.904, AP=0.823
  Test:  Loss=1.0250, Bal Acc=0.663, AUROC=0.696, AP=0.581
Epoch 28/200
  Train: Loss=0.6757, Bal Acc=0.813, AUROC=0.893, AP=0.810
  Test:  Loss=1.1026, Bal Acc=0.619, AUROC=0.729, AP=0.595
Epoch 29/200
  Train: Loss=0.5905, Bal Acc=0.802, AUROC=0.909, AP=0.820
  Test:  Loss=1.0966, Bal Acc=0.605, AUROC=0.742, AP=0.602
Epoch 30/200
  Train: Loss=0.5961, Bal Acc=0.810, AUROC=0.907, AP=0.835
  Test:  Loss=1.0731, Bal Acc=0.634, AUROC=0.752, AP=0.628
   New best AUROC: 0.752
Epoch 31/200
  Train: Loss=0.5589, Bal Acc=0.813, AUROC=0.921, AP=0.851
  Test:  Loss=1.1322, Bal Acc=0.634, AUROC=0.755, AP=0.630
   New best AUROC: 0.755
Epoch 32/200
  Train: Loss=0.5657, Bal Acc=0.818, AUROC=0.924, AP=0.844
  Test:  Loss=1.1819, Bal Acc=0.619, AUROC=0.748, AP=0.627
Epoch 33/200
  Train: Loss=0.5307, Bal Acc=0.882, AUROC=0.935, AP=0.850
  Test:  Loss=1.5119, Bal Acc=0.590, AUROC=0.755, AP=0.628
Epoch 34/200
  Train: Loss=0.5635, Bal Acc=0.838, AUROC=0.924, AP=0.836
  Test:  Loss=1.1805, Bal Acc=0.619, AUROC=0.722, AP=0.611
Epoch 35/200
  Train: Loss=0.5754, Bal Acc=0.829, AUROC=0.927, AP=0.854
  Test:  Loss=1.2834, Bal Acc=0.649, AUROC=0.755, AP=0.629
Epoch 36/200
  Train: Loss=0.5223, Bal Acc=0.838, AUROC=0.931, AP=0.872
  Test:  Loss=1.3512, Bal Acc=0.634, AUROC=0.755, AP=0.628
Epoch 37/200
  Train: Loss=0.5644, Bal Acc=0.849, AUROC=0.931, AP=0.860
  Test:  Loss=1.3694, Bal Acc=0.649, AUROC=0.761, AP=0.632
   New best AUROC: 0.761
Epoch 38/200
  Train: Loss=0.4645, Bal Acc=0.854, AUROC=0.946, AP=0.888
  Test:  Loss=1.4591, Bal Acc=0.649, AUROC=0.768, AP=0.635
   New best AUROC: 0.768
Epoch 39/200
  Train: Loss=0.5800, Bal Acc=0.829, AUROC=0.932, AP=0.878
  Test:  Loss=1.7934, Bal Acc=0.701, AUROC=0.778, AP=0.650
   New best AUROC: 0.778
Epoch 40/200
  Train: Loss=0.5570, Bal Acc=0.854, AUROC=0.930, AP=0.872
  Test:  Loss=1.7799, Bal Acc=0.716, AUROC=0.788, AP=0.653
   New best AUROC: 0.788
Epoch 41/200
  Train: Loss=0.4893, Bal Acc=0.861, AUROC=0.942, AP=0.888
  Test:  Loss=1.4287, Bal Acc=0.619, AUROC=0.745, AP=0.622
Epoch 42/200
  Train: Loss=0.5055, Bal Acc=0.873, AUROC=0.944, AP=0.897
  Test:  Loss=1.5098, Bal Acc=0.730, AUROC=0.775, AP=0.645
Epoch 43/200
  Train: Loss=0.4496, Bal Acc=0.881, AUROC=0.945, AP=0.899
  Test:  Loss=1.4034, Bal Acc=0.634, AUROC=0.758, AP=0.632
Epoch 44/200
  Train: Loss=0.5469, Bal Acc=0.861, AUROC=0.939, AP=0.879
  Test:  Loss=1.6045, Bal Acc=0.634, AUROC=0.752, AP=0.623
Epoch 45/200
  Train: Loss=0.4290, Bal Acc=0.881, AUROC=0.956, AP=0.915
  Test:  Loss=4.1970, Bal Acc=0.672, AUROC=0.781, AP=0.565
Epoch 46/200
  Train: Loss=0.5759, Bal Acc=0.887, AUROC=0.940, AP=0.880
  Test:  Loss=1.6273, Bal Acc=0.649, AUROC=0.755, AP=0.626
Epoch 47/200
  Train: Loss=0.4103, Bal Acc=0.894, AUROC=0.956, AP=0.923
  Test:  Loss=1.4723, Bal Acc=0.649, AUROC=0.739, AP=0.621
Epoch 48/200
  Train: Loss=0.4579, Bal Acc=0.881, AUROC=0.955, AP=0.922
  Test:  Loss=1.4863, Bal Acc=0.649, AUROC=0.742, AP=0.623
Epoch 49/200
  Train: Loss=0.9440, Bal Acc=0.881, AUROC=0.949, AP=0.871
  Test:  Loss=1.6008, Bal Acc=0.634, AUROC=0.742, AP=0.623
Epoch 50/200
  Train: Loss=0.9605, Bal Acc=0.878, AUROC=0.943, AP=0.879
  Test:  Loss=1.6447, Bal Acc=0.690, AUROC=0.768, AP=0.642
Epoch 51/200
  Train: Loss=0.8880, Bal Acc=0.873, AUROC=0.954, AP=0.879
  Test:  Loss=1.9753, Bal Acc=0.619, AUROC=0.771, AP=0.642
Epoch 52/200
  Train: Loss=0.4829, Bal Acc=0.901, AUROC=0.953, AP=0.912
  Test:  Loss=1.8609, Bal Acc=0.634, AUROC=0.771, AP=0.644
Epoch 53/200
  Train: Loss=0.4796, Bal Acc=0.905, AUROC=0.955, AP=0.913
  Test:  Loss=1.8704, Bal Acc=0.690, AUROC=0.781, AP=0.653
Epoch 54/200
  Train: Loss=0.4252, Bal Acc=0.925, AUROC=0.962, AP=0.918
  Test:  Loss=1.6727, Bal Acc=0.634, AUROC=0.771, AP=0.641
Epoch 55/200
  Train: Loss=0.4305, Bal Acc=0.917, AUROC=0.959, AP=0.911
  Test:  Loss=2.0709, Bal Acc=0.730, AUROC=0.778, AP=0.631
Epoch 56/200
  Train: Loss=0.4767, Bal Acc=0.914, AUROC=0.956, AP=0.910
  Test:  Loss=1.9999, Bal Acc=0.675, AUROC=0.775, AP=0.626
Epoch 57/200
  Train: Loss=0.4776, Bal Acc=0.913, AUROC=0.957, AP=0.921
  Test:  Loss=1.9200, Bal Acc=0.730, AUROC=0.778, AP=0.649
Epoch 58/200
  Train: Loss=0.5012, Bal Acc=0.913, AUROC=0.954, AP=0.905
  Test:  Loss=2.0595, Bal Acc=0.730, AUROC=0.779, AP=0.631
Epoch 59/200
  Train: Loss=0.4008, Bal Acc=0.913, AUROC=0.964, AP=0.936
  Test:  Loss=1.8903, Bal Acc=0.690, AUROC=0.771, AP=0.644
Epoch 60/200
  Train: Loss=0.7998, Bal Acc=0.909, AUROC=0.967, AP=0.908
  Test:  Loss=2.0223, Bal Acc=0.675, AUROC=0.775, AP=0.648
Epoch 61/200
  Train: Loss=0.5285, Bal Acc=0.897, AUROC=0.953, AP=0.905
  Test:  Loss=2.1305, Bal Acc=0.730, AUROC=0.781, AP=0.632
Epoch 62/200
  Train: Loss=0.4615, Bal Acc=0.917, AUROC=0.960, AP=0.922
  Test:  Loss=1.8747, Bal Acc=0.634, AUROC=0.775, AP=0.645
Epoch 63/200
  Train: Loss=0.8897, Bal Acc=0.917, AUROC=0.960, AP=0.896
  Test:  Loss=1.9043, Bal Acc=0.690, AUROC=0.784, AP=0.655
Epoch 64/200
  Train: Loss=0.3931, Bal Acc=0.921, AUROC=0.968, AP=0.938
  Test:  Loss=2.0132, Bal Acc=0.745, AUROC=0.784, AP=0.634
Epoch 65/200
  Train: Loss=0.4326, Bal Acc=0.917, AUROC=0.966, AP=0.925
  Test:  Loss=2.0589, Bal Acc=0.745, AUROC=0.781, AP=0.632
Epoch 66/200
  Train: Loss=0.3664, Bal Acc=0.941, AUROC=0.965, AP=0.945
  Test:  Loss=1.9076, Bal Acc=0.690, AUROC=0.778, AP=0.652
Epoch 67/200
  Train: Loss=0.3982, Bal Acc=0.905, AUROC=0.966, AP=0.932
  Test:  Loss=1.9576, Bal Acc=0.690, AUROC=0.781, AP=0.653
Epoch 68/200
  Train: Loss=0.3939, Bal Acc=0.933, AUROC=0.966, AP=0.935
  Test:  Loss=2.0953, Bal Acc=0.745, AUROC=0.779, AP=0.630
Epoch 69/200
  Train: Loss=0.4315, Bal Acc=0.921, AUROC=0.962, AP=0.929
  Test:  Loss=2.1837, Bal Acc=0.730, AUROC=0.778, AP=0.630
Epoch 70/200
  Train: Loss=0.4085, Bal Acc=0.937, AUROC=0.963, AP=0.929
  Test:  Loss=1.9964, Bal Acc=0.745, AUROC=0.778, AP=0.652
Epoch 71/200
  Train: Loss=0.3731, Bal Acc=0.941, AUROC=0.968, AP=0.934
  Test:  Loss=2.0606, Bal Acc=0.730, AUROC=0.784, AP=0.655
Epoch 72/200
  Train: Loss=0.8330, Bal Acc=0.925, AUROC=0.965, AP=0.908
  Test:  Loss=2.2373, Bal Acc=0.716, AUROC=0.781, AP=0.653
Epoch 73/200
  Train: Loss=0.3787, Bal Acc=0.925, AUROC=0.970, AP=0.935
  Test:  Loss=2.0521, Bal Acc=0.745, AUROC=0.784, AP=0.655
Epoch 74/200
  Train: Loss=0.7842, Bal Acc=0.925, AUROC=0.970, AP=0.921

In [6]:
# --- Handcrafted features (combined) at 50% ---
# Expected: still chance-level, confirming failure is not split-dependent

for seed in [0, 1, 2]:
    !python train_tcn.py \
        --train_csv ../../data/metadata/splits/protein_level_train.csv \
        --test_csv ../../data/metadata/splits/protein_level_test.csv \
        --npy_dir ../../../gcs_mount/data/processed/combined_features/combined_50pct \
        --batch_size 1 --num_workers 0 \
        --patience 50 --epochs 200 \
        --output_dir ../../results/tcn_combined_50pct_receptor

Using device: cpu
Output directory: ../../results/tcn_combined_50pct_receptor/tcn_20260312_120523

Loading datasets...
Loaded 203 samples
  Multi: 62.0 (30.5%)
  Single: 141 (69.5%)
  Using frac=1.0 of each trajectory
Loaded 43 samples
  Multi: 9.0 (20.9%)
  Single: 34 (79.1%)
  Using frac=1.0 of each trajectory
  Auto-detected 58 features from data

Initializing TCN with 58 input features...
TCN Summary:
  Receptive field:   61 timesteps
  Pooling:           mean
  Parameters:        19,176
  Architecture:      [25, 25, 25, 25]

Using pos_weight=1.0 for imbalanced data

Starting training...
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 1/200
  Train: Loss=30.5419, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=20.9302, Bal Acc=0.500, AUROC=0.500, AP=0.209
   New best AUROC: 0.500
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 2/200
  Train: Loss=42.7888, Bal Acc=0.456, AUROC=0.470, AP=0.285
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 3/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 4/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 5/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 6/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 7/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 8/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 9/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 10/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 11/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 12/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 13/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 14/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 15/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 16/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 17/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 18/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 19/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 20/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 21/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 22/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 23/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 24/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 25/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 26/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 27/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 28/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 29/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 30/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 31/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 32/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
Epoch 33/200
  Train: Loss=69.4581, Bal Acc=0.500, AUROC=0.500, AP=0.305
  Test:  Loss=79.0698, Bal Acc=0.500, AUROC=0.500, AP=0.209
/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

NameError: name 'done' is not defined

In [ ]:
# --- Oracle/sanity check features at 50% ---
# Upper bound under receptor-level holdout; expect higher than 0.831 (cross-family)

for seed in [0, 1, 2]:
    !python train_tcn.py \
        --train_csv ../../data/metadata/splits/protein_level_train.csv \
        --test_csv ../../data/metadata/splits/protein_level_test.csv \
        --npy_dir ../../data/features_50pct/oracle_features \
        --batch_size 1 --num_workers 0 \
        --patience 50 --epochs 200 \
        --output_dir ../../results/tcn_oracle_50pct_receptor

Using device: cpu
Output directory: results/tcn_oracle_90pct_receptor/tcn_20260312_123236

Loading datasets...
Loaded 203 samples
  Multi: 62.0 (30.5%)
  Single: 141 (69.5%)
  Using frac=1.0 of each trajectory
Loaded 43 samples
  Multi: 9.0 (20.9%)
  Single: 34 (79.1%)
  Using frac=1.0 of each trajectory
  Auto-detected 7 features from data

Initializing TCN with 7 input features...
TCN Summary:
  Receptive field:   61 timesteps
  Pooling:           mean
  Parameters:        14,076
  Architecture:      [25, 25, 25, 25]

Using pos_weight=1.0 for imbalanced data

Starting training...
Epoch 1/200
  Train: Loss=1.7736, Bal Acc=0.486, AUROC=0.503, AP=0.319
  Test:  Loss=1.0830, Bal Acc=0.500, AUROC=0.657, AP=0.459
   New best AUROC: 0.657
Epoch 2/200
  Train: Loss=1.2580, Bal Acc=0.500, AUROC=0.484, AP=0.295
  Test:  Loss=0.6862, Bal Acc=0.500, AUROC=0.797, AP=0.546
   New best AUROC: 0.797
Epoch 3/200
  Train: Loss=1.1979, Bal Acc=0.500, AUROC=0.540, AP=0.343
  Test:  Loss=0.8451, Bal Acc=0.500, AUROC=0.729, AP=0.492
Epoch 4/200
  Train: Loss=1.0805, Bal Acc=0.508, AUROC=0.630, AP=0.447
  Test:  Loss=0.4172, Bal Acc=0.663, AUROC=0.810, AP=0.566
   New best AUROC: 0.810
Epoch 5/200
  Train: Loss=1.0370, Bal Acc=0.518, AUROC=0.642, AP=0.459
  Test:  Loss=0.4700, Bal Acc=0.556, AUROC=0.827, AP=0.604
   New best AUROC: 0.827
Epoch 6/200
  Train: Loss=0.9449, Bal Acc=0.566, AUROC=0.711, AP=0.557
  Test:  Loss=0.4593, Bal Acc=0.704, AUROC=0.833, AP=0.604
   New best AUROC: 0.833
Epoch 7/200
  Train: Loss=0.8718, Bal Acc=0.641, AUROC=0.740, AP=0.579
  Test:  Loss=0.7927, Bal Acc=0.730, AUROC=0.853, AP=0.586
   New best AUROC: 0.853
Epoch 8/200
  Train: Loss=0.9225, Bal Acc=0.610, AUROC=0.754, AP=0.593
  Test:  Loss=0.7084, Bal Acc=0.745, AUROC=0.846, AP=0.577
Epoch 9/200
  Train: Loss=0.9108, Bal Acc=0.611, AUROC=0.773, AP=0.599
  Test:  Loss=0.7151, Bal Acc=0.663, AUROC=0.820, AP=0.549
Epoch 10/200
  Train: Loss=0.8952, Bal Acc=0.609, AUROC=0.784, AP=0.622
  Test:  Loss=0.7224, Bal Acc=0.745, AUROC=0.830, AP=0.554
Epoch 11/200
  Train: Loss=0.8904, Bal Acc=0.663, AUROC=0.795, AP=0.656
  Test:  Loss=0.9772, Bal Acc=0.771, AUROC=0.833, AP=0.581
Epoch 12/200
  Train: Loss=0.8890, Bal Acc=0.663, AUROC=0.797, AP=0.627
  Test:  Loss=0.8034, Bal Acc=0.815, AUROC=0.853, AP=0.598
   New best AUROC: 0.853
Epoch 13/200
  Train: Loss=0.8533, Bal Acc=0.690, AUROC=0.832, AP=0.661
  Test:  Loss=0.5093, Bal Acc=0.678, AUROC=0.846, AP=0.587
Epoch 14/200
  Train: Loss=0.8250, Bal Acc=0.708, AUROC=0.817, AP=0.724
  Test:  Loss=3.5770, Bal Acc=0.786, AUROC=0.812, AP=0.450
Epoch 15/200
  Train: Loss=0.7682, Bal Acc=0.677, AUROC=0.842, AP=0.725
  Test:  Loss=1.1143, Bal Acc=0.771, AUROC=0.833, AP=0.568
Epoch 16/200
  Train: Loss=0.9498, Bal Acc=0.700, AUROC=0.823, AP=0.669
  Test:  Loss=0.9709, Bal Acc=0.801, AUROC=0.853, AP=0.575
Epoch 17/200
  Train: Loss=0.7081, Bal Acc=0.731, AUROC=0.873, AP=0.742
  Test:  Loss=0.6230, Bal Acc=0.678, AUROC=0.814, AP=0.664
Epoch 18/200
  Train: Loss=0.8310, Bal Acc=0.747, AUROC=0.861, AP=0.761
  Test:  Loss=1.3941, Bal Acc=0.716, AUROC=0.827, AP=0.532
Epoch 19/200
  Train: Loss=0.6669, Bal Acc=0.792, AUROC=0.904, AP=0.805
  Test:  Loss=3.5421, Bal Acc=0.716, AUROC=0.815, AP=0.479
Epoch 20/200
  Train: Loss=0.6731, Bal Acc=0.768, AUROC=0.896, AP=0.795
  Test:  Loss=3.3806, Bal Acc=0.786, AUROC=0.861, AP=0.543
   New best AUROC: 0.861
Epoch 21/200
  Train: Loss=0.7139, Bal Acc=0.801, AUROC=0.905, AP=0.787
  Test:  Loss=0.9877, Bal Acc=0.704, AUROC=0.814, AP=0.627
Epoch 22/200
  Train: Loss=0.7285, Bal Acc=0.794, AUROC=0.904, AP=0.816
  Test:  Loss=3.3327, Bal Acc=0.675, AUROC=0.845, AP=0.495
Epoch 23/200
  Train: Loss=0.6455, Bal Acc=0.822, AUROC=0.910, AP=0.823
  Test:  Loss=1.5281, Bal Acc=0.730, AUROC=0.833, AP=0.572
Epoch 24/200
  Train: Loss=1.0231, Bal Acc=0.835, AUROC=0.924, AP=0.820
  Test:  Loss=1.4945, Bal Acc=0.716, AUROC=0.827, AP=0.532
Epoch 25/200
  Train: Loss=0.6881, Bal Acc=0.840, AUROC=0.925, AP=0.831
  Test:  Loss=3.2736, Bal Acc=0.690, AUROC=0.837, AP=0.505
Epoch 26/200
  Train: Loss=1.4864, Bal Acc=0.808, AUROC=0.925, AP=0.804
  Test:  Loss=5.8598, Bal Acc=0.730, AUROC=0.830, AP=0.476
Epoch 27/200
  Train: Loss=0.5711, Bal Acc=0.809, AUROC=0.934, AP=0.867
  Test:  Loss=5.7272, Bal Acc=0.786, AUROC=0.846, AP=0.480
Epoch 28/200
  Train: Loss=0.5075, Bal Acc=0.817, AUROC=0.941, AP=0.883
  Test:  Loss=1.3348, Bal Acc=0.675, AUROC=0.843, AP=0.640
Epoch 29/200
  Train: Loss=0.5532, Bal Acc=0.817, AUROC=0.937, AP=0.882
  Test:  Loss=7.8325, Bal Acc=0.730, AUROC=0.850, AP=0.467
Epoch 30/200
  Train: Loss=0.5769, Bal Acc=0.810, AUROC=0.934, AP=0.882
  Test:  Loss=5.7858, Bal Acc=0.730, AUROC=0.856, AP=0.505
Epoch 31/200
  Train: Loss=0.6314, Bal Acc=0.817, AUROC=0.918, AP=0.858
  Test:  Loss=6.0789, Bal Acc=0.812, AUROC=0.846, AP=0.515
Epoch 32/200
  Train: Loss=0.4919, Bal Acc=0.838, AUROC=0.952, AP=0.898
  Test:  Loss=9.9769, Bal Acc=0.842, AUROC=0.850, AP=0.470
Epoch 33/200
  Train: Loss=0.4397, Bal Acc=0.850, AUROC=0.960, AP=0.913
  Test:  Loss=8.1221, Bal Acc=0.771, AUROC=0.832, AP=0.472
Epoch 34/200
  Train: Loss=0.4365, Bal Acc=0.862, AUROC=0.958, AP=0.912
  Test:  Loss=6.1273, Bal Acc=0.716, AUROC=0.850, AP=0.516
Epoch 35/200
  Train: Loss=0.3903, Bal Acc=0.869, AUROC=0.964, AP=0.921
  Test:  Loss=6.0018, Bal Acc=0.730, AUROC=0.833, AP=0.501
Epoch 36/200
  Train: Loss=0.7837, Bal Acc=0.873, AUROC=0.971, AP=0.919
  Test:  Loss=10.6151, Bal Acc=0.853, AUROC=0.846, AP=0.484
Epoch 37/200
  Train: Loss=0.4022, Bal Acc=0.842, AUROC=0.969, AP=0.929
  Test:  Loss=12.5689, Bal Acc=0.853, AUROC=0.830, AP=0.449
Epoch 38/200
  Train: Loss=0.8266, Bal Acc=0.856, AUROC=0.963, AP=0.910
  Test:  Loss=10.2710, Bal Acc=0.771, AUROC=0.833, AP=0.450
Epoch 39/200
  Train: Loss=0.7597, Bal Acc=0.866, AUROC=0.970, AP=0.922
  Test:  Loss=10.3523, Bal Acc=0.827, AUROC=0.846, AP=0.466
Epoch 40/200
  Train: Loss=1.3085, Bal Acc=0.866, AUROC=0.965, AP=0.899
  Test:  Loss=10.3474, Bal Acc=0.827, AUROC=0.843, AP=0.463
Epoch 41/200
  Train: Loss=0.7794, Bal Acc=0.898, AUROC=0.968, AP=0.923
  Test:  Loss=10.3928, Bal Acc=0.827, AUROC=0.853, AP=0.490
Epoch 42/200
  Train: Loss=0.7257, Bal Acc=0.900, AUROC=0.974, AP=0.930
  Test:  Loss=10.4439, Bal Acc=0.827, AUROC=0.850, AP=0.486
Epoch 43/200
  Train: Loss=0.7557, Bal Acc=0.874, AUROC=0.975, AP=0.934
  Test:  Loss=16.4636, Bal Acc=0.797, AUROC=0.830, AP=0.427
Epoch 44/200
  Train: Loss=0.6920, Bal Acc=0.930, AUROC=0.976, AP=0.938
  Test:  Loss=12.4666, Bal Acc=0.812, AUROC=0.840, AP=0.459
Epoch 45/200
  Train: Loss=0.7326, Bal Acc=0.918, AUROC=0.979, AP=0.937
  Test:  Loss=16.5229, Bal Acc=0.853, AUROC=0.833, AP=0.430
Epoch 46/200
  Train: Loss=0.7668, Bal Acc=0.906, AUROC=0.976, AP=0.935
  Test:  Loss=14.5118, Bal Acc=0.853, AUROC=0.833, AP=0.439
Epoch 47/200
  Train: Loss=0.6869, Bal Acc=0.918, AUROC=0.981, AP=0.946
  Test:  Loss=16.4597, Bal Acc=0.853, AUROC=0.833, AP=0.430
Epoch 48/200
  Train: Loss=0.6897, Bal Acc=0.910, AUROC=0.981, AP=0.948
  Test:  Loss=16.4640, Bal Acc=0.868, AUROC=0.827, AP=0.423
Epoch 49/200
  Train: Loss=0.6464, Bal Acc=0.927, AUROC=0.984, AP=0.951
  Test:  Loss=16.4759, Bal Acc=0.868, AUROC=0.820, AP=0.416
Epoch 50/200
  Train: Loss=0.6802, Bal Acc=0.918, AUROC=0.981, AP=0.949
  Test:  Loss=16.4313, Bal Acc=0.812, AUROC=0.827, AP=0.423
Epoch 51/200
  Train: Loss=0.6921, Bal Acc=0.926, AUROC=0.982, AP=0.948
  Test:  Loss=16.5462, Bal Acc=0.853, AUROC=0.827, AP=0.423
Epoch 52/200
  Train: Loss=0.6608, Bal Acc=0.913, AUROC=0.983, AP=0.952
  Test:  Loss=16.6496, Bal Acc=0.853, AUROC=0.824, AP=0.420
Epoch 53/200
  Train: Loss=0.6888, Bal Acc=0.914, AUROC=0.981, AP=0.945
  Test:  Loss=16.4407, Bal Acc=0.868, AUROC=0.833, AP=0.430
Epoch 54/200
  Train: Loss=0.6424, Bal Acc=0.937, AUROC=0.986, AP=0.958
  Test:  Loss=16.5960, Bal Acc=0.853, AUROC=0.830, AP=0.427
Epoch 55/200
  Train: Loss=0.6425, Bal Acc=0.942, AUROC=0.987, AP=0.958
  Test:  Loss=16.5826, Bal Acc=0.853, AUROC=0.824, AP=0.420
Epoch 56/200
  Train: Loss=0.6575, Bal Acc=0.937, AUROC=0.985, AP=0.955
  Test:  Loss=16.6349, Bal Acc=0.853, AUROC=0.835, AP=0.443
Epoch 57/200
  Train: Loss=0.6240, Bal Acc=0.954, AUROC=0.987, AP=0.958
  Test:  Loss=16.4866, Bal Acc=0.868, AUROC=0.827, AP=0.423
Epoch 58/200
  Train: Loss=0.6465, Bal Acc=0.945, AUROC=0.985, AP=0.957
  Test:  Loss=16.5182, Bal Acc=0.868, AUROC=0.827, AP=0.422
Epoch 59/200
  Train: Loss=0.6486, Bal Acc=0.945, AUROC=0.987, AP=0.958
  Test:  Loss=16.6016, Bal Acc=0.853, AUROC=0.827, AP=0.423
Epoch 60/200
  Train: Loss=0.6281, Bal Acc=0.953, AUROC=0.986, AP=0.958
  Test:  Loss=16.6952, Bal Acc=0.853, AUROC=0.846, AP=0.468
Epoch 61/200
  Train: Loss=0.6447, Bal Acc=0.949, AUROC=0.985, AP=0.957
  Test:  Loss=16.6112, Bal Acc=0.853, AUROC=0.838, AP=0.446
Epoch 62/200
  Train: Loss=0.6357, Bal Acc=0.945, AUROC=0.987, AP=0.959
  Test:  Loss=16.6698, Bal Acc=0.853, AUROC=0.838, AP=0.446
Epoch 63/200
  Train: Loss=0.6316, Bal Acc=0.949, AUROC=0.987, AP=0.959
  Test:  Loss=16.5997, Bal Acc=0.853, AUROC=0.827, AP=0.423
Epoch 64/200
  Train: Loss=0.6563, Bal Acc=0.949, AUROC=0.985, AP=0.957
  Test:  Loss=16.7501, Bal Acc=0.853, AUROC=0.846, AP=0.468
Epoch 65/200
  Train: Loss=0.6341, Bal Acc=0.949, AUROC=0.987, AP=0.961
  Test:  Loss=16.6841, Bal Acc=0.853, AUROC=0.850, AP=0.471
Epoch 66/200
  Train: Loss=0.6235, Bal Acc=0.945, AUROC=0.988, AP=0.962
  Test:  Loss=16.6634, Bal Acc=0.853, AUROC=0.850, AP=0.471
Epoch 67/200
  Train: Loss=0.6321, Bal Acc=0.957, AUROC=0.985, AP=0.958
  Test:  Loss=16.6642, Bal Acc=0.853, AUROC=0.850, AP=0.471
Epoch 68/200
  Train: Loss=0.6341, Bal Acc=0.957, AUROC=0.986, AP=0.960
  Test:  Loss=16.5967, Bal Acc=0.853, AUROC=0.827, AP=0.423
Epoch 69/200
  Train: Loss=0.6227, Bal Acc=0.961, AUROC=0.988, AP=0.961
  Test:  Loss=16.7254, Bal Acc=0.853, AUROC=0.846, AP=0.468
Epoch 70/200
  Train: Loss=0.6257, Bal Acc=0.957, AUROC=0.988, AP=0.962
  Test:  Loss=16.7031, Bal Acc=0.853, AUROC=0.846, AP=0.468

Early stopping at epoch 70 (no improvement for 50 epochs)

================================================================================
FINAL EVALUATION (best model)
================================================================================

Test Metrics:
  Balanced Accuracy: 0.786
  AUROC: 0.861
  Avg Precision: 0.543

Confusion Matrix:
  TN=27, FP=7
  FN=2, TP=7

Classification Report:
              precision    recall  f1-score   support

single_state       0.93      0.79      0.86        34
 multi_state       0.50      0.78      0.61         9

    accuracy                           0.79        43
   macro avg       0.72      0.79      0.73        43
weighted avg       0.84      0.79      0.81        43


 Results saved to results/tcn_oracle_90pct_receptor/tcn_20260312_123236
Using device: cpu
Output directory: results/tcn_oracle_90pct_receptor/tcn_20260312_123646

Loading datasets...
Loaded 203 samples
  Multi: 62.0 (30.5%)
  Single: 141 (69.5%)
  Using frac=1.0 of each trajectory
Loaded 43 samples
  Multi: 9.0 (20.9%)
  Single: 34 (79.1%)
  Using frac=1.0 of each trajectory
  Auto-detected 7 features from data

Initializing TCN with 7 input features...
TCN Summary:
  Receptive field:   61 timesteps
  Pooling:           mean
  Parameters:        14,076
  Architecture:      [25, 25, 25, 25]

Using pos_weight=1.0 for imbalanced data

Starting training...
Epoch 1/200
  Train: Loss=1.5315, Bal Acc=0.500, AUROC=0.498, AP=0.297
  Test:  Loss=0.5537, Bal Acc=0.500, AUROC=0.497, AP=0.251
   New best AUROC: 0.497
Epoch 2/200
  Train: Loss=1.1679, Bal Acc=0.500, AUROC=0.500, AP=0.301
  Test:  Loss=0.5468, Bal Acc=0.500, AUROC=0.732, AP=0.570
   New best AUROC: 0.732
Epoch 3/200
  Train: Loss=1.0856, Bal Acc=0.500, AUROC=0.575, AP=0.386
  Test:  Loss=0.5148, Bal Acc=0.500, AUROC=0.765, AP=0.575
   New best AUROC: 0.765
Epoch 4/200
  Train: Loss=1.0428, Bal Acc=0.500, AUROC=0.563, AP=0.374
  Test:  Loss=0.5016, Bal Acc=0.500, AUROC=0.804, AP=0.642
   New best AUROC: 0.804
Epoch 5/200
  Train: Loss=0.9446, Bal Acc=0.500, AUROC=0.620, AP=0.409
  Test:  Loss=0.5679, Bal Acc=0.500, AUROC=0.830, AP=0.612
   New best AUROC: 0.830
Epoch 6/200
  Train: Loss=0.9249, Bal Acc=0.496, AUROC=0.701, AP=0.444
  Test:  Loss=0.4654, Bal Acc=0.500, AUROC=0.850, AP=0.610
   New best AUROC: 0.850
Epoch 7/200
  Train: Loss=0.8954, Bal Acc=0.500, AUROC=0.640, AP=0.450
  Test:  Loss=0.4634, Bal Acc=0.500, AUROC=0.846, AP=0.644
Epoch 8/200
  Train: Loss=0.8300, Bal Acc=0.513, AUROC=0.732, AP=0.520
  Test:  Loss=0.4249, Bal Acc=0.623, AUROC=0.794, AP=0.607
Epoch 9/200
  Train: Loss=0.8926, Bal Acc=0.514, AUROC=0.698, AP=0.451
  Test:  Loss=0.5258, Bal Acc=0.500, AUROC=0.807, AP=0.570
Epoch 10/200
  Train: Loss=0.8211, Bal Acc=0.550, AUROC=0.732, AP=0.525
  Test:  Loss=0.5941, Bal Acc=0.500, AUROC=0.814, AP=0.580
Epoch 11/200
  Train: Loss=0.8231, Bal Acc=0.554, AUROC=0.777, AP=0.584
  Test:  Loss=0.6148, Bal Acc=0.716, AUROC=0.833, AP=0.518
Epoch 12/200
  Train: Loss=1.1844, Bal Acc=0.593, AUROC=0.721, AP=0.543
  Test:  Loss=0.5099, Bal Acc=0.675, AUROC=0.830, AP=0.606
Epoch 13/200
  Train: Loss=0.9906, Bal Acc=0.586, AUROC=0.744, AP=0.541
  Test:  Loss=0.5051, Bal Acc=0.634, AUROC=0.859, AP=0.597
   New best AUROC: 0.859
Epoch 14/200
  Train: Loss=0.8070, Bal Acc=0.646, AUROC=0.801, AP=0.612
  Test:  Loss=0.6895, Bal Acc=0.556, AUROC=0.748, AP=0.549
Epoch 15/200
  Train: Loss=0.8948, Bal Acc=0.598, AUROC=0.798, AP=0.549
  Test:  Loss=0.9416, Bal Acc=0.786, AUROC=0.853, AP=0.566
Epoch 16/200
  Train: Loss=0.8394, Bal Acc=0.681, AUROC=0.817, AP=0.670
  Test:  Loss=0.6111, Bal Acc=0.675, AUROC=0.817, AP=0.556
Epoch 17/200
  Train: Loss=0.7096, Bal Acc=0.690, AUROC=0.834, AP=0.674
  Test:  Loss=1.0802, Bal Acc=0.757, AUROC=0.830, AP=0.576
Epoch 18/200
  Train: Loss=0.7873, Bal Acc=0.722, AUROC=0.851, AP=0.692
  Test:  Loss=1.0408, Bal Acc=0.730, AUROC=0.837, AP=0.569
Epoch 19/200
  Train: Loss=0.7560, Bal Acc=0.705, AUROC=0.856, AP=0.682
  Test:  Loss=0.9348, Bal Acc=0.716, AUROC=0.833, AP=0.615
Epoch 20/200
  Train: Loss=0.7134, Bal Acc=0.745, AUROC=0.867, AP=0.743
  Test:  Loss=0.9790, Bal Acc=0.701, AUROC=0.804, AP=0.543
Epoch 21/200
  Train: Loss=0.7983, Bal Acc=0.692, AUROC=0.858, AP=0.687
  Test:  Loss=1.6850, Bal Acc=0.797, AUROC=0.843, AP=0.602
Epoch 22/200
  Train: Loss=0.7479, Bal Acc=0.759, AUROC=0.854, AP=0.719
  Test:  Loss=1.1947, Bal Acc=0.730, AUROC=0.843, AP=0.613
Epoch 23/200
  Train: Loss=0.7530, Bal Acc=0.726, AUROC=0.881, AP=0.736
  Test:  Loss=0.8208, Bal Acc=0.675, AUROC=0.804, AP=0.503
Epoch 24/200
  Train: Loss=0.9264, Bal Acc=0.734, AUROC=0.846, AP=0.756
  Test:  Loss=1.5620, Bal Acc=0.757, AUROC=0.869, AP=0.627
   New best AUROC: 0.869
Epoch 25/200
  Train: Loss=0.7847, Bal Acc=0.780, AUROC=0.884, AP=0.740
  Test:  Loss=1.1297, Bal Acc=0.690, AUROC=0.788, AP=0.544
Epoch 26/200
  Train: Loss=0.7389, Bal Acc=0.728, AUROC=0.870, AP=0.768
  Test:  Loss=1.1853, Bal Acc=0.757, AUROC=0.827, AP=0.610
Epoch 27/200
  Train: Loss=0.7731, Bal Acc=0.772, AUROC=0.884, AP=0.764
  Test:  Loss=1.0585, Bal Acc=0.701, AUROC=0.797, AP=0.572
Epoch 28/200
  Train: Loss=0.7371, Bal Acc=0.760, AUROC=0.887, AP=0.784
  Test:  Loss=0.7576, Bal Acc=0.693, AUROC=0.820, AP=0.539
Epoch 29/200
  Train: Loss=0.7802, Bal Acc=0.743, AUROC=0.876, AP=0.779
  Test:  Loss=10.3412, Bal Acc=0.779, AUROC=0.850, AP=0.489
Epoch 30/200
  Train: Loss=0.6762, Bal Acc=0.792, AUROC=0.878, AP=0.793
  Test:  Loss=1.3721, Bal Acc=0.730, AUROC=0.827, AP=0.601
Epoch 31/200
  Train: Loss=0.6998, Bal Acc=0.805, AUROC=0.900, AP=0.791
  Test:  Loss=1.5325, Bal Acc=0.742, AUROC=0.820, AP=0.550
Epoch 32/200
  Train: Loss=0.6910, Bal Acc=0.788, AUROC=0.909, AP=0.804
  Test:  Loss=1.9113, Bal Acc=0.771, AUROC=0.863, AP=0.616
Epoch 33/200
  Train: Loss=0.6374, Bal Acc=0.817, AUROC=0.922, AP=0.814
  Test:  Loss=1.0093, Bal Acc=0.649, AUROC=0.830, AP=0.631
Epoch 34/200
  Train: Loss=0.8692, Bal Acc=0.748, AUROC=0.890, AP=0.757
  Test:  Loss=6.2941, Bal Acc=0.824, AUROC=0.838, AP=0.472
Epoch 35/200
  Train: Loss=0.5231, Bal Acc=0.780, AUROC=0.918, AP=0.859
  Test:  Loss=1.0302, Bal Acc=0.730, AUROC=0.830, AP=0.597
Epoch 36/200
  Train: Loss=0.5486, Bal Acc=0.835, AUROC=0.933, AP=0.872
  Test:  Loss=1.6413, Bal Acc=0.757, AUROC=0.850, AP=0.580
Epoch 37/200
  Train: Loss=0.5014, Bal Acc=0.861, AUROC=0.943, AP=0.902
  Test:  Loss=1.4240, Bal Acc=0.690, AUROC=0.824, AP=0.570
Epoch 38/200
  Train: Loss=0.4157, Bal Acc=0.876, AUROC=0.952, AP=0.921
  Test:  Loss=1.7055, Bal Acc=0.745, AUROC=0.843, AP=0.570
Epoch 39/200
  Train: Loss=0.5602, Bal Acc=0.861, AUROC=0.944, AP=0.898
  Test:  Loss=1.8198, Bal Acc=0.745, AUROC=0.846, AP=0.581
Epoch 40/200
  Train: Loss=0.5610, Bal Acc=0.873, AUROC=0.948, AP=0.886
  Test:  Loss=1.4490, Bal Acc=0.760, AUROC=0.827, AP=0.551
Epoch 41/200
  Train: Loss=0.4789, Bal Acc=0.875, AUROC=0.956, AP=0.919
  Test:  Loss=3.9560, Bal Acc=0.701, AUROC=0.833, AP=0.542
Epoch 42/200
  Train: Loss=0.4418, Bal Acc=0.904, AUROC=0.958, AP=0.912
  Test:  Loss=4.2532, Bal Acc=0.783, AUROC=0.869, AP=0.631
   New best AUROC: 0.869
Epoch 43/200
  Train: Loss=0.4431, Bal Acc=0.877, AUROC=0.962, AP=0.931
  Test:  Loss=4.7191, Bal Acc=0.742, AUROC=0.868, AP=0.665
Epoch 44/200
  Train: Loss=0.4177, Bal Acc=0.883, AUROC=0.961, AP=0.934
  Test:  Loss=10.6021, Bal Acc=0.812, AUROC=0.835, AP=0.455
Epoch 45/200
  Train: Loss=0.5560, Bal Acc=0.883, AUROC=0.951, AP=0.916
  Test:  Loss=3.9803, Bal Acc=0.730, AUROC=0.827, AP=0.546
Epoch 46/200
  Train: Loss=0.4608, Bal Acc=0.882, AUROC=0.963, AP=0.933
  Test:  Loss=10.7744, Bal Acc=0.768, AUROC=0.830, AP=0.503
Epoch 47/200
  Train: Loss=0.3964, Bal Acc=0.907, AUROC=0.969, AP=0.945
  Test:  Loss=3.8212, Bal Acc=0.745, AUROC=0.827, AP=0.536
Epoch 48/200
  Train: Loss=0.3125, Bal Acc=0.926, AUROC=0.977, AP=0.962
  Test:  Loss=4.0470, Bal Acc=0.730, AUROC=0.838, AP=0.568
Epoch 49/200
  Train: Loss=0.3432, Bal Acc=0.911, AUROC=0.978, AP=0.954
  Test:  Loss=4.1317, Bal Acc=0.745, AUROC=0.842, AP=0.594
Epoch 50/200
  Train: Loss=0.3220, Bal Acc=0.935, AUROC=0.978, AP=0.959
  Test:  Loss=4.3377, Bal Acc=0.716, AUROC=0.830, AP=0.594
Epoch 51/200
  Train: Loss=0.3510, Bal Acc=0.899, AUROC=0.976, AP=0.959
  Test:  Loss=4.4333, Bal Acc=0.701, AUROC=0.853, AP=0.609
Epoch 52/200
  Train: Loss=0.2771, Bal Acc=0.916, AUROC=0.982, AP=0.964
  Test:  Loss=10.4436, Bal Acc=0.757, AUROC=0.853, AP=0.519
Epoch 53/200
  Train: Loss=0.2978, Bal Acc=0.895, AUROC=0.982, AP=0.962
  Test:  Loss=10.2837, Bal Acc=0.742, AUROC=0.859, AP=0.548
Epoch 54/200
  Train: Loss=0.2724, Bal Acc=0.920, AUROC=0.983, AP=0.968
  Test:  Loss=4.0309, Bal Acc=0.730, AUROC=0.851, AP=0.587
Epoch 55/200
  Train: Loss=0.2777, Bal Acc=0.937, AUROC=0.985, AP=0.969
  Test:  Loss=12.5211, Bal Acc=0.727, AUROC=0.828, AP=0.473
Epoch 56/200
  Train: Loss=0.2522, Bal Acc=0.923, AUROC=0.984, AP=0.971
  Test:  Loss=10.6439, Bal Acc=0.730, AUROC=0.820, AP=0.472
Epoch 57/200
  Train: Loss=0.3044, Bal Acc=0.914, AUROC=0.980, AP=0.959
  Test:  Loss=14.6111, Bal Acc=0.757, AUROC=0.807, AP=0.448
Epoch 58/200
  Train: Loss=0.2437, Bal Acc=0.930, AUROC=0.987, AP=0.973
  Test:  Loss=14.5199, Bal Acc=0.757, AUROC=0.810, AP=0.448
Epoch 59/200
  Train: Loss=0.2581, Bal Acc=0.946, AUROC=0.990, AP=0.979
  Test:  Loss=8.6347, Bal Acc=0.716, AUROC=0.822, AP=0.504
Epoch 60/200
  Train: Loss=0.2483, Bal Acc=0.937, AUROC=0.987, AP=0.975
  Test:  Loss=8.5574, Bal Acc=0.771, AUROC=0.845, AP=0.546
Epoch 61/200
  Train: Loss=0.2499, Bal Acc=0.950, AUROC=0.987, AP=0.977
  Test:  Loss=8.6213, Bal Acc=0.716, AUROC=0.835, AP=0.540
Epoch 62/200
  Train: Loss=0.2670, Bal Acc=0.945, AUROC=0.985, AP=0.971
  Test:  Loss=12.5230, Bal Acc=0.771, AUROC=0.819, AP=0.470
Epoch 63/200
  Train: Loss=0.2555, Bal Acc=0.942, AUROC=0.986, AP=0.976
  Test:  Loss=12.5377, Bal Acc=0.771, AUROC=0.835, AP=0.481
Epoch 64/200
  Train: Loss=0.2181, Bal Acc=0.942, AUROC=0.990, AP=0.979
  Test:  Loss=12.5591, Bal Acc=0.742, AUROC=0.815, AP=0.469

NameError: name 'done' is not defined

In [9]:
# --- Oracle/sanity check features at 90% ---
# Upper bound at 50%; expect close to cross-family result of 0.95

for seed in [0, 1, 2]:
    !python train_tcn.py \
        --train_csv ../../data/metadata/splits/protein_level_train.csv \
        --test_csv ../../data/metadata/splits/protein_level_test.csv \
        --npy_dir ../../data/processed_v4/features_90pct/sanity_check_features \
        --batch_size 1 --num_workers 0 \
        --patience 50 --epochs 200 \
        --output_dir ../../results/tcn_oracle_90pct_receptor

Using device: cpu
Output directory: ../../results/tcn_oracle_90pct_receptor/tcn_20260312_143839

Loading datasets...
Loaded 203 samples
  Multi: 62.0 (30.5%)
  Single: 141 (69.5%)
  Using frac=1.0 of each trajectory
Loaded 43 samples
  Multi: 9.0 (20.9%)
  Single: 34 (79.1%)
  Using frac=1.0 of each trajectory
  Auto-detected 7 features from data

Initializing TCN with 7 input features...
TCN Summary:
  Receptive field:   61 timesteps
  Pooling:           mean
  Parameters:        14,076
  Architecture:      [25, 25, 25, 25]

Using pos_weight=1.0 for imbalanced data

Starting training...
Epoch 1/200
  Train: Loss=1.7125, Bal Acc=0.490, AUROC=0.494, AP=0.293
  Test:  Loss=0.7735, Bal Acc=0.500, AUROC=0.709, AP=0.477
   New best AUROC: 0.709
Epoch 2/200
  Train: Loss=1.2216, Bal Acc=0.500, AUROC=0.576, AP=0.357
  Test:  Loss=0.5264, Bal Acc=0.500, AUROC=0.758, AP=0.522
   New best AUROC: 0.758
Epoch 3/200
  Train: Loss=1.1786, Bal Acc=0.500, AUROC=0.554, AP=0.344
  Test:  Loss=0.5509, Bal Acc=0.500, AUROC=0.765, AP=0.533
   New best AUROC: 0.765
Epoch 4/200
  Train: Loss=1.1518, Bal Acc=0.500, AUROC=0.598, AP=0.417
  Test:  Loss=0.6095, Bal Acc=0.500, AUROC=0.797, AP=0.581
   New best AUROC: 0.797
Epoch 5/200
  Train: Loss=1.0478, Bal Acc=0.500, AUROC=0.625, AP=0.420
  Test:  Loss=0.6622, Bal Acc=0.500, AUROC=0.788, AP=0.559
Epoch 6/200
  Train: Loss=1.0990, Bal Acc=0.517, AUROC=0.623, AP=0.412
  Test:  Loss=0.5775, Bal Acc=0.500, AUROC=0.807, AP=0.548
   New best AUROC: 0.807
Epoch 7/200
  Train: Loss=0.9539, Bal Acc=0.533, AUROC=0.687, AP=0.513
  Test:  Loss=0.5321, Bal Acc=0.538, AUROC=0.778, AP=0.454
Epoch 8/200
  Train: Loss=1.0317, Bal Acc=0.593, AUROC=0.718, AP=0.551
  Test:  Loss=0.5023, Bal Acc=0.556, AUROC=0.778, AP=0.487
Epoch 9/200
  Train: Loss=0.8638, Bal Acc=0.573, AUROC=0.731, AP=0.542
  Test:  Loss=0.5004, Bal Acc=0.567, AUROC=0.794, AP=0.523
Epoch 10/200
  Train: Loss=0.7924, Bal Acc=0.582, AUROC=0.774, AP=0.607
  Test:  Loss=0.6797, Bal Acc=0.590, AUROC=0.748, AP=0.516
Epoch 11/200
  Train: Loss=0.7779, Bal Acc=0.693, AUROC=0.795, AP=0.661
  Test:  Loss=0.6956, Bal Acc=0.564, AUROC=0.830, AP=0.512
   New best AUROC: 0.830
Epoch 12/200
  Train: Loss=0.8041, Bal Acc=0.690, AUROC=0.817, AP=0.675
  Test:  Loss=0.6655, Bal Acc=0.564, AUROC=0.833, AP=0.531
   New best AUROC: 0.833
Epoch 13/200
  Train: Loss=0.7262, Bal Acc=0.675, AUROC=0.837, AP=0.692
  Test:  Loss=0.6526, Bal Acc=0.634, AUROC=0.837, AP=0.520
   New best AUROC: 0.837
Epoch 14/200
  Train: Loss=0.6313, Bal Acc=0.719, AUROC=0.880, AP=0.742
  Test:  Loss=0.5622, Bal Acc=0.760, AUROC=0.908, AP=0.741
   New best AUROC: 0.908
Epoch 15/200
  Train: Loss=0.7106, Bal Acc=0.776, AUROC=0.881, AP=0.793
  Test:  Loss=0.7215, Bal Acc=0.815, AUROC=0.892, AP=0.736
Epoch 16/200
  Train: Loss=0.7106, Bal Acc=0.757, AUROC=0.885, AP=0.770
  Test:  Loss=1.0411, Bal Acc=0.827, AUROC=0.908, AP=0.764
   New best AUROC: 0.908
Epoch 17/200
  Train: Loss=0.6977, Bal Acc=0.815, AUROC=0.901, AP=0.801
  Test:  Loss=0.5060, Bal Acc=0.815, AUROC=0.902, AP=0.825
Epoch 18/200
  Train: Loss=0.7390, Bal Acc=0.762, AUROC=0.887, AP=0.758
  Test:  Loss=0.7340, Bal Acc=0.871, AUROC=0.912, AP=0.725
   New best AUROC: 0.912
Epoch 19/200
  Train: Loss=0.6471, Bal Acc=0.771, AUROC=0.888, AP=0.799
  Test:  Loss=0.9770, Bal Acc=0.842, AUROC=0.935, AP=0.836
   New best AUROC: 0.935
Epoch 20/200
  Train: Loss=0.6958, Bal Acc=0.773, AUROC=0.901, AP=0.822
  Test:  Loss=0.6223, Bal Acc=0.815, AUROC=0.941, AP=0.875
   New best AUROC: 0.941
Epoch 21/200
  Train: Loss=0.6255, Bal Acc=0.771, AUROC=0.902, AP=0.829
  Test:  Loss=0.9633, Bal Acc=0.926, AUROC=0.935, AP=0.803
Epoch 22/200
  Train: Loss=0.6631, Bal Acc=0.785, AUROC=0.904, AP=0.833
  Test:  Loss=0.4751, Bal Acc=0.748, AUROC=0.938, AP=0.844
Epoch 23/200
  Train: Loss=0.6069, Bal Acc=0.804, AUROC=0.920, AP=0.837
  Test:  Loss=0.6823, Bal Acc=0.871, AUROC=0.951, AP=0.864
   New best AUROC: 0.951
Epoch 24/200
  Train: Loss=0.6002, Bal Acc=0.803, AUROC=0.927, AP=0.847
  Test:  Loss=0.3689, Bal Acc=0.845, AUROC=0.967, AP=0.918
   New best AUROC: 0.967
Epoch 25/200
  Train: Loss=0.6271, Bal Acc=0.805, AUROC=0.928, AP=0.831
  Test:  Loss=0.5127, Bal Acc=0.871, AUROC=0.935, AP=0.787
Epoch 26/200
  Train: Loss=0.4786, Bal Acc=0.845, AUROC=0.938, AP=0.882
  Test:  Loss=0.4117, Bal Acc=0.804, AUROC=0.951, AP=0.827
Epoch 27/200
  Train: Loss=0.5010, Bal Acc=0.843, AUROC=0.942, AP=0.868
  Test:  Loss=0.7392, Bal Acc=0.926, AUROC=0.948, AP=0.818
Epoch 28/200
  Train: Loss=0.5352, Bal Acc=0.847, AUROC=0.943, AP=0.876
  Test:  Loss=3.7945, Bal Acc=0.838, AUROC=0.949, AP=0.767
Epoch 29/200
  Train: Loss=0.5407, Bal Acc=0.836, AUROC=0.943, AP=0.882
  Test:  Loss=3.6796, Bal Acc=0.882, AUROC=0.944, AP=0.734
Epoch 30/200
  Train: Loss=0.4614, Bal Acc=0.855, AUROC=0.948, AP=0.904
  Test:  Loss=0.6374, Bal Acc=0.871, AUROC=0.967, AP=0.909
Epoch 31/200
  Train: Loss=0.5386, Bal Acc=0.859, AUROC=0.946, AP=0.896
  Test:  Loss=0.9279, Bal Acc=0.667, AUROC=0.954, AP=0.866
Epoch 32/200
  Train: Loss=0.7244, Bal Acc=0.793, AUROC=0.923, AP=0.829
  Test:  Loss=0.6319, Bal Acc=0.871, AUROC=0.954, AP=0.846
Epoch 33/200
  Train: Loss=0.5166, Bal Acc=0.845, AUROC=0.947, AP=0.909
  Test:  Loss=3.5005, Bal Acc=0.882, AUROC=0.949, AP=0.760
Epoch 34/200
  Train: Loss=0.4734, Bal Acc=0.842, AUROC=0.951, AP=0.891
  Test:  Loss=0.5364, Bal Acc=0.871, AUROC=0.958, AP=0.883
Epoch 35/200
  Train: Loss=0.5141, Bal Acc=0.845, AUROC=0.956, AP=0.895
  Test:  Loss=1.4746, Bal Acc=0.853, AUROC=0.956, AP=0.884
Epoch 36/200
  Train: Loss=0.4587, Bal Acc=0.887, AUROC=0.955, AP=0.909
  Test:  Loss=0.5282, Bal Acc=0.886, AUROC=0.954, AP=0.847
Epoch 37/200
  Train: Loss=0.3705, Bal Acc=0.869, AUROC=0.967, AP=0.928
  Test:  Loss=0.7363, Bal Acc=0.926, AUROC=0.958, AP=0.869
Epoch 38/200
  Train: Loss=0.3270, Bal Acc=0.903, AUROC=0.972, AP=0.939
  Test:  Loss=1.1685, Bal Acc=0.926, AUROC=0.948, AP=0.826
Epoch 39/200
  Train: Loss=0.3094, Bal Acc=0.892, AUROC=0.975, AP=0.947
  Test:  Loss=0.8661, Bal Acc=0.926, AUROC=0.951, AP=0.830
Epoch 40/200
  Train: Loss=0.3754, Bal Acc=0.895, AUROC=0.971, AP=0.931
  Test:  Loss=0.8529, Bal Acc=0.926, AUROC=0.951, AP=0.830
Epoch 41/200
  Train: Loss=0.3331, Bal Acc=0.899, AUROC=0.970, AP=0.936
  Test:  Loss=3.4528, Bal Acc=0.912, AUROC=0.948, AP=0.761
Epoch 42/200
  Train: Loss=0.3473, Bal Acc=0.923, AUROC=0.975, AP=0.940
  Test:  Loss=0.9950, Bal Acc=0.926, AUROC=0.948, AP=0.821
Epoch 43/200
  Train: Loss=0.4127, Bal Acc=0.877, AUROC=0.971, AP=0.936
  Test:  Loss=3.5338, Bal Acc=0.897, AUROC=0.949, AP=0.775
Epoch 44/200
  Train: Loss=0.3314, Bal Acc=0.923, AUROC=0.976, AP=0.958
  Test:  Loss=0.3938, Bal Acc=0.845, AUROC=0.964, AP=0.889
Epoch 45/200
  Train: Loss=0.2676, Bal Acc=0.898, AUROC=0.981, AP=0.962
  Test:  Loss=3.0065, Bal Acc=0.926, AUROC=0.951, AP=0.740
Epoch 46/200
  Train: Loss=1.2734, Bal Acc=0.903, AUROC=0.967, AP=0.893
  Test:  Loss=0.5300, Bal Acc=0.886, AUROC=0.954, AP=0.836
Epoch 47/200
  Train: Loss=0.2577, Bal Acc=0.930, AUROC=0.984, AP=0.959
  Test:  Loss=0.9873, Bal Acc=0.926, AUROC=0.964, AP=0.880
Epoch 48/200
  Train: Loss=0.3182, Bal Acc=0.933, AUROC=0.981, AP=0.959
  Test:  Loss=0.7490, Bal Acc=0.926, AUROC=0.954, AP=0.817
Epoch 49/200
  Train: Loss=0.2566, Bal Acc=0.937, AUROC=0.984, AP=0.965
  Test:  Loss=3.4260, Bal Acc=0.912, AUROC=0.951, AP=0.770
Epoch 50/200
  Train: Loss=0.6781, Bal Acc=0.922, AUROC=0.983, AP=0.939
  Test:  Loss=3.2990, Bal Acc=0.912, AUROC=0.954, AP=0.776
Epoch 51/200
  Train: Loss=0.3214, Bal Acc=0.939, AUROC=0.982, AP=0.960
  Test:  Loss=3.2017, Bal Acc=0.926, AUROC=0.953, AP=0.769
Epoch 52/200
  Train: Loss=0.2858, Bal Acc=0.934, AUROC=0.983, AP=0.965
  Test:  Loss=3.3853, Bal Acc=0.926, AUROC=0.962, AP=0.832
Epoch 53/200
  Train: Loss=0.2734, Bal Acc=0.941, AUROC=0.984, AP=0.963
  Test:  Loss=3.2166, Bal Acc=0.926, AUROC=0.948, AP=0.756
Epoch 54/200
  Train: Loss=0.2851, Bal Acc=0.929, AUROC=0.985, AP=0.961
  Test:  Loss=3.3429, Bal Acc=0.926, AUROC=0.949, AP=0.756
Epoch 55/200
  Train: Loss=0.2877, Bal Acc=0.938, AUROC=0.985, AP=0.963
  Test:  Loss=1.0009, Bal Acc=0.926, AUROC=0.954, AP=0.843
Epoch 56/200
  Train: Loss=0.2293, Bal Acc=0.941, AUROC=0.987, AP=0.971
  Test:  Loss=3.3712, Bal Acc=0.912, AUROC=0.954, AP=0.776
Epoch 57/200
  Train: Loss=0.2384, Bal Acc=0.938, AUROC=0.987, AP=0.967
  Test:  Loss=0.7471, Bal Acc=0.886, AUROC=0.954, AP=0.852
Epoch 58/200
  Train: Loss=0.2288, Bal Acc=0.949, AUROC=0.989, AP=0.975
  Test:  Loss=1.2810, Bal Acc=0.926, AUROC=0.958, AP=0.858
Epoch 59/200
  Train: Loss=0.2274, Bal Acc=0.957, AUROC=0.989, AP=0.974
  Test:  Loss=1.1209, Bal Acc=0.926, AUROC=0.956, AP=0.845
Epoch 60/200
  Train: Loss=0.2583, Bal Acc=0.941, AUROC=0.988, AP=0.969
  Test:  Loss=5.2592, Bal Acc=0.912, AUROC=0.941, AP=0.709
Epoch 61/200
  Train: Loss=0.2223, Bal Acc=0.949, AUROC=0.987, AP=0.972
  Test:  Loss=3.1483, Bal Acc=0.926, AUROC=0.949, AP=0.756
Epoch 62/200
  Train: Loss=0.6111, Bal Acc=0.957, AUROC=0.989, AP=0.956
  Test:  Loss=5.3945, Bal Acc=0.912, AUROC=0.944, AP=0.718
Epoch 63/200
  Train: Loss=0.2553, Bal Acc=0.937, AUROC=0.988, AP=0.970
  Test:  Loss=1.2640, Bal Acc=0.926, AUROC=0.959, AP=0.858
Epoch 64/200
  Train: Loss=0.2028, Bal Acc=0.957, AUROC=0.990, AP=0.973
  Test:  Loss=1.2199, Bal Acc=0.926, AUROC=0.959, AP=0.859
Epoch 65/200
  Train: Loss=0.2383, Bal Acc=0.949, AUROC=0.989, AP=0.972
  Test:  Loss=3.2458, Bal Acc=0.926, AUROC=0.956, AP=0.770
Epoch 66/200
  Train: Loss=0.2632, Bal Acc=0.957, AUROC=0.988, AP=0.964
  Test:  Loss=1.2614, Bal Acc=0.926, AUROC=0.956, AP=0.852
Epoch 67/200
  Train: Loss=0.1770, Bal Acc=0.957, AUROC=0.992, AP=0.980
  Test:  Loss=1.1002, Bal Acc=0.926, AUROC=0.956, AP=0.845
Epoch 68/200
  Train: Loss=0.2072, Bal Acc=0.961, AUROC=0.989, AP=0.975
  Test:  Loss=5.1907, Bal Acc=0.926, AUROC=0.938, AP=0.688
Epoch 69/200
  Train: Loss=0.2150, Bal Acc=0.957, AUROC=0.991, AP=0.975
  Test:  Loss=5.3278, Bal Acc=0.926, AUROC=0.944, AP=0.718
Epoch 70/200
  Train: Loss=0.1938, Bal Acc=0.957, AUROC=0.992, AP=0.981
  Test:  Loss=1.0868, Bal Acc=0.926, AUROC=0.954, AP=0.845
Epoch 71/200
  Train: Loss=0.2231, Bal Acc=0.949, AUROC=0.990, AP=0.974
  Test:  Loss=1.1857, Bal Acc=0.926, AUROC=0.954, AP=0.845
Epoch 72/200
  Train: Loss=0.1736, Bal Acc=0.961, AUROC=0.995, AP=0.988
  Test:  Loss=3.1629, Bal Acc=0.926, AUROC=0.949, AP=0.756
Epoch 73/200
  Train: Loss=0.1953, Bal Acc=0.957, AUROC=0.992, AP=0.980
  Test:  Loss=1.1562, Bal Acc=0.926, AUROC=0.954, AP=0.845
Epoch 74/200
  Train: Loss=0.2380, Bal Acc=0.961, AUROC=0.990, AP=0.973
  Test:  Loss=5.1708, Bal Acc=0.926, AUROC=0.941, AP=0.696

Early stopping at epoch 74 (no improvement for 50 epochs)

================================================================================
FINAL EVALUATION (best model)
================================================================================

Test Metrics:
  Balanced Accuracy: 0.845
  AUROC: 0.967
  Avg Precision: 0.918

Confusion Matrix:
  TN=31, FP=3
  FN=2, TP=7

Classification Report:
              precision    recall  f1-score   support

single_state       0.94      0.91      0.93        34
 multi_state       0.70      0.78      0.74         9

    accuracy                           0.88        43
   macro avg       0.82      0.84      0.83        43
weighted avg       0.89      0.88      0.89        43


 Results saved to ../../results/tcn_oracle_90pct_receptor/tcn_20260312_143839
Using device: cpu
Output directory: ../../results/tcn_oracle_90pct_receptor/tcn_20260312_144410

Loading datasets...
Loaded 203 samples
  Multi: 62.0 (30.5%)
  Single: 141 (69.5%)
  Using frac=1.0 of each trajectory
Loaded 43 samples
  Multi: 9.0 (20.9%)
  Single: 34 (79.1%)
  Using frac=1.0 of each trajectory
  Auto-detected 7 features from data

Initializing TCN with 7 input features...
TCN Summary:
  Receptive field:   61 timesteps
  Pooling:           mean
  Parameters:        14,076
  Architecture:      [25, 25, 25, 25]

Using pos_weight=1.0 for imbalanced data

Starting training...
Epoch 1/200
  Train: Loss=1.8807, Bal Acc=0.489, AUROC=0.533, AP=0.336
  Test:  Loss=0.9649, Bal Acc=0.500, AUROC=0.814, AP=0.686
   New best AUROC: 0.814
Epoch 2/200
  Train: Loss=1.1307, Bal Acc=0.501, AUROC=0.629, AP=0.421
  Test:  Loss=0.5539, Bal Acc=0.500, AUROC=0.794, AP=0.555
Epoch 3/200
  Train: Loss=1.0073, Bal Acc=0.492, AUROC=0.690, AP=0.442
  Test:  Loss=0.4313, Bal Acc=0.500, AUROC=0.843, AP=0.718
   New best AUROC: 0.843
Epoch 4/200
  Train: Loss=0.8905, Bal Acc=0.532, AUROC=0.724, AP=0.570
  Test:  Loss=0.4930, Bal Acc=0.623, AUROC=0.817, AP=0.539
Epoch 5/200
  Train: Loss=0.8146, Bal Acc=0.658, AUROC=0.807, AP=0.589
  Test:  Loss=1.0165, Bal Acc=0.742, AUROC=0.830, AP=0.648
Epoch 6/200
  Train: Loss=0.7498, Bal Acc=0.698, AUROC=0.808, AP=0.717
  Test:  Loss=0.5347, Bal Acc=0.786, AUROC=0.886, AP=0.815
   New best AUROC: 0.886
Epoch 7/200
  Train: Loss=0.7238, Bal Acc=0.726, AUROC=0.835, AP=0.701
  Test:  Loss=0.3806, Bal Acc=0.778, AUROC=0.915, AP=0.801
   New best AUROC: 0.915
Epoch 8/200
  Train: Loss=0.7372, Bal Acc=0.672, AUROC=0.825, AP=0.698
  Test:  Loss=0.7158, Bal Acc=0.730, AUROC=0.846, AP=0.583
Epoch 9/200
  Train: Loss=0.8067, Bal Acc=0.707, AUROC=0.817, AP=0.702
  Test:  Loss=0.3119, Bal Acc=0.778, AUROC=0.928, AP=0.855
   New best AUROC: 0.928
Epoch 10/200
  Train: Loss=0.7671, Bal Acc=0.698, AUROC=0.836, AP=0.694
  Test:  Loss=0.3978, Bal Acc=0.734, AUROC=0.889, AP=0.750
Epoch 11/200
  Train: Loss=0.6767, Bal Acc=0.710, AUROC=0.847, AP=0.761
  Test:  Loss=0.6082, Bal Acc=0.730, AUROC=0.833, AP=0.580
Epoch 12/200
  Train: Loss=0.7144, Bal Acc=0.712, AUROC=0.853, AP=0.712
  Test:  Loss=5.8104, Bal Acc=0.783, AUROC=0.886, AP=0.588
Epoch 13/200
  Train: Loss=0.7318, Bal Acc=0.705, AUROC=0.849, AP=0.724
  Test:  Loss=0.4451, Bal Acc=0.789, AUROC=0.899, AP=0.784
Epoch 14/200
  Train: Loss=0.7761, Bal Acc=0.746, AUROC=0.876, AP=0.742
  Test:  Loss=0.2980, Bal Acc=0.874, AUROC=0.948, AP=0.893
   New best AUROC: 0.948
Epoch 15/200
  Train: Loss=0.6951, Bal Acc=0.697, AUROC=0.864, AP=0.730
  Test:  Loss=0.3058, Bal Acc=0.845, AUROC=0.941, AP=0.886
Epoch 16/200
  Train: Loss=0.6372, Bal Acc=0.735, AUROC=0.860, AP=0.749
  Test:  Loss=0.3823, Bal Acc=0.845, AUROC=0.922, AP=0.785
Epoch 17/200
  Train: Loss=0.6365, Bal Acc=0.756, AUROC=0.890, AP=0.779
  Test:  Loss=0.9183, Bal Acc=0.812, AUROC=0.925, AP=0.865
Epoch 18/200
  Train: Loss=0.6594, Bal Acc=0.757, AUROC=0.882, AP=0.786
  Test:  Loss=0.4385, Bal Acc=0.871, AUROC=0.944, AP=0.894
Epoch 19/200
  Train: Loss=0.5677, Bal Acc=0.772, AUROC=0.905, AP=0.819
  Test:  Loss=0.5441, Bal Acc=0.815, AUROC=0.938, AP=0.808
Epoch 20/200
  Train: Loss=0.7073, Bal Acc=0.766, AUROC=0.895, AP=0.804
  Test:  Loss=0.3262, Bal Acc=0.900, AUROC=0.938, AP=0.825
Epoch 21/200
  Train: Loss=0.6785, Bal Acc=0.774, AUROC=0.897, AP=0.812
  Test:  Loss=0.3346, Bal Acc=0.845, AUROC=0.948, AP=0.874
Epoch 22/200
  Train: Loss=0.6665, Bal Acc=0.804, AUROC=0.900, AP=0.814
  Test:  Loss=0.3739, Bal Acc=0.678, AUROC=0.938, AP=0.809
Epoch 23/200
  Train: Loss=0.6494, Bal Acc=0.803, AUROC=0.911, AP=0.817
  Test:  Loss=0.7304, Bal Acc=0.842, AUROC=0.951, AP=0.881
   New best AUROC: 0.951
Epoch 24/200
  Train: Loss=0.6263, Bal Acc=0.808, AUROC=0.910, AP=0.825
  Test:  Loss=0.3678, Bal Acc=0.778, AUROC=0.944, AP=0.853
Epoch 25/200
  Train: Loss=1.1402, Bal Acc=0.810, AUROC=0.905, AP=0.788
  Test:  Loss=0.3413, Bal Acc=0.845, AUROC=0.948, AP=0.878
Epoch 26/200
  Train: Loss=0.6335, Bal Acc=0.770, AUROC=0.913, AP=0.810
  Test:  Loss=0.7954, Bal Acc=0.926, AUROC=0.938, AP=0.802
Epoch 27/200
  Train: Loss=0.6050, Bal Acc=0.803, AUROC=0.921, AP=0.842
  Test:  Loss=0.7065, Bal Acc=0.842, AUROC=0.941, AP=0.837
Epoch 28/200
  Train: Loss=0.7110, Bal Acc=0.785, AUROC=0.905, AP=0.810
  Test:  Loss=0.7997, Bal Acc=0.842, AUROC=0.951, AP=0.874
Epoch 29/200
  Train: Loss=0.5761, Bal Acc=0.815, AUROC=0.925, AP=0.851
  Test:  Loss=0.3209, Bal Acc=0.900, AUROC=0.961, AP=0.867
   New best AUROC: 0.961
Epoch 30/200
  Train: Loss=0.6165, Bal Acc=0.812, AUROC=0.924, AP=0.852
  Test:  Loss=0.3569, Bal Acc=0.900, AUROC=0.951, AP=0.853
Epoch 31/200
  Train: Loss=0.5664, Bal Acc=0.810, AUROC=0.936, AP=0.861
  Test:  Loss=0.7433, Bal Acc=0.856, AUROC=0.941, AP=0.851
Epoch 32/200
  Train: Loss=0.6338, Bal Acc=0.812, AUROC=0.921, AP=0.850
  Test:  Loss=0.3440, Bal Acc=0.900, AUROC=0.954, AP=0.897
Epoch 33/200
  Train: Loss=1.0453, Bal Acc=0.851, AUROC=0.930, AP=0.834
  Test:  Loss=0.2691, Bal Acc=0.859, AUROC=0.964, AP=0.879
   New best AUROC: 0.964
Epoch 34/200
  Train: Loss=0.5644, Bal Acc=0.813, AUROC=0.931, AP=0.855
  Test:  Loss=0.4637, Bal Acc=0.886, AUROC=0.954, AP=0.854
Epoch 35/200
  Train: Loss=1.0404, Bal Acc=0.816, AUROC=0.931, AP=0.831
  Test:  Loss=0.6870, Bal Acc=0.856, AUROC=0.954, AP=0.891
Epoch 36/200
  Train: Loss=0.6231, Bal Acc=0.835, AUROC=0.933, AP=0.866
  Test:  Loss=0.8249, Bal Acc=0.812, AUROC=0.948, AP=0.872
Epoch 37/200
  Train: Loss=0.9913, Bal Acc=0.849, AUROC=0.944, AP=0.843
  Test:  Loss=0.5283, Bal Acc=0.871, AUROC=0.954, AP=0.869
Epoch 38/200
  Train: Loss=0.5088, Bal Acc=0.847, AUROC=0.952, AP=0.892
  Test:  Loss=0.6496, Bal Acc=0.886, AUROC=0.967, AP=0.902
   New best AUROC: 0.967
Epoch 39/200
  Train: Loss=0.5814, Bal Acc=0.821, AUROC=0.943, AP=0.878
  Test:  Loss=1.5207, Bal Acc=0.838, AUROC=0.954, AP=0.866
Epoch 40/200
  Train: Loss=0.4386, Bal Acc=0.844, AUROC=0.954, AP=0.905
  Test:  Loss=0.6384, Bal Acc=0.886, AUROC=0.961, AP=0.880
Epoch 41/200
  Train: Loss=0.6764, Bal Acc=0.869, AUROC=0.939, AP=0.869
  Test:  Loss=0.4103, Bal Acc=0.874, AUROC=0.944, AP=0.890
Epoch 42/200
  Train: Loss=0.5960, Bal Acc=0.812, AUROC=0.942, AP=0.868
  Test:  Loss=0.8423, Bal Acc=0.912, AUROC=0.961, AP=0.877
Epoch 43/200
  Train: Loss=0.5449, Bal Acc=0.805, AUROC=0.943, AP=0.890
  Test:  Loss=0.6159, Bal Acc=0.856, AUROC=0.964, AP=0.907
Epoch 44/200
  Train: Loss=0.4719, Bal Acc=0.877, AUROC=0.958, AP=0.900
  Test:  Loss=7.6505, Bal Acc=0.882, AUROC=0.931, AP=0.639
Epoch 45/200
  Train: Loss=0.9551, Bal Acc=0.885, AUROC=0.956, AP=0.884
  Test:  Loss=0.2895, Bal Acc=0.915, AUROC=0.971, AP=0.913
   New best AUROC: 0.971
Epoch 46/200
  Train: Loss=0.9187, Bal Acc=0.899, AUROC=0.957, AP=0.884
  Test:  Loss=0.3556, Bal Acc=0.815, AUROC=0.967, AP=0.918
Epoch 47/200
  Train: Loss=0.7050, Bal Acc=0.832, AUROC=0.938, AP=0.854
  Test:  Loss=1.0868, Bal Acc=0.926, AUROC=0.958, AP=0.872
Epoch 48/200
  Train: Loss=0.9502, Bal Acc=0.892, AUROC=0.957, AP=0.892
  Test:  Loss=3.8612, Bal Acc=0.853, AUROC=0.954, AP=0.809
Epoch 49/200
  Train: Loss=0.9316, Bal Acc=0.888, AUROC=0.962, AP=0.898
  Test:  Loss=1.0159, Bal Acc=0.912, AUROC=0.961, AP=0.874
Epoch 50/200
  Train: Loss=0.5121, Bal Acc=0.856, AUROC=0.956, AP=0.899
  Test:  Loss=0.8657, Bal Acc=0.941, AUROC=0.954, AP=0.840
Epoch 51/200
  Train: Loss=0.5490, Bal Acc=0.858, AUROC=0.952, AP=0.889
  Test:  Loss=0.3871, Bal Acc=0.900, AUROC=0.967, AP=0.905
Epoch 52/200
  Train: Loss=1.3880, Bal Acc=0.896, AUROC=0.959, AP=0.865
  Test:  Loss=1.2351, Bal Acc=0.912, AUROC=0.948, AP=0.823
Epoch 53/200
  Train: Loss=0.8476, Bal Acc=0.902, AUROC=0.968, AP=0.921
  Test:  Loss=7.9659, Bal Acc=0.838, AUROC=0.931, AP=0.668
Epoch 54/200
  Train: Loss=0.8613, Bal Acc=0.864, AUROC=0.960, AP=0.902
  Test:  Loss=0.4086, Bal Acc=0.830, AUROC=0.967, AP=0.909
Epoch 55/200
  Train: Loss=0.8654, Bal Acc=0.912, AUROC=0.966, AP=0.915
  Test:  Loss=0.9503, Bal Acc=0.886, AUROC=0.961, AP=0.880
Epoch 56/200
  Train: Loss=0.9388, Bal Acc=0.896, AUROC=0.966, AP=0.923
  Test:  Loss=0.6754, Bal Acc=0.886, AUROC=0.971, AP=0.915
Epoch 57/200
  Train: Loss=0.7551, Bal Acc=0.908, AUROC=0.976, AP=0.925
  Test:  Loss=1.2436, Bal Acc=0.926, AUROC=0.967, AP=0.902
Epoch 58/200
  Train: Loss=0.7588, Bal Acc=0.929, AUROC=0.976, AP=0.935
  Test:  Loss=0.6990, Bal Acc=0.941, AUROC=0.974, AP=0.929
   New best AUROC: 0.974
Epoch 59/200

In [13]:
# --- Oracle/sanity check features at 10% ---
# Upper bound at 10%

for seed in [0, 1, 2]:
    !python train_tcn.py \
        --train_csv ../../data/metadata/splits/protein_level_train.csv \
        --test_csv ../../data/metadata/splits/protein_level_test.csv \
        --npy_dir ../../data/processed_v4/features_10pct/sanity_check_features \
        --batch_size 1 --num_workers 0 \
        --patience 50 --epochs 200 \
        --output_dir ../../results/tcn_oracle_10pct_receptor

Using device: cpu
Output directory: ../../results/tcn_oracle_10pct_receptor/tcn_20260312_153323

Loading datasets...
Loaded 203 samples
  Multi: 62.0 (30.5%)
  Single: 141 (69.5%)
  Using frac=1.0 of each trajectory
Loaded 43 samples
  Multi: 9.0 (20.9%)
  Single: 34 (79.1%)
  Using frac=1.0 of each trajectory
  Auto-detected 7 features from data

Initializing TCN with 7 input features...
TCN Summary:
  Receptive field:   61 timesteps
  Pooling:           mean
  Parameters:        14,076
  Architecture:      [25, 25, 25, 25]

Using pos_weight=1.0 for imbalanced data

Starting training...
Epoch 1/200
  Train: Loss=1.8451, Bal Acc=0.497, AUROC=0.395, AP=0.280
  Test:  Loss=0.8090, Bal Acc=0.500, AUROC=0.448, AP=0.305
   New best AUROC: 0.448
Epoch 2/200
  Train: Loss=1.3810, Bal Acc=0.500, AUROC=0.393, AP=0.260
  Test:  Loss=0.6802, Bal Acc=0.500, AUROC=0.621, AP=0.343
   New best AUROC: 0.621
Epoch 3/200
  Train: Loss=1.2222, Bal Acc=0.508, AUROC=0.558, AP=0.395
  Test:  Loss=1.4762, Bal Acc=0.500, AUROC=0.471, AP=0.226
Epoch 4/200
  Train: Loss=1.1741, Bal Acc=0.508, AUROC=0.583, AP=0.398
  Test:  Loss=0.7153, Bal Acc=0.500, AUROC=0.663, AP=0.338
   New best AUROC: 0.663
Epoch 5/200
  Train: Loss=1.0462, Bal Acc=0.500, AUROC=0.669, AP=0.470
  Test:  Loss=1.0319, Bal Acc=0.500, AUROC=0.539, AP=0.250
Epoch 6/200
  Train: Loss=1.0487, Bal Acc=0.537, AUROC=0.642, AP=0.489
  Test:  Loss=0.6982, Bal Acc=0.500, AUROC=0.634, AP=0.277
Epoch 7/200
  Train: Loss=0.9915, Bal Acc=0.530, AUROC=0.679, AP=0.463
  Test:  Loss=0.8429, Bal Acc=0.500, AUROC=0.592, AP=0.302
Epoch 8/200
  Train: Loss=1.0306, Bal Acc=0.497, AUROC=0.672, AP=0.485
  Test:  Loss=0.5152, Bal Acc=0.538, AUROC=0.699, AP=0.347
   New best AUROC: 0.699
Epoch 9/200
  Train: Loss=0.9407, Bal Acc=0.528, AUROC=0.690, AP=0.471
  Test:  Loss=0.6822, Bal Acc=0.456, AUROC=0.680, AP=0.317
Epoch 10/200
  Train: Loss=0.9031, Bal Acc=0.566, AUROC=0.716, AP=0.508
  Test:  Loss=0.6962, Bal Acc=0.645, AUROC=0.725, AP=0.345
   New best AUROC: 0.725
Epoch 11/200
  Train: Loss=0.8833, Bal Acc=0.595, AUROC=0.722, AP=0.587
  Test:  Loss=0.7387, Bal Acc=0.634, AUROC=0.696, AP=0.340
Epoch 12/200
  Train: Loss=0.9087, Bal Acc=0.596, AUROC=0.718, AP=0.558
  Test:  Loss=0.7098, Bal Acc=0.690, AUROC=0.719, AP=0.347
Epoch 13/200
  Train: Loss=0.8260, Bal Acc=0.614, AUROC=0.759, AP=0.610
  Test:  Loss=0.9863, Bal Acc=0.485, AUROC=0.647, AP=0.294
Epoch 14/200
  Train: Loss=0.9187, Bal Acc=0.591, AUROC=0.697, AP=0.529
  Test:  Loss=0.6973, Bal Acc=0.500, AUROC=0.703, AP=0.328
Epoch 15/200
  Train: Loss=0.8877, Bal Acc=0.603, AUROC=0.753, AP=0.586
  Test:  Loss=0.7995, Bal Acc=0.730, AUROC=0.765, AP=0.385
   New best AUROC: 0.765
Epoch 16/200
  Train: Loss=0.8668, Bal Acc=0.641, AUROC=0.768, AP=0.629
  Test:  Loss=0.7753, Bal Acc=0.716, AUROC=0.771, AP=0.378
   New best AUROC: 0.771
Epoch 17/200
  Train: Loss=0.8853, Bal Acc=0.654, AUROC=0.765, AP=0.622
  Test:  Loss=1.0262, Bal Acc=0.456, AUROC=0.722, AP=0.346
Epoch 18/200
  Train: Loss=0.8349, Bal Acc=0.669, AUROC=0.776, AP=0.654
  Test:  Loss=1.2384, Bal Acc=0.526, AUROC=0.680, AP=0.320
Epoch 19/200
  Train: Loss=0.9388, Bal Acc=0.653, AUROC=0.794, AP=0.622
  Test:  Loss=4.1164, Bal Acc=0.838, AUROC=0.770, AP=0.375
Epoch 20/200
  Train: Loss=0.8399, Bal Acc=0.671, AUROC=0.776, AP=0.651
  Test:  Loss=0.6810, Bal Acc=0.552, AUROC=0.781, AP=0.461
   New best AUROC: 0.781
Epoch 21/200
  Train: Loss=0.7565, Bal Acc=0.653, AUROC=0.823, AP=0.676
  Test:  Loss=1.0898, Bal Acc=0.716, AUROC=0.755, AP=0.352
Epoch 22/200
  Train: Loss=0.8009, Bal Acc=0.706, AUROC=0.811, AP=0.704
  Test:  Loss=0.8363, Bal Acc=0.567, AUROC=0.716, AP=0.366
Epoch 23/200
  Train: Loss=0.8345, Bal Acc=0.649, AUROC=0.791, AP=0.669
  Test:  Loss=1.0711, Bal Acc=0.608, AUROC=0.784, AP=0.388
   New best AUROC: 0.784
Epoch 24/200
  Train: Loss=0.7634, Bal Acc=0.658, AUROC=0.796, AP=0.671
  Test:  Loss=1.1227, Bal Acc=0.608, AUROC=0.801, AP=0.411
   New best AUROC: 0.801
Epoch 25/200
  Train: Loss=0.7585, Bal Acc=0.689, AUROC=0.816, AP=0.706
  Test:  Loss=3.1227, Bal Acc=0.619, AUROC=0.797, AP=0.409
Epoch 26/200
  Train: Loss=0.7723, Bal Acc=0.686, AUROC=0.812, AP=0.692
  Test:  Loss=1.2986, Bal Acc=0.567, AUROC=0.755, AP=0.383
Epoch 27/200
  Train: Loss=0.8127, Bal Acc=0.686, AUROC=0.809, AP=0.675
  Test:  Loss=3.1977, Bal Acc=0.608, AUROC=0.768, AP=0.395
Epoch 28/200
  Train: Loss=0.7284, Bal Acc=0.713, AUROC=0.837, AP=0.753
  Test:  Loss=0.9968, Bal Acc=0.730, AUROC=0.797, AP=0.491
Epoch 29/200
  Train: Loss=0.7737, Bal Acc=0.702, AUROC=0.815, AP=0.697
  Test:  Loss=3.3394, Bal Acc=0.578, AUROC=0.791, AP=0.413
Epoch 30/200
  Train: Loss=0.8125, Bal Acc=0.687, AUROC=0.808, AP=0.688
  Test:  Loss=1.2177, Bal Acc=0.567, AUROC=0.771, AP=0.412
Epoch 31/200
  Train: Loss=0.8047, Bal Acc=0.688, AUROC=0.830, AP=0.724
  Test:  Loss=1.0675, Bal Acc=0.593, AUROC=0.791, AP=0.479
Epoch 32/200
  Train: Loss=0.7111, Bal Acc=0.697, AUROC=0.836, AP=0.718
  Test:  Loss=1.2930, Bal Acc=0.690, AUROC=0.729, AP=0.450
Epoch 33/200
  Train: Loss=0.8752, Bal Acc=0.692, AUROC=0.829, AP=0.675
  Test:  Loss=1.1671, Bal Acc=0.608, AUROC=0.775, AP=0.404
Epoch 34/200
  Train: Loss=0.8053, Bal Acc=0.657, AUROC=0.803, AP=0.695
  Test:  Loss=3.2469, Bal Acc=0.649, AUROC=0.788, AP=0.428
Epoch 35/200
  Train: Loss=0.7300, Bal Acc=0.718, AUROC=0.837, AP=0.723
  Test:  Loss=3.2512, Bal Acc=0.623, AUROC=0.763, AP=0.410
Epoch 36/200
  Train: Loss=0.7392, Bal Acc=0.689, AUROC=0.848, AP=0.735
  Test:  Loss=3.1409, Bal Acc=0.608, AUROC=0.786, AP=0.439
Epoch 37/200
  Train: Loss=0.7452, Bal Acc=0.726, AUROC=0.851, AP=0.748
  Test:  Loss=5.2424, Bal Acc=0.649, AUROC=0.791, AP=0.428
Epoch 38/200
  Train: Loss=0.6640, Bal Acc=0.721, AUROC=0.870, AP=0.774
  Test:  Loss=5.2538, Bal Acc=0.593, AUROC=0.778, AP=0.408
Epoch 39/200
  Train: Loss=0.6644, Bal Acc=0.724, AUROC=0.868, AP=0.768
  Test:  Loss=3.1525, Bal Acc=0.690, AUROC=0.806, AP=0.446
   New best AUROC: 0.806
Epoch 40/200
  Train: Loss=0.7432, Bal Acc=0.739, AUROC=0.864, AP=0.759
  Test:  Loss=3.1426, Bal Acc=0.593, AUROC=0.765, AP=0.406
Epoch 41/200
  Train: Loss=0.6384, Bal Acc=0.742, AUROC=0.883, AP=0.784
  Test:  Loss=5.4403, Bal Acc=0.564, AUROC=0.771, AP=0.402
Epoch 42/200
  Train: Loss=0.6535, Bal Acc=0.742, AUROC=0.864, AP=0.762
  Test:  Loss=5.3122, Bal Acc=0.730, AUROC=0.791, AP=0.427
Epoch 43/200
  Train: Loss=0.7392, Bal Acc=0.715, AUROC=0.866, AP=0.765
  Test:  Loss=5.5397, Bal Acc=0.660, AUROC=0.745, AP=0.383
Epoch 44/200
  Train: Loss=0.6429, Bal Acc=0.730, AUROC=0.872, AP=0.769
  Test:  Loss=5.2849, Bal Acc=0.605, AUROC=0.765, AP=0.408
Epoch 45/200
  Train: Loss=0.5979, Bal Acc=0.751, AUROC=0.878, AP=0.789
  Test:  Loss=5.6233, Bal Acc=0.645, AUROC=0.765, AP=0.391
Epoch 46/200
  Train: Loss=0.7652, Bal Acc=0.734, AUROC=0.883, AP=0.778
  Test:  Loss=3.2350, Bal Acc=0.619, AUROC=0.776, AP=0.417
Epoch 47/200
  Train: Loss=0.6809, Bal Acc=0.734, AUROC=0.871, AP=0.771
  Test:  Loss=5.4134, Bal Acc=0.701, AUROC=0.771, AP=0.413
Epoch 48/200
  Train: Loss=0.6384, Bal Acc=0.742, AUROC=0.891, AP=0.788
  Test:  Loss=5.3515, Bal Acc=0.593, AUROC=0.804, AP=0.432
Epoch 49/200
  Train: Loss=0.7089, Bal Acc=0.727, AUROC=0.876, AP=0.773
  Test:  Loss=5.5582, Bal Acc=0.701, AUROC=0.775, AP=0.398
Epoch 50/200
  Train: Loss=0.8383, Bal Acc=0.755, AUROC=0.854, AP=0.755
  Test:  Loss=5.3772, Bal Acc=0.605, AUROC=0.778, AP=0.401
Epoch 51/200
  Train: Loss=0.6366, Bal Acc=0.755, AUROC=0.906, AP=0.810
  Test:  Loss=5.5332, Bal Acc=0.660, AUROC=0.781, AP=0.402
Epoch 52/200
  Train: Loss=0.6043, Bal Acc=0.750, AUROC=0.892, AP=0.799
  Test:  Loss=5.3829, Bal Acc=0.605, AUROC=0.778, AP=0.399
Epoch 53/200
  Train: Loss=0.5968, Bal Acc=0.750, AUROC=0.899, AP=0.814
  Test:  Loss=5.5184, Bal Acc=0.660, AUROC=0.771, AP=0.392
Epoch 54/200
  Train: Loss=0.6029, Bal Acc=0.763, AUROC=0.904, AP=0.822
  Test:  Loss=5.4671, Bal Acc=0.716, AUROC=0.778, AP=0.406
Epoch 55/200
  Train: Loss=0.5948, Bal Acc=0.766, AUROC=0.909, AP=0.822
  Test:  Loss=5.5946, Bal Acc=0.660, AUROC=0.775, AP=0.395
Epoch 56/200
  Train: Loss=0.6059, Bal Acc=0.731, AUROC=0.903, AP=0.815
  Test:  Loss=5.5710, Bal Acc=0.716, AUROC=0.771, AP=0.392
Epoch 57/200
  Train: Loss=0.6149, Bal Acc=0.763, AUROC=0.907, AP=0.821
  Test:  Loss=5.4246, Bal Acc=0.605, AUROC=0.778, AP=0.399
Epoch 58/200
  Train: Loss=0.5576, Bal Acc=0.779, AUROC=0.914, AP=0.829
  Test:  Loss=5.5296, Bal Acc=0.660, AUROC=0.784, AP=0.404
Epoch 59/200
  Train: Loss=0.5857, Bal Acc=0.783, AUROC=0.908, AP=0.822
  Test:  Loss=5.3209, Bal Acc=0.619, AUROC=0.784, AP=0.409
Epoch 60/200
  Train: Loss=0.5928, Bal Acc=0.747, AUROC=0.911, AP=0.830
  Test:  Loss=5.5880, Bal Acc=0.660, AUROC=0.784, AP=0.404
Epoch 61/200
  Train: Loss=0.5747, Bal Acc=0.775, AUROC=0.908, AP=0.830
  Test:  Loss=5.5740, Bal Acc=0.619, AUROC=0.778, AP=0.399
Epoch 62/200
  Train: Loss=0.5652, Bal Acc=0.783, AUROC=0.920, AP=0.843
  Test:  Loss=5.6071, Bal Acc=0.605, AUROC=0.778, AP=0.399
Epoch 63/200
  Train: Loss=0.5559, Bal Acc=0.778, AUROC=0.921, AP=0.849
  Test:  Loss=5.6244, Bal Acc=0.605, AUROC=0.778, AP=0.399
Epoch 64/200
  Train: Loss=0.5501, Bal Acc=0.786, AUROC=0.924, AP=0.850
  Test:  Loss=5.5555, Bal Acc=0.619, AUROC=0.778, AP=0.399
Epoch 65/200
  Train: Loss=0.5446, Bal Acc=0.775, AUROC=0.919, AP=0.850
  Test:  Loss=5.5983, Bal Acc=0.634, AUROC=0.784, AP=0.406
Epoch 66/200
  Train: Loss=0.5449, Bal Acc=0.790, AUROC=0.923, AP=0.856
  Test:  Loss=5.6669, Bal Acc=0.619, AUROC=0.778, AP=0.399
Epoch 67/200
  Train: Loss=0.5466, Bal Acc=0.777, AUROC=0.926, AP=0.860
  Test:  Loss=5.7469, Bal Acc=0.605, AUROC=0.778, AP=0.399
Epoch 68/200
  Train: Loss=0.5669, Bal Acc=0.798, AUROC=0.917, AP=0.847
  Test:  Loss=7.6848, Bal Acc=0.619, AUROC=0.779, AP=0.392
Epoch 69/200
  Train: Loss=0.5524, Bal Acc=0.791, AUROC=0.926, AP=0.857
  Test:  Loss=7.6990, Bal Acc=0.605, AUROC=0.779, AP=0.392
Epoch 70/200
  Train: Loss=0.5214, Bal Acc=0.791, AUROC=0.930, AP=0.862
  Test:  Loss=7.6998, Bal Acc=0.605, AUROC=0.776, AP=0.390
Epoch 71/200
  Train: Loss=0.5573, Bal Acc=0.823, AUROC=0.922, AP=0.857
  Test:  Loss=5.7095, Bal Acc=0.619, AUROC=0.788, AP=0.408
Epoch 72/200
  Train: Loss=0.5438, Bal Acc=0.787, AUROC=0.927, AP=0.854
  Test:  Loss=5.7148, Bal Acc=0.619, AUROC=0.788, AP=0.408
Epoch 73/200
  Train: Loss=0.5137, Bal Acc=0.802, AUROC=0.931, AP=0.864
  Test:  Loss=5.7395, Bal Acc=0.619, AUROC=0.788, AP=0.408
Epoch 74/200
  Train: Loss=0.5167, Bal Acc=0.794, AUROC=0.933, AP=0.867
  Test:  Loss=7.7042, Bal Acc=0.619, AUROC=0.786, AP=0.399
Epoch 75/200
  Train: Loss=0.5080, Bal Acc=0.806, AUROC=0.932, AP=0.870
  Test:  Loss=7.7345, Bal Acc=0.619, AUROC=0.786, AP=0.399
Epoch 76/200
  Train: Loss=0.5212, Bal Acc=0.818, AUROC=0.930, AP=0.865
  Test:  Loss=7.7271, Bal Acc=0.619, AUROC=0.786, AP=0.399
Epoch 77/200
  Train: Loss=0.5040, Bal Acc=0.814, AUROC=0.932, AP=0.869
  Test:  Loss=7.7542, Bal Acc=0.619, AUROC=0.786, AP=0.399
Epoch 78/200
  Train: Loss=0.5261, Bal Acc=0.823, AUROC=0.934, AP=0.866
  Test:  Loss=7.7493, Bal Acc=0.619, AUROC=0.786, AP=0.398
Epoch 79/200
  Train: Loss=0.5463, Bal Acc=0.806, AUROC=0.934, AP=0.876
  Test:  Loss=7.7773, Bal Acc=0.619, AUROC=0.783, AP=0.395
Epoch 80/200
  Train: Loss=0.5346, Bal Acc=0.807, AUROC=0.932, AP=0.870
  Test:  Loss=7.8025, Bal Acc=0.619, AUROC=0.779, AP=0.394
Epoch 81/200
  Train: Loss=0.5090, Bal Acc=0.807, AUROC=0.936, AP=0.876
  Test:  Loss=7.8039, Bal Acc=0.619, AUROC=0.779, AP=0.394
Epoch 82/200
  Train: Loss=0.5200, Bal Acc=0.818, AUROC=0.939, AP=0.878
  Test:  Loss=7.7806, Bal Acc=0.619, AUROC=0.783, AP=0.396
Epoch 83/200
  Train: Loss=0.5179, Bal Acc=0.818, AUROC=0.938, AP=0.876
  Test:  Loss=7.7883, Bal Acc=0.619, AUROC=0.783, AP=0.396
Epoch 84/200
  Train: Loss=0.5092, Bal Acc=0.810, AUROC=0.937, AP=0.877
  Test:  Loss=7.8070, Bal Acc=0.619, AUROC=0.779, AP=0.394
Epoch 85/200
  Train: Loss=0.5336, Bal Acc=0.823, AUROC=0.932, AP=0.873
  Test:  Loss=7.8198, Bal Acc=0.619, AUROC=0.779, AP=0.394
Epoch 86/200
  Train: Loss=0.5219, Bal Acc=0.810, AUROC=0.936, AP=0.876
  Test:  Loss=7.8257, Bal Acc=0.619, AUROC=0.776, AP=0.391
Epoch 87/200
  Train: Loss=0.5233, Bal Acc=0.814, AUROC=0.935, AP=0.874
  Test:  Loss=7.8337, Bal Acc=0.619, AUROC=0.776, AP=0.391
Epoch 88/200
  Train: Loss=0.5338, Bal Acc=0.826, AUROC=0.932, AP=0.875
  Test:  Loss=7.8353, Bal Acc=0.619, AUROC=0.779, AP=0.394
Epoch 89/200
  Train: Loss=0.5281, Bal Acc=0.822, AUROC=0.934, AP=0.872
  Test:  Loss=7.8402, Bal Acc=0.619, AUROC=0.779, AP=0.394

Early stopping at epoch 89 (no improvement for 50 epochs)

================================================================================
FINAL EVALUATION (best model)
================================================================================

Test Metrics:
  Balanced Accuracy: 0.690
  AUROC: 0.806
  Avg Precision: 0.446

Confusion Matrix:
  TN=28, FP=6
  FN=4, TP=5

Classification Report:
              precision    recall  f1-score   support

single_state       0.88      0.82      0.85        34
 multi_state       0.45      0.56      0.50         9

    accuracy                           0.77        43
   macro avg       0.66      0.69      0.67        43
weighted avg       0.79      0.77      0.78        43


 Results saved to ../../results/tcn_oracle_10pct_receptor/tcn_20260312_153323
Using device: cpu
Output directory: ../../results/tcn_oracle_10pct_receptor/tcn_20260312_153613

Loading datasets...
Loaded 203 samples
  Multi: 62.0 (30.5%)
  Single: 141 (69.5%)
  Using frac=1.0 of each trajectory
Loaded 43 samples
  Multi: 9.0 (20.9%)
  Single: 34 (79.1%)
  Using frac=1.0 of each trajectory
  Auto-detected 7 features from data

Initializing TCN with 7 input features...
TCN Summary:
  Receptive field:   61 timesteps
  Pooling:           mean
  Parameters:        14,076
  Architecture:      [25, 25, 25, 25]

Using pos_weight=1.0 for imbalanced data

Starting training...
Epoch 1/200
  Train: Loss=1.6761, Bal Acc=0.500, AUROC=0.356, AP=0.246
  Test:  Loss=0.8413, Bal Acc=0.500, AUROC=0.605, AP=0.266
   New best AUROC: 0.605
Epoch 2/200
  Train: Loss=1.1112, Bal Acc=0.563, AUROC=0.637, AP=0.410
  Test:  Loss=0.7924, Bal Acc=0.500, AUROC=0.729, AP=0.372
   New best AUROC: 0.729
Epoch 3/200
  Train: Loss=1.1370, Bal Acc=0.513, AUROC=0.628, AP=0.429
  Test:  Loss=0.7171, Bal Acc=0.471, AUROC=0.601, AP=0.286
Epoch 4/200
  Train: Loss=1.0919, Bal Acc=0.486, AUROC=0.607, AP=0.391
  Test:  Loss=0.6222, Bal Acc=0.500, AUROC=0.758, AP=0.397
   New best AUROC: 0.758
Epoch 5/200
  Train: Loss=1.0448, Bal Acc=0.518, AUROC=0.664, AP=0.439
  Test:  Loss=0.5112, Bal Acc=0.441, AUROC=0.725, AP=0.327
Epoch 6/200
  Train: Loss=1.0715, Bal Acc=0.539, AUROC=0.690, AP=0.475
  Test:  Loss=0.5452, Bal Acc=0.485, AUROC=0.735, AP=0.354
Epoch 7/200
  Train: Loss=0.9346, Bal Acc=0.551, AUROC=0.749, AP=0.569
  Test:  Loss=0.5839, Bal Acc=0.482, AUROC=0.716, AP=0.335
Epoch 8/200
  Train: Loss=0.8608, Bal Acc=0.597, AUROC=0.757, AP=0.566
  Test:  Loss=0.5675, Bal Acc=0.426, AUROC=0.748, AP=0.380
Epoch 9/200
  Train: Loss=0.8244, Bal Acc=0.609, AUROC=0.773, AP=0.636
  Test:  Loss=0.7795, Bal Acc=0.634, AUROC=0.775, AP=0.377
   New best AUROC: 0.775
Epoch 10/200
  Train: Loss=0.9675, Bal Acc=0.675, AUROC=0.757, AP=0.587
  Test:  Loss=0.5437, Bal Acc=0.649, AUROC=0.797, AP=0.408
   New best AUROC: 0.797
Epoch 11/200
  Train: Loss=0.9654, Bal Acc=0.668, AUROC=0.771, AP=0.595
  Test:  Loss=0.8432, Bal Acc=0.538, AUROC=0.801, AP=0.406
   New best AUROC: 0.801
Epoch 12/200
  Train: Loss=0.8385, Bal Acc=0.636, AUROC=0.776, AP=0.645
  Test:  Loss=0.9329, Bal Acc=0.619, AUROC=0.817, AP=0.436
   New best AUROC: 0.817
Epoch 13/200
  Train: Loss=0.8771, Bal Acc=0.658, AUROC=0.785, AP=0.651
  Test:  Loss=1.0430, Bal Acc=0.812, AUROC=0.797, AP=0.449
Epoch 14/200
  Train: Loss=0.8300, Bal Acc=0.707, AUROC=0.788, AP=0.663
  Test:  Loss=0.7639, Bal Acc=0.511, AUROC=0.810, AP=0.459
Epoch 15/200
  Train: Loss=0.8118, Bal Acc=0.669, AUROC=0.791, AP=0.675
  Test:  Loss=1.1358, Bal Acc=0.760, AUROC=0.810, AP=0.420
Epoch 16/200
  Train: Loss=0.7755, Bal Acc=0.669, AUROC=0.806, AP=0.690
  Test:  Loss=3.0601, Bal Acc=0.704, AUROC=0.850, AP=0.518
   New best AUROC: 0.850
Epoch 17/200
  Train: Loss=0.8372, Bal Acc=0.671, AUROC=0.810, AP=0.654
  Test:  Loss=1.1616, Bal Acc=0.497, AUROC=0.676, AP=0.326
Epoch 18/200
  Train: Loss=0.7916, Bal Acc=0.682, AUROC=0.820, AP=0.698
  Test:  Loss=0.5267, Bal Acc=0.637, AUROC=0.837, AP=0.604
Epoch 19/200
  Train: Loss=0.8036, Bal Acc=0.695, AUROC=0.800, AP=0.682
  Test:  Loss=3.1037, Bal Acc=0.663, AUROC=0.846, AP=0.480
Epoch 20/200
  Train: Loss=0.7386, Bal Acc=0.681, AUROC=0.833, AP=0.722
  Test:  Loss=5.1401, Bal Acc=0.690, AUROC=0.791, AP=0.406
Epoch 21/200
  Train: Loss=0.8497, Bal Acc=0.687, AUROC=0.830, AP=0.682
  Test:  Loss=0.8603, Bal Acc=0.663, AUROC=0.843, AP=0.477
Epoch 22/200
  Train: Loss=0.7518, Bal Acc=0.678, AUROC=0.827, AP=0.691
  Test:  Loss=3.1976, Bal Acc=0.771, AUROC=0.814, AP=0.451
Epoch 23/200
  Train: Loss=0.7111, Bal Acc=0.718, AUROC=0.857, AP=0.749
  Test:  Loss=1.3734, Bal Acc=0.716, AUROC=0.742, AP=0.413
Epoch 24/200
  Train: Loss=0.7100, Bal Acc=0.759, AUROC=0.851, AP=0.759
  Test:  Loss=5.1275, Bal Acc=0.719, AUROC=0.843, AP=0.485
Epoch 25/200
  Train: Loss=0.7488, Bal Acc=0.698, AUROC=0.833, AP=0.720
  Test:  Loss=3.0253, Bal Acc=0.678, AUROC=0.810, AP=0.476
Epoch 26/200
  Train: Loss=0.7298, Bal Acc=0.712, AUROC=0.841, AP=0.737
  Test:  Loss=3.1395, Bal Acc=0.690, AUROC=0.804, AP=0.461
Epoch 27/200
  Train: Loss=0.7332, Bal Acc=0.724, AUROC=0.852, AP=0.735
  Test:  Loss=3.2083, Bal Acc=0.608, AUROC=0.783, AP=0.447
Epoch 28/200
  Train: Loss=0.6598, Bal Acc=0.746, AUROC=0.874, AP=0.778
  Test:  Loss=5.3697, Bal Acc=0.783, AUROC=0.810, AP=0.453
Epoch 29/200
  Train: Loss=0.6911, Bal Acc=0.756, AUROC=0.872, AP=0.778
  Test:  Loss=3.0744, Bal Acc=0.608, AUROC=0.820, AP=0.468
Epoch 30/200
  Train: Loss=0.6337, Bal Acc=0.749, AUROC=0.880, AP=0.792
  Test:  Loss=5.2245, Bal Acc=0.730, AUROC=0.784, AP=0.431
Epoch 31/200
  Train: Loss=0.6516, Bal Acc=0.767, AUROC=0.883, AP=0.797
  Test:  Loss=5.1436, Bal Acc=0.608, AUROC=0.791, AP=0.430
Epoch 32/200
  Train: Loss=0.6237, Bal Acc=0.763, AUROC=0.885, AP=0.799
  Test:  Loss=5.2343, Bal Acc=0.690, AUROC=0.807, AP=0.453
Epoch 33/200
  Train: Loss=0.6377, Bal Acc=0.759, AUROC=0.884, AP=0.793
  Test:  Loss=5.1246, Bal Acc=0.704, AUROC=0.797, AP=0.451
Epoch 34/200
  Train: Loss=0.6123, Bal Acc=0.771, AUROC=0.886, AP=0.796
  Test:  Loss=5.2637, Bal Acc=0.675, AUROC=0.771, AP=0.438
Epoch 35/200
  Train: Loss=0.6732, Bal Acc=0.763, AUROC=0.892, AP=0.801
  Test:  Loss=5.3699, Bal Acc=0.660, AUROC=0.791, AP=0.445
Epoch 36/200
  Train: Loss=0.6360, Bal Acc=0.751, AUROC=0.889, AP=0.803
  Test:  Loss=5.2219, Bal Acc=0.675, AUROC=0.771, AP=0.446
Epoch 37/200
  Train: Loss=0.7043, Bal Acc=0.778, AUROC=0.889, AP=0.792
  Test:  Loss=5.6842, Bal Acc=0.672, AUROC=0.771, AP=0.415
Epoch 38/200
  Train: Loss=0.6198, Bal Acc=0.776, AUROC=0.901, AP=0.822
  Test:  Loss=5.3099, Bal Acc=0.660, AUROC=0.771, AP=0.439
Epoch 39/200
  Train: Loss=0.5223, Bal Acc=0.791, AUROC=0.921, AP=0.850
  Test:  Loss=5.4455, Bal Acc=0.660, AUROC=0.771, AP=0.447
Epoch 40/200
  Train: Loss=0.5617, Bal Acc=0.803, AUROC=0.915, AP=0.845
  Test:  Loss=5.2645, Bal Acc=0.690, AUROC=0.745, AP=0.428
Epoch 41/200
  Train: Loss=0.5938, Bal Acc=0.803, AUROC=0.920, AP=0.847
  Test:  Loss=5.3964, Bal Acc=0.645, AUROC=0.755, AP=0.432
Epoch 42/200
  Train: Loss=0.5769, Bal Acc=0.811, AUROC=0.925, AP=0.854
  Test:  Loss=5.4439, Bal Acc=0.590, AUROC=0.729, AP=0.409
Epoch 43/200
  Train: Loss=0.5470, Bal Acc=0.810, AUROC=0.926, AP=0.864
  Test:  Loss=5.5888, Bal Acc=0.605, AUROC=0.703, AP=0.395
Epoch 44/200
  Train: Loss=0.5852, Bal Acc=0.807, AUROC=0.925, AP=0.862
  Test:  Loss=5.4660, Bal Acc=0.690, AUROC=0.735, AP=0.419
Epoch 45/200
  Train: Loss=0.5796, Bal Acc=0.803, AUROC=0.933, AP=0.879

In [34]:
# --- Oracle/sanity check features at 20,30,40,60,70,80,100% ---

for pct in [20,30,40,60,70,80,100]:
    for seed in [0, 1, 2]:
        !python train_tcn.py \
            --train_csv ../../data/metadata/splits/protein_level_train.csv \
            --test_csv ../../data/metadata/splits/protein_level_test.csv \
            --npy_dir ../../data/processed_v4/features_{pct}pct/sanity_check_features \
            --batch_size 1 --num_workers 0 \
            --patience 50 --epochs 200 \
            --output_dir ../../results/tcn_oracle_{pct}pct_receptor

Using device: cpu
Output directory: ../../results/tcn_oracle_20pct_receptor/tcn_20260313_004158

Loading datasets...
Loaded 203 samples
  Multi: 62.0 (30.5%)
  Single: 141 (69.5%)
  Using frac=1.0 of each trajectory
Loaded 43 samples
  Multi: 9.0 (20.9%)
  Single: 34 (79.1%)
  Using frac=1.0 of each trajectory
  Auto-detected 7 features from data

Initializing TCN with 7 input features...
TCN Summary:
  Receptive field:   61 timesteps
  Pooling:           mean
  Parameters:        14,076
  Architecture:      [25, 25, 25, 25]

Using pos_weight=1.0 for imbalanced data

Starting training...
Epoch 1/200
  Train: Loss=1.9129, Bal Acc=0.485, AUROC=0.492, AP=0.295
  Test:  Loss=1.0259, Bal Acc=0.500, AUROC=0.386, AP=0.187
   New best AUROC: 0.386
Epoch 2/200
  Train: Loss=1.3290, Bal Acc=0.496, AUROC=0.533, AP=0.348
  Test:  Loss=1.1082, Bal Acc=0.500, AUROC=0.399, AP=0.194
   New best AUROC: 0.399
Epoch 3/200
  Train: Loss=1.2457, Bal Acc=0.500, AUROC=0.526, AP=0.349
  Test:  Loss=0.5889, Bal Acc=0.500, AUROC=0.575, AP=0.272
   New best AUROC: 0.575
Epoch 4/200
  Train: Loss=1.1566, Bal Acc=0.500, AUROC=0.518, AP=0.333
  Test:  Loss=0.7510, Bal Acc=0.500, AUROC=0.585, AP=0.271
   New best AUROC: 0.585
Epoch 5/200
  Train: Loss=1.1126, Bal Acc=0.500, AUROC=0.601, AP=0.382
  Test:  Loss=0.6143, Bal Acc=0.500, AUROC=0.631, AP=0.328
   New best AUROC: 0.631
Epoch 6/200
  Train: Loss=1.0624, Bal Acc=0.500, AUROC=0.612, AP=0.397
  Test:  Loss=0.8080, Bal Acc=0.500, AUROC=0.575, AP=0.248
Epoch 7/200
  Train: Loss=1.0875, Bal Acc=0.500, AUROC=0.622, AP=0.413
  Test:  Loss=0.6131, Bal Acc=0.500, AUROC=0.605, AP=0.259
Epoch 8/200
  Train: Loss=1.0231, Bal Acc=0.501, AUROC=0.635, AP=0.415
  Test:  Loss=0.6400, Bal Acc=0.500, AUROC=0.552, AP=0.232
Epoch 9/200
  Train: Loss=0.9876, Bal Acc=0.500, AUROC=0.672, AP=0.460
  Test:  Loss=0.6971, Bal Acc=0.500, AUROC=0.670, AP=0.302
   New best AUROC: 0.670
Epoch 10/200
  Train: Loss=0.9505, Bal Acc=0.500, AUROC=0.669, AP=0.478
  Test:  Loss=0.8420, Bal Acc=0.500, AUROC=0.716, AP=0.339
   New best AUROC: 0.716
Epoch 11/200
  Train: Loss=1.0755, Bal Acc=0.523, AUROC=0.674, AP=0.460
  Test:  Loss=0.6389, Bal Acc=0.500, AUROC=0.624, AP=0.270
Epoch 12/200
  Train: Loss=0.9933, Bal Acc=0.505, AUROC=0.696, AP=0.510
  Test:  Loss=0.5948, Bal Acc=0.471, AUROC=0.725, AP=0.327
   New best AUROC: 0.725
Epoch 13/200
  Train: Loss=0.9073, Bal Acc=0.526, AUROC=0.722, AP=0.521
  Test:  Loss=0.6722, Bal Acc=0.485, AUROC=0.722, AP=0.326
Epoch 14/200
  Train: Loss=0.9236, Bal Acc=0.579, AUROC=0.737, AP=0.548
  Test:  Loss=0.9290, Bal Acc=0.500, AUROC=0.719, AP=0.326
Epoch 15/200
  Train: Loss=0.9617, Bal Acc=0.580, AUROC=0.742, AP=0.565
  Test:  Loss=0.9474, Bal Acc=0.538, AUROC=0.735, AP=0.340
   New best AUROC: 0.735
Epoch 16/200
  Train: Loss=0.8805, Bal Acc=0.608, AUROC=0.768, AP=0.610
  Test:  Loss=0.6886, Bal Acc=0.485, AUROC=0.676, AP=0.327
Epoch 17/200
  Train: Loss=0.9037, Bal Acc=0.602, AUROC=0.777, AP=0.635
  Test:  Loss=1.1461, Bal Acc=0.467, AUROC=0.781, AP=0.394
   New best AUROC: 0.781
Epoch 18/200
  Train: Loss=0.7901, Bal Acc=0.641, AUROC=0.791, AP=0.668
  Test:  Loss=0.8919, Bal Acc=0.456, AUROC=0.712, AP=0.338
Epoch 19/200
  Train: Loss=0.9931, Bal Acc=0.633, AUROC=0.805, AP=0.662
  Test:  Loss=0.9021, Bal Acc=0.471, AUROC=0.614, AP=0.295
Epoch 20/200
  Train: Loss=1.2815, Bal Acc=0.673, AUROC=0.809, AP=0.640
  Test:  Loss=5.3855, Bal Acc=0.549, AUROC=0.755, AP=0.369
Epoch 21/200
  Train: Loss=0.8260, Bal Acc=0.676, AUROC=0.810, AP=0.688
  Test:  Loss=1.4395, Bal Acc=0.497, AUROC=0.673, AP=0.337
Epoch 22/200
  Train: Loss=1.2779, Bal Acc=0.655, AUROC=0.814, AP=0.681
  Test:  Loss=3.6864, Bal Acc=0.523, AUROC=0.781, AP=0.376
Epoch 23/200
  Train: Loss=1.3307, Bal Acc=0.665, AUROC=0.827, AP=0.678
  Test:  Loss=3.5001, Bal Acc=0.552, AUROC=0.765, AP=0.380
Epoch 24/200
  Train: Loss=1.2262, Bal Acc=0.699, AUROC=0.841, AP=0.734
  Test:  Loss=7.8994, Bal Acc=0.605, AUROC=0.740, AP=0.357
Epoch 25/200
  Train: Loss=0.8292, Bal Acc=0.674, AUROC=0.821, AP=0.707
  Test:  Loss=1.2073, Bal Acc=0.497, AUROC=0.536, AP=0.247
Epoch 26/200
  Train: Loss=1.9693, Bal Acc=0.671, AUROC=0.801, AP=0.620
  Test:  Loss=3.4027, Bal Acc=0.426, AUROC=0.559, AP=0.253
Epoch 27/200
  Train: Loss=0.8587, Bal Acc=0.689, AUROC=0.863, AP=0.750
  Test:  Loss=3.5551, Bal Acc=0.482, AUROC=0.549, AP=0.257
Epoch 28/200
  Train: Loss=0.6622, Bal Acc=0.713, AUROC=0.865, AP=0.784
  Test:  Loss=3.5556, Bal Acc=0.538, AUROC=0.559, AP=0.297
Epoch 29/200
  Train: Loss=1.1149, Bal Acc=0.737, AUROC=0.886, AP=0.789
  Test:  Loss=5.9021, Bal Acc=0.467, AUROC=0.565, AP=0.269
Epoch 30/200
  Train: Loss=1.0614, Bal Acc=0.744, AUROC=0.897, AP=0.812
  Test:  Loss=8.4666, Bal Acc=0.523, AUROC=0.569, AP=0.258
Epoch 31/200
  Train: Loss=0.7153, Bal Acc=0.738, AUROC=0.888, AP=0.805
  Test:  Loss=5.8920, Bal Acc=0.523, AUROC=0.585, AP=0.292
Epoch 32/200
  Train: Loss=0.6115, Bal Acc=0.744, AUROC=0.901, AP=0.833
  Test:  Loss=10.3699, Bal Acc=0.578, AUROC=0.598, AP=0.281
Epoch 33/200
  Train: Loss=1.0890, Bal Acc=0.752, AUROC=0.893, AP=0.801
  Test:  Loss=10.5886, Bal Acc=0.578, AUROC=0.539, AP=0.254
Epoch 34/200
  Train: Loss=1.1846, Bal Acc=0.775, AUROC=0.906, AP=0.809
  Test:  Loss=10.3429, Bal Acc=0.523, AUROC=0.526, AP=0.254
Epoch 35/200
  Train: Loss=1.1033, Bal Acc=0.741, AUROC=0.891, AP=0.803
  Test:  Loss=12.5102, Bal Acc=0.578, AUROC=0.592, AP=0.272
Epoch 36/200
  Train: Loss=0.6131, Bal Acc=0.766, AUROC=0.897, AP=0.835
  Test:  Loss=8.5610, Bal Acc=0.578, AUROC=0.500, AP=0.240
Epoch 37/200
  Train: Loss=1.1694, Bal Acc=0.775, AUROC=0.905, AP=0.829
  Test:  Loss=7.9857, Bal Acc=0.538, AUROC=0.565, AP=0.279
Epoch 38/200
  Train: Loss=1.0919, Bal Acc=0.778, AUROC=0.903, AP=0.809
  Test:  Loss=8.2154, Bal Acc=0.482, AUROC=0.556, AP=0.273
Epoch 39/200
  Train: Loss=0.6168, Bal Acc=0.765, AUROC=0.899, AP=0.839
  Test:  Loss=8.3099, Bal Acc=0.593, AUROC=0.526, AP=0.259
Epoch 40/200
  Train: Loss=0.5341, Bal Acc=0.776, AUROC=0.936, AP=0.886
  Test:  Loss=8.3872, Bal Acc=0.578, AUROC=0.539, AP=0.268
Epoch 41/200
  Train: Loss=0.5236, Bal Acc=0.813, AUROC=0.934, AP=0.879
  Test:  Loss=12.7931, Bal Acc=0.578, AUROC=0.516, AP=0.249
Epoch 42/200
  Train: Loss=0.5127, Bal Acc=0.821, AUROC=0.931, AP=0.883
  Test:  Loss=8.5639, Bal Acc=0.578, AUROC=0.471, AP=0.232
Epoch 43/200
  Train: Loss=0.5370, Bal Acc=0.808, AUROC=0.938, AP=0.885
  Test:  Loss=8.5539, Bal Acc=0.593, AUROC=0.500, AP=0.242
Epoch 44/200
  Train: Loss=0.5022, Bal Acc=0.804, AUROC=0.941, AP=0.895
  Test:  Loss=10.4990, Bal Acc=0.593, AUROC=0.539, AP=0.272
Epoch 45/200
  Train: Loss=0.5020, Bal Acc=0.792, AUROC=0.930, AP=0.880
  Test:  Loss=10.6454, Bal Acc=0.593, AUROC=0.542, AP=0.276
Epoch 46/200
  Train: Loss=0.4600, Bal Acc=0.832, AUROC=0.944, AP=0.902
  Test:  Loss=8.6292, Bal Acc=0.482, AUROC=0.448, AP=0.221
Epoch 47/200
  Train: Loss=0.4919, Bal Acc=0.807, AUROC=0.943, AP=0.905
  Test:  Loss=12.4344, Bal Acc=0.690, AUROC=0.549, AP=0.290
Epoch 48/200
  Train: Loss=0.4998, Bal Acc=0.821, AUROC=0.934, AP=0.890
  Test:  Loss=8.8238, Bal Acc=0.538, AUROC=0.454, AP=0.228
Epoch 49/200
  Train: Loss=0.5031, Bal Acc=0.821, AUROC=0.939, AP=0.896
  Test:  Loss=10.8376, Bal Acc=0.578, AUROC=0.523, AP=0.261
Epoch 50/200
  Train: Loss=0.5691, Bal Acc=0.813, AUROC=0.935, AP=0.895
  Test:  Loss=8.7484, Bal Acc=0.578, AUROC=0.435, AP=0.219
Epoch 51/200
  Train: Loss=0.3691, Bal Acc=0.843, AUROC=0.961, AP=0.932
  Test:  Loss=11.1021, Bal Acc=0.578, AUROC=0.487, AP=0.243
Epoch 52/200
  Train: Loss=0.4053, Bal Acc=0.840, AUROC=0.956, AP=0.922
  Test:  Loss=9.0470, Bal Acc=0.578, AUROC=0.441, AP=0.225
Epoch 53/200
  Train: Loss=0.4106, Bal Acc=0.843, AUROC=0.966, AP=0.936
  Test:  Loss=9.1263, Bal Acc=0.578, AUROC=0.441, AP=0.227
Epoch 54/200
  Train: Loss=0.4032, Bal Acc=0.847, AUROC=0.962, AP=0.932
  Test:  Loss=9.1333, Bal Acc=0.578, AUROC=0.441, AP=0.225
Epoch 55/200
  Train: Loss=0.3827, Bal Acc=0.840, AUROC=0.963, AP=0.933
  Test:  Loss=9.1524, Bal Acc=0.578, AUROC=0.438, AP=0.223
Epoch 56/200
  Train: Loss=0.3957, Bal Acc=0.832, AUROC=0.965, AP=0.934
  Test:  Loss=11.2981, Bal Acc=0.578, AUROC=0.477, AP=0.240
Epoch 57/200
  Train: Loss=0.3908, Bal Acc=0.851, AUROC=0.966, AP=0.939
  Test:  Loss=9.2895, Bal Acc=0.578, AUROC=0.435, AP=0.224
Epoch 58/200
  Train: Loss=0.3560, Bal Acc=0.832, AUROC=0.972, AP=0.944
  Test:  Loss=9.3996, Bal Acc=0.578, AUROC=0.435, AP=0.219
Epoch 59/200
  Train: Loss=0.4544, Bal Acc=0.828, AUROC=0.961, AP=0.931
  Test:  Loss=9.2040, Bal Acc=0.523, AUROC=0.438, AP=0.229
Epoch 60/200
  Train: Loss=0.4256, Bal Acc=0.851, AUROC=0.964, AP=0.936
  Test:  Loss=9.4513, Bal Acc=0.578, AUROC=0.428, AP=0.222
Epoch 61/200
  Train: Loss=0.3861, Bal Acc=0.851, AUROC=0.965, AP=0.938
  Test:  Loss=11.4748, Bal Acc=0.578, AUROC=0.425, AP=0.223
Epoch 62/200
  Train: Loss=0.3316, Bal Acc=0.851, AUROC=0.972, AP=0.949
  Test:  Loss=9.7015, Bal Acc=0.578, AUROC=0.428, AP=0.224
Epoch 63/200
  Train: Loss=0.3382, Bal Acc=0.848, AUROC=0.968, AP=0.944
  Test:  Loss=9.6465, Bal Acc=0.578, AUROC=0.431, AP=0.221
Epoch 64/200
  Train: Loss=0.3893, Bal Acc=0.847, AUROC=0.971, AP=0.947
  Test:  Loss=9.7664, Bal Acc=0.578, AUROC=0.431, AP=0.225
Epoch 65/200
  Train: Loss=0.3480, Bal Acc=0.859, AUROC=0.976, AP=0.956
  Test:  Loss=9.7526, Bal Acc=0.578, AUROC=0.428, AP=0.224
Epoch 66/200
  Train: Loss=0.3287, Bal Acc=0.843, AUROC=0.978, AP=0.958
  Test:  Loss=9.7978, Bal Acc=0.578, AUROC=0.431, AP=0.221
Epoch 67/200
  Train: Loss=0.3701, Bal Acc=0.863, AUROC=0.971, AP=0.951
  Test:  Loss=9.8315, Bal Acc=0.578, AUROC=0.422, AP=0.215

Early stopping at epoch 67 (no improvement for 50 epochs)

================================================================================
FINAL EVALUATION (best model)
================================================================================

Test Metrics:
  Balanced Accuracy: 0.467
  AUROC: 0.781
  Avg Precision: 0.394

Confusion Matrix:
  TN=28, FP=6
  FN=8, TP=1

Classification Report:
              precision    recall  f1-score   support

single_state       0.78      0.82      0.80        34
 multi_state       0.14      0.11      0.12         9

    accuracy                           0.67        43
   macro avg       0.46      0.47      0.46        43
weighted avg       0.64      0.67      0.66        43


 Results saved to ../../results/tcn_oracle_20pct_receptor/tcn_20260313_004158
Using device: cpu
Output directory: ../../results/tcn_oracle_20pct_receptor/tcn_20260313_004431

Loading datasets...
Loaded 203 samples
  Multi: 62.0 (30.5%)
  Single: 141 (69.5%)
  Using frac=1.0 of each trajectory
Loaded 43 samples
  Multi: 9.0 (20.9%)
  Single: 34 (79.1%)
  Using frac=1.0 of each trajectory
  Auto-detected 7 features from data

Initializing TCN with 7 input features...
TCN Summary:
  Receptive field:   61 timesteps
  Pooling:           mean
  Parameters:        14,076
  Architecture:      [25, 25, 25, 25]

Using pos_weight=1.0 for imbalanced data

Starting training...
Epoch 1/200
  Train: Loss=2.2801, Bal Acc=0.493, AUROC=0.383, AP=0.246
  Test:  Loss=0.8472, Bal Acc=0.500, AUROC=0.382, AP=0.183
   New best AUROC: 0.382
Epoch 2/200
  Train: Loss=1.5071, Bal Acc=0.500, AUROC=0.457, AP=0.281
  Test:  Loss=0.6197, Bal Acc=0.500, AUROC=0.572, AP=0.259
   New best AUROC: 0.572
Epoch 3/200
  Train: Loss=1.4297, Bal Acc=0.500, AUROC=0.488, AP=0.324
  Test:  Loss=0.5725, Bal Acc=0.500, AUROC=0.474, AP=0.208
Epoch 4/200
  Train: Loss=1.1842, Bal Acc=0.500, AUROC=0.515, AP=0.328
  Test:  Loss=0.6799, Bal Acc=0.500, AUROC=0.559, AP=0.241
Epoch 5/200
  Train: Loss=1.1772, Bal Acc=0.500, AUROC=0.518, AP=0.322
  Test:  Loss=0.5431, Bal Acc=0.500, AUROC=0.660, AP=0.394
   New best AUROC: 0.660
Epoch 6/200
  Train: Loss=1.1601, Bal Acc=0.500, AUROC=0.542, AP=0.333
  Test:  Loss=0.5719, Bal Acc=0.500, AUROC=0.552, AP=0.303
Epoch 7/200
  Train: Loss=1.0415, Bal Acc=0.500, AUROC=0.613, AP=0.397
  Test:  Loss=0.7131, Bal Acc=0.500, AUROC=0.680, AP=0.373
   New best AUROC: 0.680
Epoch 8/200
  Train: Loss=1.1089, Bal Acc=0.500, AUROC=0.590, AP=0.378
  Test:  Loss=0.6227, Bal Acc=0.500, AUROC=0.627, AP=0.324
Epoch 9/200
  Train: Loss=1.0265, Bal Acc=0.500, AUROC=0.650, AP=0.398
  Test:  Loss=0.5495, Bal Acc=0.500, AUROC=0.680, AP=0.355
Epoch 10/200
  Train: Loss=1.0525, Bal Acc=0.500, AUROC=0.636, AP=0.403
  Test:  Loss=0.6917, Bal Acc=0.500, AUROC=0.624, AP=0.314
Epoch 11/200
  Train: Loss=0.9745, Bal Acc=0.500, AUROC=0.683, AP=0.519
  Test:  Loss=0.6707, Bal Acc=0.500, AUROC=0.650, AP=0.306
Epoch 12/200
  Train: Loss=0.9720, Bal Acc=0.500, AUROC=0.712, AP=0.462
  Test:  Loss=0.6767, Bal Acc=0.500, AUROC=0.722, AP=0.461
   New best AUROC: 0.722
Epoch 13/200
  Train: Loss=0.9775, Bal Acc=0.556, AUROC=0.680, AP=0.489
  Test:  Loss=0.7913, Bal Acc=0.500, AUROC=0.627, AP=0.356
Epoch 14/200
  Train: Loss=0.9093, Bal Acc=0.521, AUROC=0.766, AP=0.573
  Test:  Loss=0.4951, Bal Acc=0.649, AUROC=0.775, AP=0.551
   New best AUROC: 0.775
Epoch 15/200
  Train: Loss=0.9021, Bal Acc=0.617, AUROC=0.740, AP=0.540
  Test:  Loss=0.6586, Bal Acc=0.485, AUROC=0.680, AP=0.296
Epoch 16/200
  Train: Loss=0.8991, Bal Acc=0.589, AUROC=0.760, AP=0.543
  Test:  Loss=0.7593, Bal Acc=0.500, AUROC=0.706, AP=0.333
Epoch 17/200
  Train: Loss=0.9097, Bal Acc=0.575, AUROC=0.766, AP=0.609
  Test:  Loss=0.9594, Bal Acc=0.701, AUROC=0.801, AP=0.500
   New best AUROC: 0.801
Epoch 18/200
  Train: Loss=0.8790, Bal Acc=0.628, AUROC=0.779, AP=0.573
  Test:  Loss=1.1417, Bal Acc=0.727, AUROC=0.781, AP=0.389
Epoch 19/200
  Train: Loss=0.9293, Bal Acc=0.637, AUROC=0.783, AP=0.581
  Test:  Loss=0.5745, Bal Acc=0.690, AUROC=0.810, AP=0.433
   New best AUROC: 0.810
Epoch 20/200
  Train: Loss=0.7811, Bal Acc=0.611, AUROC=0.809, AP=0.636
  Test:  Loss=0.8802, Bal Acc=0.485, AUROC=0.676, AP=0.365
Epoch 21/200
  Train: Loss=0.8409, Bal Acc=0.661, AUROC=0.798, AP=0.663
  Test:  Loss=0.5448, Bal Acc=0.582, AUROC=0.791, AP=0.459
Epoch 22/200
  Train: Loss=0.7089, Bal Acc=0.661, AUROC=0.820, AP=0.684
  Test:  Loss=0.8367, Bal Acc=0.645, AUROC=0.846, AP=0.640
   New best AUROC: 0.846
Epoch 23/200
  Train: Loss=0.8281, Bal Acc=0.662, AUROC=0.829, AP=0.699
  Test:  Loss=0.7655, Bal Acc=0.675, AUROC=0.846, AP=0.659
   New best AUROC: 0.846
Epoch 24/200
  Train: Loss=0.8902, Bal Acc=0.650, AUROC=0.827, AP=0.668
  Test:  Loss=0.7648, Bal Acc=0.660, AUROC=0.791, AP=0.540
Epoch 25/200
  Train: Loss=0.7370, Bal Acc=0.699, AUROC=0.829, AP=0.689
  Test:  Loss=0.8708, Bal Acc=0.675, AUROC=0.742, AP=0.472
Epoch 26/200
  Train: Loss=0.7002, Bal Acc=0.687, AUROC=0.860, AP=0.742
  Test:  Loss=0.6159, Bal Acc=0.538, AUROC=0.712, AP=0.430
Epoch 27/200
  Train: Loss=0.7960, Bal Acc=0.673, AUROC=0.847, AP=0.700
  Test:  Loss=0.6217, Bal Acc=0.690, AUROC=0.765, AP=0.541
Epoch 28/200
  Train: Loss=0.7243, Bal Acc=0.680, AUROC=0.863, AP=0.742
  Test:  Loss=1.0360, Bal Acc=0.675, AUROC=0.761, AP=0.459
Epoch 29/200
  Train: Loss=0.7507, Bal Acc=0.712, AUROC=0.856, AP=0.734
  Test:  Loss=0.8806, Bal Acc=0.675, AUROC=0.768, AP=0.457
Epoch 30/200
  Train: Loss=0.7448, Bal Acc=0.702, AUROC=0.859, AP=0.749
  Test:  Loss=0.8462, Bal Acc=0.564, AUROC=0.725, AP=0.438
Epoch 31/200
  Train: Loss=0.7395, Bal Acc=0.694, AUROC=0.842, AP=0.726
  Test:  Loss=1.2905, Bal Acc=0.675, AUROC=0.748, AP=0.442
Epoch 32/200
  Train: Loss=0.6442, Bal Acc=0.747, AUROC=0.874, AP=0.787
  Test:  Loss=0.8810, Bal Acc=0.467, AUROC=0.712, AP=0.400
Epoch 33/200
  Train: Loss=0.7281, Bal Acc=0.706, AUROC=0.859, AP=0.768
  Test:  Loss=1.3023, Bal Acc=0.634, AUROC=0.732, AP=0.426
Epoch 34/200
  Train: Loss=0.6039, Bal Acc=0.754, AUROC=0.890, AP=0.793
  Test:  Loss=3.4258, Bal Acc=0.549, AUROC=0.747, AP=0.372
Epoch 35/200
  Train: Loss=0.5430, Bal Acc=0.757, AUROC=0.921, AP=0.856
  Test:  Loss=10.3676, Bal Acc=0.686, AUROC=0.755, AP=0.365
Epoch 36/200
  Train: Loss=0.6467, Bal Acc=0.755, AUROC=0.908, AP=0.833
  Test:  Loss=3.5869, Bal Acc=0.660, AUROC=0.740, AP=0.363
Epoch 37/200
  Train: Loss=0.6036, Bal Acc=0.747, AUROC=0.909, AP=0.845
  Test:  Loss=3.9180, Bal Acc=0.701, AUROC=0.727, AP=0.360
Epoch 38/200
  Train: Loss=0.5546, Bal Acc=0.766, AUROC=0.913, AP=0.843
  Test:  Loss=3.5524, Bal Acc=0.549, AUROC=0.766, AP=0.389
Epoch 39/200
  Train: Loss=0.5988, Bal Acc=0.762, AUROC=0.917, AP=0.849
  Test:  Loss=3.8140, Bal Acc=0.716, AUROC=0.770, AP=0.392
Epoch 40/200
  Train: Loss=0.5104, Bal Acc=0.766, AUROC=0.929, AP=0.865
  Test:  Loss=3.6414, Bal Acc=0.690, AUROC=0.753, AP=0.382
Epoch 41/200
  Train: Loss=0.6016, Bal Acc=0.762, AUROC=0.918, AP=0.854
  Test:  Loss=5.9945, Bal Acc=0.730, AUROC=0.729, AP=0.359
Epoch 42/200
  Train: Loss=0.5144, Bal Acc=0.806, AUROC=0.927, AP=0.882
  Test:  Loss=6.0350, Bal Acc=0.771, AUROC=0.732, AP=0.357
Epoch 43/200
  Train: Loss=0.5716, Bal Acc=0.786, AUROC=0.929, AP=0.882
  Test:  Loss=12.4915, Bal Acc=0.727, AUROC=0.743, AP=0.340
Epoch 44/200
  Train: Loss=0.5152, Bal Acc=0.810, AUROC=0.918, AP=0.872
  Test:  Loss=3.9110, Bal Acc=0.549, AUROC=0.708, AP=0.347
Epoch 45/200
  Train: Loss=0.4665, Bal Acc=0.806, AUROC=0.943, AP=0.894
  Test:  Loss=8.1787, Bal Acc=0.716, AUROC=0.721, AP=0.329
Epoch 46/200
  Train: Loss=0.4425, Bal Acc=0.809, AUROC=0.943, AP=0.903
  Test:  Loss=8.1943, Bal Acc=0.716, AUROC=0.737, AP=0.348
Epoch 47/200
  Train: Loss=0.4277, Bal Acc=0.812, AUROC=0.946, AP=0.903
  Test:  Loss=8.1161, Bal Acc=0.716, AUROC=0.740, AP=0.341
Epoch 48/200
  Train: Loss=0.4470, Bal Acc=0.836, AUROC=0.951, AP=0.916
  Test:  Loss=8.5179, Bal Acc=0.716, AUROC=0.724, AP=0.332
Epoch 49/200
  Train: Loss=0.4481, Bal Acc=0.810, AUROC=0.946, AP=0.902
  Test:  Loss=10.1450, Bal Acc=0.716, AUROC=0.739, AP=0.342
Epoch 50/200
  Train: Loss=0.4288, Bal Acc=0.838, AUROC=0.953, AP=0.920
  Test:  Loss=10.4661, Bal Acc=0.686, AUROC=0.745, AP=0.363
Epoch 51/200
  Train: Loss=0.4977, Bal Acc=0.837, AUROC=0.946, AP=0.905
  Test:  Loss=12.5236, Bal Acc=0.686, AUROC=0.740, AP=0.339
Epoch 52/200
  Train: Loss=0.4862, Bal Acc=0.826, AUROC=0.949, AP=0.909
  Test:  Loss=8.3275, Bal Acc=0.757, AUROC=0.721, AP=0.332
Epoch 53/200
  Train: Loss=0.4111, Bal Acc=0.810, AUROC=0.958, AP=0.922
  Test:  Loss=8.1320, Bal Acc=0.605, AUROC=0.717, AP=0.325
Epoch 54/200
  Train: Loss=0.4158, Bal Acc=0.857, AUROC=0.955, AP=0.921
  Test:  Loss=8.2899, Bal Acc=0.645, AUROC=0.701, AP=0.315
Epoch 55/200
  Train: Loss=0.5593, Bal Acc=0.817, AUROC=0.940, AP=0.903
  Test:  Loss=10.5215, Bal Acc=0.701, AUROC=0.722, AP=0.326
Epoch 56/200
  Train: Loss=0.3545, Bal Acc=0.860, AUROC=0.969, AP=0.940
  Test:  Loss=10.5639, Bal Acc=0.701, AUROC=0.712, AP=0.319
Epoch 57/200
  Train: Loss=0.3234, Bal Acc=0.856, AUROC=0.974, AP=0.948
  Test:  Loss=12.7565, Bal Acc=0.686, AUROC=0.724, AP=0.321
Epoch 58/200
  Train: Loss=0.3270, Bal Acc=0.869, AUROC=0.968, AP=0.941
  Test:  Loss=10.5571, Bal Acc=0.701, AUROC=0.716, AP=0.318
Epoch 59/200
  Train: Loss=0.3099, Bal Acc=0.873, AUROC=0.973, AP=0.949
  Test:  Loss=8.3999, Bal Acc=0.645, AUROC=0.708, AP=0.317
Epoch 60/200
  Train: Loss=0.3125, Bal Acc=0.872, AUROC=0.974, AP=0.952
  Test:  Loss=10.5801, Bal Acc=0.701, AUROC=0.719, AP=0.317
Epoch 61/200
  Train: Loss=0.2809, Bal Acc=0.881, AUROC=0.977, AP=0.956
  Test:  Loss=8.2802, Bal Acc=0.605, AUROC=0.721, AP=0.324
Epoch 62/200
  Train: Loss=0.3206, Bal Acc=0.881, AUROC=0.973, AP=0.947
  Test:  Loss=8.8641, Bal Acc=0.686, AUROC=0.708, AP=0.314
Epoch 63/200
  Train: Loss=0.2827, Bal Acc=0.888, AUROC=0.978, AP=0.959
  Test:  Loss=10.7306, Bal Acc=0.686, AUROC=0.709, AP=0.311
Epoch 64/200
  Train: Loss=0.3134, Bal Acc=0.889, AUROC=0.973, AP=0.951
  Test:  Loss=10.9608, Bal Acc=0.686, AUROC=0.703, AP=0.308
Epoch 65/200
  Train: Loss=0.2784, Bal Acc=0.888, AUROC=0.978, AP=0.958
  Test:  Loss=8.9599, Bal Acc=0.686, AUROC=0.704, AP=0.311
Epoch 66/200
  Train: Loss=0.2805, Bal Acc=0.896, AUROC=0.976, AP=0.957
  Test:  Loss=8.9829, Bal Acc=0.686, AUROC=0.704, AP=0.312
Epoch 67/200
  Train: Loss=0.2237, Bal Acc=0.904, AUROC=0.984, AP=0.968

## Step 3: Collect Results
Aggregates AUROC and balanced accuracy across seeds for each experiment.
Edit `result_dirs` to match actual output directory names after training.

In [21]:
import os
import json
import glob
import numpy as np
import pandas as pd

def collect_results(base_dir, label):
    """
    Collect AUROC, balanced accuracy, AP, F1, and confusion matrix across seed subdirectories.
    Looks for metrics.json or test_predictions.csv in each seed folder.
    Returns a dict with mean/std suitable for pasting into the results table.
    """
    from sklearn.metrics import (
        roc_auc_score, balanced_accuracy_score,
        average_precision_score, f1_score, confusion_matrix
    )

    aurocs, bal_accs, aps, f1s = [], [], [], []
    cms = []
    behaviours = []

    seed_dirs = sorted(glob.glob(os.path.join(base_dir, 'seed_*')))
    if not seed_dirs:
        seed_dirs = sorted(glob.glob(os.path.join(base_dir, 'tcn_*')))

    for seed_dir in seed_dirs:
        print(f'found {base_dir} / {seed_dir} for {label}')
        metrics_path = os.path.join(seed_dir, 'metrics.json')

        if os.path.exists(metrics_path):
            with open(metrics_path) as f:
                m = json.load(f)
            aurocs.append(m.get('test_auroc', m.get('auroc')))
            bal_accs.append(m.get('test_balanced_accuracy', m.get('balanced_accuracy')))
            aps.append(m.get('test_ap', m.get('ap')))
            f1s.append(m.get('test_f1', m.get('f1')))
            # metrics.json may not have CM — skip if absent
            cm = m.get('confusion_matrix')
            cms.append(np.array(cm) if cm is not None else None)
            # determine degeneracy from pred distribution if available
            unique_preds = m.get('unique_pred_labels')
            is_degenerate = (unique_preds is not None and len(unique_preds) == 1)

        else:
            pred_path = os.path.join(seed_dir, 'test_predictions.csv')
            if os.path.exists(pred_path):
                preds = pd.read_csv(pred_path)
                print(f'  columns: {list(preds.columns)}')
                y_true = preds['true_label']
                y_prob = preds['pred_prob']
                y_pred = preds['pred_label']

                aurocs.append(roc_auc_score(y_true, y_prob))
                bal_accs.append(balanced_accuracy_score(y_true, y_pred))
                aps.append(average_precision_score(y_true, y_prob))
                f1s.append(f1_score(y_true, y_pred, zero_division=0))
                cms.append(confusion_matrix(y_true, y_pred))
                is_degenerate = (len(y_pred.unique()) == 1)
            else:
                print(f'  WARNING: no metrics found in {seed_dir}')
                continue

        # Behaviour classification — degeneracy takes priority over AUROC threshold
        if is_degenerate:
            behaviours.append('Degenerate')
        elif aurocs and aurocs[-1] is not None:
            a = aurocs[-1]
            if a > 0.6:
                behaviours.append('Real signal')
            elif abs(a - 0.5) < 0.05:
                behaviours.append('Chance')
            else:
                behaviours.append('Near-chance')
        else:
            behaviours.append('Unknown')

    if not aurocs:
        print(f'No results found in {base_dir}')
        return None

    # Aggregate confusion matrices
    valid_cms = [cm for cm in cms if cm is not None]
    cm_mean = np.mean(valid_cms, axis=0).round(1) if valid_cms else None
    cm_std  = np.std(valid_cms,  axis=0).round(1) if valid_cms else None

    result = {
        'label':        label,
        'n_seeds':      len(aurocs),
        'auroc_mean':   np.mean(aurocs),
        'auroc_std':    np.std(aurocs),
        'bal_acc_mean': np.mean(bal_accs) if bal_accs else None,
        'bal_acc_std':  np.std(bal_accs)  if bal_accs else None,
        'ap_mean':      np.mean(aps)      if aps      else None,
        'ap_std':       np.std(aps)       if aps      else None,
        'f1_mean':      np.mean(f1s)      if f1s      else None,
        'f1_std':       np.std(f1s)       if f1s      else None,
        'cm_mean':      cm_mean,
        'cm_std':       cm_std,
        'behaviour':    behaviours[-1]    if behaviours else 'Unknown',
        'raw_aurocs':   aurocs,
    }

    # Pretty print
    print(f"{label}:")
    print(f"  AUROC:    {result['auroc_mean']:.3f} ± {result['auroc_std']:.3f}")
    print(f"  Bal Acc:  {result['bal_acc_mean']:.3f} ± {result['bal_acc_std']:.3f}" if bal_accs else "  Bal Acc: N/A")
    print(f"  AP:       {result['ap_mean']:.3f} ± {result['ap_std']:.3f}"           if aps      else "  AP:      N/A")
    print(f"  F1:       {result['f1_mean']:.3f} ± {result['f1_std']:.3f}"           if f1s      else "  F1:      N/A")
    print(f"  Behaviour: {result['behaviour']} (n={result['n_seeds']})")
    if cm_mean is not None:
        print(f"  CM (mean): TN={cm_mean[0,0]}, FP={cm_mean[0,1]}, FN={cm_mean[1,0]}, TP={cm_mean[1,1]}")

    return result


# --- Edit these paths to match actual output dirs ---
experiments = [
    ('../../results/tcn_scalar_50pct_receptor',         'Scalar (50%)',                   'receptor'),
    ('../../results/tcn_tica_50pct_receptor',           'TICA (50%)',                     'receptor'),
    ('../../results/tcn_combined_50pct_receptor',       'Handcrafted (combined, 50%)',    'receptor'),
    ('../../results/tcn_oracle_10pct_receptor',         'Oracle (10%)',                   'receptor'),
    ('../../results/tcn_oracle_50pct_receptor',         'Oracle (50%)',                   'receptor'),
    ('../../results/tcn_oracle_90pct_receptor',         'Oracle (90%)',                   'receptor'),
]

all_results = []
for base_dir, label, split in experiments:
    r = collect_results(base_dir, label)
    if r:
        r['split'] = split
        all_results.append(r)

results_df = pd.DataFrame(all_results)
results_df

found ../../results/tcn_scalar_50pct_receptor / ../../results/tcn_scalar_50pct_receptor/tcn_20260312_150355 for Scalar (50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_scalar_50pct_receptor / ../../results/tcn_scalar_50pct_receptor/tcn_20260312_151413 for Scalar (50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_scalar_50pct_receptor / ../../results/tcn_scalar_50pct_receptor/tcn_20260312_151825 for Scalar (50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Scalar (50%):
  AUROC:    0.682 ± 0.151
  Bal Acc:  0.500 ± 0.000
  AP:       0.377 ± 0.158
  F1:       0.115 ± 0.163
  Behaviour: Degenerate (n=3)
  CM (mean): TN=22.7, FP=11.3, FN=6.0, TP=3.0
found ../../results/tcn_tica_50pct_receptor / ../../results/tcn_tica_50pct_receptor/tcn_20260312_154322 for TICA (50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_tica_50pct_receptor / ../../results/tcn_tica_50pct_receptor/tcn_20260312_154726 for TICA (50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_tica_50pct_receptor / ../../results/tcn_tica_50pct_receptor/tcn_20260312_155708 for TICA (50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
TICA (50%):
  AUROC:    0.782 ± 0.022
  Bal Acc:  0.582 ± 0.116
  AP:       0.641 ± 0.024
  F1:       0.190 ± 0.269
  Behaviour: Degenerate (n=3)
  CM (mean): TN=32.0, FP=2.0, FN=7.0, TP=2.0
found ../../results/tcn_combined_50pct_receptor / ../../results/tcn_combined_50pct_receptor/tcn_20260312_120523 for Handcrafted (combined, 50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_combined_50pct_receptor / ../../results/tcn_combined_50pct_receptor/tcn_20260312_121944 for Handcrafted (combined, 50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_combined_50pct_receptor / ../../results/tcn_combined_50pct_receptor/tcn_20260312_122556 for Handcrafted (combined, 50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Handcrafted (combined, 50%):
  AUROC:    0.564 ± 0.091
  Bal Acc:  0.500 ± 0.000
  AP:       0.253 ± 0.062
  F1:       0.115 ± 0.163
  Behaviour: Degenerate (n=3)
  CM (mean): TN=22.7, FP=11.3, FN=6.0, TP=3.0
found ../../results/tcn_oracle_10pct_receptor / ../../results/tcn_oracle_10pct_receptor/tcn_20260312_153323 for Oracle (10%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_10pct_receptor / ../../results/tcn_oracle_10pct_receptor/tcn_20260312_153613 for Oracle (10%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_10pct_receptor / ../../results/tcn_oracle_10pct_receptor/tcn_20260312_153819 for Oracle (10%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Oracle (10%):
  AUROC:    0.836 ± 0.022
  Bal Acc:  0.690 ± 0.012
  AP:       0.520 ± 0.061
  F1:       0.501 ± 0.020
  Behaviour: Real signal (n=3)
  CM (mean): TN=28.0, FP=6.0, FN=4.0, TP=5.0
found ../../results/tcn_oracle_50pct_receptor / ../../results/tcn_oracle_50pct_receptor/tcn_20260312_123236 for Oracle (50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_50pct_receptor / ../../results/tcn_oracle_50pct_receptor/tcn_20260312_123646 for Oracle (50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_50pct_receptor / ../../results/tcn_oracle_50pct_receptor/tcn_20260312_124218 for Oracle (50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Oracle (50%):
  AUROC:    0.862 ± 0.005
  Bal Acc:  0.708 ± 0.108
  AP:       0.572 ± 0.042
  F1:       0.460 ± 0.185
  Behaviour: Real signal (n=3)
  CM (mean): TN=28.0, FP=6.0, FN=3.7, TP=5.3
found ../../results/tcn_oracle_90pct_receptor / ../../results/tcn_oracle_90pct_receptor/tcn_20260312_143510 for Oracle (90%)
  WARNING: no metrics found in ../../results/tcn_oracle_90pct_receptor/tcn_20260312_143510
found ../../results/tcn_oracle_90pct_receptor / ../../results/tcn_oracle_90pct_receptor/tcn_20260312_143513 for Oracle (90%)
  WARNING: no metrics found in ../../results/tcn_oracle_90pct_receptor/tcn_20260312_143513
found ../../results/tcn_oracle_90pct_receptor / ../../results/tcn_oracle_90pct_receptor/tcn_20260312_143516 for Oracle (90%)
  WARNING: no metrics found in ../../results/tcn_oracle_90pct_receptor/tcn_20260312_143516
found ../../results/tcn_oracle_90pct_receptor / ../../results/tcn_oracle_90pct_receptor/tcn_20260312_143839 for Oracle (90%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_90pct_receptor / ../../results/tcn_oracle_90pct_receptor/tcn_20260312_144410 for Oracle (90%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_90pct_receptor / ../../results/tcn_oracle_90pct_receptor/tcn_20260312_145240 for Oracle (90%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Oracle (90%):
  AUROC:    0.974 ± 0.005
  Bal Acc:  0.863 ± 0.017
  AP:       0.924 ± 0.005
  F1:       0.759 ± 0.017
  Behaviour: Real signal (n=3)
  CM (mean): TN=31.0, FP=3.0, FN=1.7, TP=7.3

,label,n_seeds,auroc_mean,auroc_std,bal_acc_mean,bal_acc_std,ap_mean,ap_std,f1_mean,f1_std,cm_mean,cm_std,behaviour,raw_aurocs,split
0,Scalar (50%),3,0.681917,0.150808,0.500000,0.000000,0.377065,0.157686,0.115385,0.163178,"[[22.7, 11.3], [6.0, 3.0]]","[[16.0, 16.0], [4.2, 4.2]]",Degenerate,"[0.869281045751634, 0.6764705882352942, 0.5]",receptor
1,TICA (50%),3,0.782135,0.022218,0.581699,0.115540,0.641203,0.024386,0.190476,0.269374,"[[32.0, 2.0], [7.0, 2.0]]","[[2.8, 2.8], [2.8, 2.8]]",Degenerate,"[0.7516339869281046, 0.7908496732026143, 0.803...",receptor
2,"Handcrafted (combined, 50%)",3,0.564270,0.090892,0.500000,0.000000,0.253360,0.062306,0.115385,0.163178,"[[22.7, 11.3], [6.0, 3.0]]","[[16.0, 16.0], [4.2, 4.2]]",Degenerate,"[0.6928104575163399, 0.5, 0.5]",receptor
3,Oracle (10%),3,0.836057,0.021609,0.689542,0.012007,0.519847,0.061272,0.500835,0.020472,"[[28.0, 6.0], [4.0, 5.0]]","[[0.8, 0.8], [0.0, 0.0]]",Real signal,"[0.8055555555555556, 0.8496732026143791, 0.852...",receptor
4,Oracle (50%),3,0.862200,0.005392,0.708061,0.107846,0.571595,0.042170,0.460041,0.184505,"[[28.0, 6.0], [3.7, 5.3]]","[[4.5, 4.5], [3.1, 3.1]]",Real signal,"[0.861111111111111, 0.869281045751634, 0.85620...",receptor
5,Oracle (90%),3,0.973856,0.004622,0.863290,0.016893,0.924197,0.005009,0.758842,0.016852,"[[31.0, 3.0], [1.7, 7.3]]","[[0.8, 0.8], [0.5, 0.5]]",Real signal,"[0.9673202614379085, 0.9771241830065359, 0.977...",receptor

In [35]:
oracle_experiments = [
    ('../../results/tcn_oracle_10pct_receptor',         'Oracle (10%)',                   'receptor'),
    ('../../results/tcn_oracle_20pct_receptor',         'Oracle (20%)',                   'receptor'),
    ('../../results/tcn_oracle_30pct_receptor',         'Oracle (30%)',                   'receptor'),
    ('../../results/tcn_oracle_40pct_receptor',         'Oracle (40%)',                   'receptor'),
    ('../../results/tcn_oracle_50pct_receptor',         'Oracle (50%)',                   'receptor'),
    ('../../results/tcn_oracle_60pct_receptor',         'Oracle (60%)',                   'receptor'),
    ('../../results/tcn_oracle_70pct_receptor',         'Oracle (70%)',                   'receptor'),
    ('../../results/tcn_oracle_80pct_receptor',         'Oracle (80%)',                   'receptor'),
    ('../../results/tcn_oracle_90pct_receptor',         'Oracle (90%)',                   'receptor'),
    ('../../results/tcn_oracle_100pct_receptor',         'Oracle (100%)',                 'receptor'),
]

all_oracle_results = []
for base_dir, label, split in oracle_experiments:
    r = collect_results(base_dir, label)
    if r:
        r['split'] = split
        all_oracle_results.append(r)

oracle_results_df = pd.DataFrame(all_oracle_results)
oracle_results_df

found ../../results/tcn_oracle_10pct_receptor / ../../results/tcn_oracle_10pct_receptor/tcn_20260312_153323 for Oracle (10%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_10pct_receptor / ../../results/tcn_oracle_10pct_receptor/tcn_20260312_153613 for Oracle (10%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_10pct_receptor / ../../results/tcn_oracle_10pct_receptor/tcn_20260312_153819 for Oracle (10%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Oracle (10%):
  AUROC:    0.836 ± 0.022
  Bal Acc:  0.690 ± 0.012
  AP:       0.520 ± 0.061
  F1:       0.501 ± 0.020
  Behaviour: Real signal (n=3)
  CM (mean): TN=28.0, FP=6.0, FN=4.0, TP=5.0
found ../../results/tcn_oracle_20pct_receptor / ../../results/tcn_oracle_20pct_receptor/tcn_20260313_004158 for Oracle (20%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_20pct_receptor / ../../results/tcn_oracle_20pct_receptor/tcn_20260313_004431 for Oracle (20%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_20pct_receptor / ../../results/tcn_oracle_20pct_receptor/tcn_20260313_004718 for Oracle (20%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Oracle (20%):
  AUROC:    0.817 ± 0.027
  Bal Acc:  0.602 ± 0.095
  AP:       0.519 ± 0.109
  F1:       0.357 ± 0.164
  Behaviour: Real signal (n=3)
  CM (mean): TN=28.3, FP=5.7, FN=5.7, TP=3.3
found ../../results/tcn_oracle_30pct_receptor / ../../results/tcn_oracle_30pct_receptor/tcn_20260313_004933 for Oracle (30%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_30pct_receptor / ../../results/tcn_oracle_30pct_receptor/tcn_20260313_005312 for Oracle (30%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_30pct_receptor / ../../results/tcn_oracle_30pct_receptor/tcn_20260313_005644 for Oracle (30%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Oracle (30%):
  AUROC:    0.837 ± 0.016
  Bal Acc:  0.814 ± 0.030
  AP:       0.505 ± 0.008
  F1:       0.647 ± 0.036
  Behaviour: Real signal (n=3)
  CM (mean): TN=27.7, FP=6.3, FN=1.7, TP=7.3
found ../../results/tcn_oracle_40pct_receptor / ../../results/tcn_oracle_40pct_receptor/tcn_20260313_005931 for Oracle (40%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_40pct_receptor / ../../results/tcn_oracle_40pct_receptor/tcn_20260313_010300 for Oracle (40%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_40pct_receptor / ../../results/tcn_oracle_40pct_receptor/tcn_20260313_010700 for Oracle (40%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Oracle (40%):
  AUROC:    0.852 ± 0.012
  Bal Acc:  0.638 ± 0.017
  AP:       0.558 ± 0.031
  F1:       0.425 ± 0.022
  Behaviour: Real signal (n=3)
  CM (mean): TN=27.0, FP=7.0, FN=4.7, TP=4.3
found ../../results/tcn_oracle_50pct_receptor / ../../results/tcn_oracle_50pct_receptor/tcn_20260312_123236 for Oracle (50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_50pct_receptor / ../../results/tcn_oracle_50pct_receptor/tcn_20260312_123646 for Oracle (50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_50pct_receptor / ../../results/tcn_oracle_50pct_receptor/tcn_20260312_124218 for Oracle (50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Oracle (50%):
  AUROC:    0.862 ± 0.005
  Bal Acc:  0.708 ± 0.108
  AP:       0.572 ± 0.042
  F1:       0.460 ± 0.185
  Behaviour: Real signal (n=3)
  CM (mean): TN=28.0, FP=6.0, FN=3.7, TP=5.3
found ../../results/tcn_oracle_60pct_receptor / ../../results/tcn_oracle_60pct_receptor/tcn_20260313_011010 for Oracle (60%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_60pct_receptor / ../../results/tcn_oracle_60pct_receptor/tcn_20260313_011500 for Oracle (60%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_60pct_receptor / ../../results/tcn_oracle_60pct_receptor/tcn_20260313_012040 for Oracle (60%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Oracle (60%):
  AUROC:    0.887 ± 0.028
  Bal Acc:  0.818 ± 0.059
  AP:       0.686 ± 0.062
  F1:       0.647 ± 0.091
  Behaviour: Real signal (n=3)
  CM (mean): TN=26.7, FP=7.3, FN=1.3, TP=7.7
found ../../results/tcn_oracle_70pct_receptor / ../../results/tcn_oracle_70pct_receptor/tcn_20260313_012535 for Oracle (70%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_70pct_receptor / ../../results/tcn_oracle_70pct_receptor/tcn_20260313_013043 for Oracle (70%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_70pct_receptor / ../../results/tcn_oracle_70pct_receptor/tcn_20260313_013608 for Oracle (70%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Oracle (70%):
  AUROC:    0.871 ± 0.038
  Bal Acc:  0.777 ± 0.101
  AP:       0.668 ± 0.129
  F1:       0.594 ± 0.123
  Behaviour: Real signal (n=3)
  CM (mean): TN=27.7, FP=6.3, FN=2.3, TP=6.7
found ../../results/tcn_oracle_80pct_receptor / ../../results/tcn_oracle_80pct_receptor/tcn_20260313_014300 for Oracle (80%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_80pct_receptor / ../../results/tcn_oracle_80pct_receptor/tcn_20260313_014805 for Oracle (80%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_80pct_receptor / ../../results/tcn_oracle_80pct_receptor/tcn_20260313_015915 for Oracle (80%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Oracle (80%):
  AUROC:    0.936 ± 0.024
  Bal Acc:  0.849 ± 0.083
  AP:       0.705 ± 0.063
  F1:       0.711 ± 0.087
  Behaviour: Real signal (n=3)
  CM (mean): TN=30.0, FP=4.0, FN=1.7, TP=7.3
found ../../results/tcn_oracle_90pct_receptor / ../../results/tcn_oracle_90pct_receptor/tcn_20260312_143510 for Oracle (90%)
  WARNING: no metrics found in ../../results/tcn_oracle_90pct_receptor/tcn_20260312_143510
found ../../results/tcn_oracle_90pct_receptor / ../../results/tcn_oracle_90pct_receptor/tcn_20260312_143513 for Oracle (90%)
  WARNING: no metrics found in ../../results/tcn_oracle_90pct_receptor/tcn_20260312_143513
found ../../results/tcn_oracle_90pct_receptor / ../../results/tcn_oracle_90pct_receptor/tcn_20260312_143516 for Oracle (90%)
  WARNING: no metrics found in ../../results/tcn_oracle_90pct_receptor/tcn_20260312_143516
found ../../results/tcn_oracle_90pct_receptor / ../../results/tcn_oracle_90pct_receptor/tcn_20260312_143839 for Oracle (90%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_90pct_receptor / ../../results/tcn_oracle_90pct_receptor/tcn_20260312_144410 for Oracle (90%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_90pct_receptor / ../../results/tcn_oracle_90pct_receptor/tcn_20260312_145240 for Oracle (90%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Oracle (90%):
  AUROC:    0.974 ± 0.005
  Bal Acc:  0.863 ± 0.017
  AP:       0.924 ± 0.005
  F1:       0.759 ± 0.017
  Behaviour: Real signal (n=3)
  CM (mean): TN=31.0, FP=3.0, FN=1.7, TP=7.3
found ../../results/tcn_oracle_100pct_receptor / ../../results/tcn_oracle_100pct_receptor/tcn_20260313_020544 for Oracle (100%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_100pct_receptor / ../../results/tcn_oracle_100pct_receptor/tcn_20260313_021355 for Oracle (100%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_oracle_100pct_receptor / ../../results/tcn_oracle_100pct_receptor/tcn_20260313_022249 for Oracle (100%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Oracle (100%):
  AUROC:    0.977 ± 0.014
  Bal Acc:  0.923 ± 0.013
  AP:       0.916 ± 0.052
  F1:       0.803 ± 0.039
  Behaviour: Real signal (n=3)
  CM (mean): TN=30.0, FP=4.0, FN=0.3, TP=8.7

,label,n_seeds,auroc_mean,auroc_std,bal_acc_mean,bal_acc_std,ap_mean,ap_std,f1_mean,f1_std,cm_mean,cm_std,behaviour,raw_aurocs,split
0,Oracle (10%),3,0.836057,0.021609,0.689542,0.012007,0.519847,0.061272,0.500835,0.020472,"[[28.0, 6.0], [4.0, 5.0]]","[[0.8, 0.8], [0.0, 0.0]]",Real signal,"[0.8055555555555556, 0.8496732026143791, 0.852...",receptor
1,Oracle (20%),3,0.816993,0.027080,0.601852,0.095243,0.518553,0.108622,0.357260,0.164248,"[[28.3, 5.7], [5.7, 3.3]]","[[1.2, 1.2], [1.7, 1.7]]",Real signal,"[0.781045751633987, 0.8464052287581699, 0.8235...",receptor
2,Oracle (30%),3,0.837146,0.015578,0.814270,0.030257,0.504907,0.008461,0.646904,0.036274,"[[27.7, 6.3], [1.7, 7.3]]","[[0.5, 0.5], [0.5, 0.5]]",Real signal,"[0.8333333333333333, 0.857843137254902, 0.8202...",receptor
3,Oracle (40%),3,0.851852,0.012324,0.637800,0.016893,0.557548,0.031131,0.425199,0.022460,"[[27.0, 7.0], [4.7, 4.3]]","[[0.8, 0.8], [0.5, 0.5]]",Real signal,"[0.8431372549019607, 0.8692810457516339, 0.843...",receptor
4,Oracle (50%),3,0.862200,0.005392,0.708061,0.107846,0.571595,0.042170,0.460041,0.184505,"[[28.0, 6.0], [3.7, 5.3]]","[[4.5, 4.5], [3.1, 3.1]]",Real signal,"[0.861111111111111, 0.869281045751634, 0.85620...",receptor
5,Oracle (60%),3,0.887255,0.027762,0.818083,0.059025,0.685641,0.062323,0.646789,0.091347,"[[26.7, 7.3], [1.3, 7.7]]","[[2.5, 2.5], [0.5, 0.5]]",Real signal,"[0.8480392156862744, 0.9084967320261438, 0.905...",receptor
6,Oracle (70%),3,0.870915,0.037570,0.777233,0.101468,0.667775,0.129247,0.594457,0.123185,"[[27.7, 6.3], [2.3, 6.7]]","[[0.5, 0.5], [1.9, 1.9]]",Real signal,"[0.8316993464052288, 0.9215686274509803, 0.859...",receptor
7,Oracle (80%),3,0.936275,0.024052,0.848584,0.082957,0.705179,0.063489,0.710916,0.087159,"[[30.0, 4.0], [1.7, 7.3]]","[[0.8, 0.8], [1.7, 1.7]]",Real signal,"[0.9035947712418301, 0.9607843137254902, 0.944...",receptor
8,Oracle (90%),3,0.973856,0.004622,0.863290,0.016893,0.924197,0.005009,0.758842,0.016852,"[[31.0, 3.0], [1.7, 7.3]]","[[0.8, 0.8], [0.5, 0.5]]",Real signal,"[0.9673202614379085, 0.9771241830065359, 0.977...",receptor
9,Oracle (100%),3,0.977124,0.013865,0.922658,0.013162,0.915552,0.051985,0.803429,0.039022,"[[30.0, 4.0], [0.3, 8.7]]","[[1.6, 1.6], [0.5, 0.5]]",Real signal,"[0.957516339869281, 0.9869281045751633, 0.9869...",receptor

In [22]:
family_experiments = [
    ('../../results/tcn_sanity_check_10pct',            'Oracle (10%)',                   'family'),
    ('../../results/tcn_sanity_check_50pct',            'Oracle (50%)',                   'family'),
    ('../../results/tcn_sanity_check_90pct',            'Oracle (90%)',                   'family'),
]

all_family_results = []
for base_dir, label, split in family_experiments:
    r = collect_results(base_dir, label)
    if r:
        r['split'] = split
        all_family_results.append(r)

family_results_df = pd.DataFrame(all_family_results)
family_results_df

found ../../../gcs_mount/results/tcn_combined_50pct / ../../../gcs_mount/results/tcn_combined_50pct/tcn_20260228_152756 for Handcrafted (combined, 50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Handcrafted (combined, 50%):
  AUROC:    0.543 ± 0.000
  Bal Acc:  0.500 ± 0.000
  AP:       0.425 ± 0.000
  F1:       0.000 ± 0.000
  Behaviour: Degenerate (n=1)
  CM (mean): TN=35.0, FP=0.0, FN=22.0, TP=0.0
found ../../results/tcn_sanity_check_10pct / ../../results/tcn_sanity_check_10pct/tcn_20260311_032034 for Oracle (10%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_sanity_check_10pct / ../../results/tcn_sanity_check_10pct/tcn_20260311_032501 for Oracle (10%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_sanity_check_10pct / ../../results/tcn_sanity_check_10pct/tcn_20260311_032806 for Oracle (10%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_sanity_check_10pct / ../../results/tcn_sanity_check_10pct/tcn_20260311_033132 for Oracle (10%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Oracle (10%):
  AUROC:    0.782 ± 0.030
  Bal Acc:  0.555 ± 0.014
  AP:       0.697 ± 0.024
  F1:       0.256 ± 0.031
  Behaviour: Real signal (n=4)
  CM (mean): TN=33.2, FP=1.8, FN=18.5, TP=3.5
found ../../results/tcn_sanity_check_50pct / ../../results/tcn_sanity_check_50pct/tcn_20260303_143046 for Oracle (50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_sanity_check_50pct / ../../results/tcn_sanity_check_50pct/tcn_20260303_143512 for Oracle (50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_sanity_check_50pct / ../../results/tcn_sanity_check_50pct/tcn_20260303_144808 for Oracle (50%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Oracle (50%):
  AUROC:    0.811 ± 0.020
  Bal Acc:  0.748 ± 0.033
  AP:       0.761 ± 0.044
  F1:       0.679 ± 0.045
  Behaviour: Real signal (n=3)
  CM (mean): TN=31.7, FP=3.3, FN=9.0, TP=13.0
found ../../results/tcn_sanity_check_90pct / ../../results/tcn_sanity_check_90pct/tcn_20260303_152556 for Oracle (90%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_sanity_check_90pct / ../../results/tcn_sanity_check_90pct/tcn_20260305_053115 for Oracle (90%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_sanity_check_90pct / ../../results/tcn_sanity_check_90pct/tcn_20260305_053353 for Oracle (90%)
  columns: ['true_label', 'pred_prob', 'pred_label']
found ../../results/tcn_sanity_check_90pct / ../../results/tcn_sanity_check_90pct/tcn_20260305_053806 for Oracle (90%)
  columns: ['true_label', 'pred_prob', 'pred_label']
Oracle (90%):
  AUROC:    0.933 ± 0.015
  Bal Acc:  0.728 ± 0.056
  AP:       0.913 ± 0.025
  F1:       0.626 ± 0.096
  Behaviour: Real signal (n=4)
  CM (mean): TN=34.2, FP=0.8, FN=11.5, TP=10.5

,label,n_seeds,auroc_mean,auroc_std,bal_acc_mean,bal_acc_std,ap_mean,ap_std,f1_mean,f1_std,cm_mean,cm_std,behaviour,raw_aurocs,split
0,"Handcrafted (combined, 50%)",1,0.542857,0.000000,0.500000,0.000000,0.424977,0.000000,0.000000,0.000000,"[[35.0, 0.0], [22.0, 0.0]]","[[0.0, 0.0], [0.0, 0.0]]",Degenerate,[0.5428571428571428],family
1,Oracle (10%),4,0.782468,0.029750,0.554545,0.013721,0.697460,0.024300,0.256287,0.030804,"[[33.2, 1.8], [18.5, 3.5]]","[[0.8, 0.8], [0.5, 0.5]]",Real signal,"[0.8038961038961038, 0.8090909090909091, 0.733...",family
2,Oracle (50%),3,0.811255,0.020461,0.747835,0.033086,0.761445,0.044381,0.678679,0.045186,"[[31.7, 3.3], [9.0, 13.0]]","[[1.2, 1.2], [0.8, 0.8]]",Real signal,"[0.7831168831168832, 0.8311688311688312, 0.819...",family
3,Oracle (90%),4,0.933117,0.014650,0.727922,0.055638,0.912547,0.025040,0.625781,0.096400,"[[34.2, 0.8], [11.5, 10.5]]","[[0.8, 0.8], [2.3, 2.3]]",Real signal,"[0.9558441558441557, 0.9337662337662338, 0.927...",family

## Step 4: Format for Report
Generates LaTeX table rows ready to paste into the paper.
Cross-family numbers are hardcoded from existing results for comparison.

In [23]:
# Cross-family results (hardcoded from existing experiments)
cross_family = {
    'Scalar (TCN, 3-dim)':              {'auroc': 0.500, 'behaviour': 'Degenerate'},
    'TICA projections (TCN, 5-dim)':    {'auroc': 0.500, 'behaviour': 'Degenerate'},
    'Combined (TCN, 58-dim)':           {'auroc': 0.543, 'behaviour': 'Degenerate'},
    'Oracle 10% (TCN, 7-dim)':          {'auroc': 0.783, 'behaviour': 'Real signal'},
    'Oracle 50% (TCN, 7-dim)':          {'auroc': 0.811, 'behaviour': 'Real signal'},
    'Oracle 90% (TCN, 7-dim)':          {'auroc': 0.933, 'behaviour': 'Real signal'},
    'ESMDance LR (480-dim)':            {'auroc': 0.494, 'behaviour': 'Near-chance'},
    'ESMDance RF (480-dim)':            {'auroc': 0.523, 'behaviour': 'Near-chance'},
    'ESMDance MLP (480-dim)':           {'auroc': 0.500, 'behaviour': 'Degenerate'},
    'ESM-IF mean-pooled LR':            {'auroc': 0.541, 'behaviour': 'Near-chance'},
    'ESM-IF mean-pooled RF':            {'auroc': 0.513, 'behaviour': 'Near-chance'},
    'ESM-IF mean-pooled MLP':           {'auroc': 0.529, 'behaviour': 'Near-chance'},
}

# ESM-2,LogisticRegression,1280,0.5409090909090909,0.434697431180753,0.4948051948051948,0.5968253968253968,6,29,4,18
# ESM-2,RandomForest,1280,0.512987012987013,0.42295344159738346,0.5253246753246753,0.551468253968254,32,3,19,3
# ESM-2,MLP,1280,0.5285714285714286,0.4294189444625695,0.49090909090909096,0.6452380952380953,28,7,18,4
# ESMDance,LogisticRegression,480,0.4941558441558441,0.42390253678527784,0.5233766233766234,0.5975396825396826,8,27,4,18
# ESMDance,RandomForest,480,0.5233766233766234,0.4098917286417287,0.4967532467532467,0.5699206349206349,30,5,19,3
# ESMDance,MLP,480,0.5,0.4187125948404144,0.5311688311688312,0.6382539682539683,34,1,20,2

print("=" * 70)
print("RECEPTOR-LEVEL HOLDOUT RESULTS (fill in after experiments complete)")
print("=" * 70)
for r in all_results:
    print(f"  {r['label']}: {r['auroc_mean']:.3f} ± {r['auroc_std']:.3f} [{r['behaviour']}]")

print()
print("=" * 70)
print("LaTeX TABLE ROWS (receptor AUROC | family AUROC)")
print("Fill in TBD values from results_df above")
print("=" * 70)
print()

# Template — fill in receptor_auroc values from results_df after running
rows = [
    # (features, model, dim, receptor_auroc, family_auroc, behaviour)
    ('Scalar',            'TCN',     '3',   'TBD',  '0.500', 'Degenerate'),
    ('TICA projections',  'TCN',     '5',   'TBD',  '0.500', 'Degenerate'),
    ('Combined',          'TCN',     '58',  'TBD',  '0.500', 'Degenerate'),
    ('ESMDance',          'LR',      '480', '--',   '0.494', 'Near-chance'),
    ('ESMDance',          'RF',      '480', '--',   '0.523', 'Near-chance'),
    ('ESMDance',          'MLP',     '480', '--',   '0.500', 'Degenerate'),
    ('ESM-IF (mean-pooled)', 'LR/RF/MLP', '512', '0.770', '0.527', 'Near-chance / Real signal'),
    ('Oracle (50\\%)',    'TCN',     '7',   'TBD',  '0.831', 'Real signal'),
]

print(r'\midrule')
for feat, model, dim, rec_auroc, fam_auroc, beh in rows:
    print(f'{feat} & {model} & {dim} & {rec_auroc} & {fam_auroc} & {beh} \\\\')
print(r'\midrule')
print(r'Oracle (50\%) & TCN & 7 & TBD & 0.831 & Real signal \\')

======================================================================
RECEPTOR-LEVEL HOLDOUT RESULTS (fill in after experiments complete)
======================================================================
  Scalar (50%): 0.682 ± 0.151 [Degenerate]
  TICA (50%): 0.782 ± 0.022 [Degenerate]
  Handcrafted (combined, 50%): 0.564 ± 0.091 [Degenerate]
  Oracle (10%): 0.836 ± 0.022 [Real signal]
  Oracle (50%): 0.862 ± 0.005 [Real signal]
  Oracle (90%): 0.974 ± 0.005 [Real signal]

======================================================================
LaTeX TABLE ROWS (receptor AUROC | family AUROC)
Fill in TBD values from results_df above
======================================================================

\midrule
Scalar & TCN & 3 & TBD & 0.500 & Degenerate \\
TICA projections & TCN & 5 & TBD & 0.500 & Degenerate \\
Combined & TCN & 58 & TBD & 0.500 & Degenerate \\
ESMDance & LR & 480 & -- & 0.494 & Near-chance \\
ESMDance & RF & 480 & -- & 0.523 & Near-chance \\
ESMDance & MLP & 480 & -- & 0.500 & Degenerate \\
ESM-IF (mean-pooled) & LR/RF/MLP & 512 & 0.770 & 0.527 & Near-chance / Real signal \\
Oracle (50\%) & TCN & 7 & TBD & 0.831 & Real signal \\
\midrule
Oracle (50\%) & TCN & 7 & TBD & 0.831 & Real signal \\

In [30]:
# Cross-family results (hardcoded from existing experiments)
# Columns: auroc, avg_precision, balanced_accuracy, cv_auroc, TN, FP, FN, TP
cross_family = {
    'Scalar (TCN, 3-dim)':           {'auroc': 0.500, 'bal_acc': None,  'cv_auroc': None,  'behaviour': 'Degenerate'},
    'TICA projections (TCN, 5-dim)': {'auroc': 0.500, 'bal_acc': None,  'cv_auroc': None,  'behaviour': 'Degenerate'},
    'Combined (TCN, 58-dim)':        {'auroc': 0.543, 'bal_acc': None,  'cv_auroc': None,  'behaviour': 'Degenerate'},
    'Oracle 10% (TCN, 7-dim)':       {'auroc': 0.783, 'bal_acc': None,  'cv_auroc': None,  'behaviour': 'Real signal'},
    'Oracle 50% (TCN, 7-dim)':       {'auroc': 0.811, 'bal_acc': None,  'cv_auroc': None,  'behaviour': 'Real signal'},
    'Oracle 90% (TCN, 7-dim)':       {'auroc': 0.933, 'bal_acc': None,  'cv_auroc': None,  'behaviour': 'Real signal'},
    'ESM-2 LR (1280-dim)':           {'auroc': 0.541, 'bal_acc': 0.495, 'cv_auroc': 0.597, 'behaviour': 'Near-chance', 'TN':  6, 'FP': 29, 'FN':  4, 'TP': 18},
    'ESM-2 RF (1280-dim)':           {'auroc': 0.513, 'bal_acc': 0.525, 'cv_auroc': 0.551, 'behaviour': 'Near-chance', 'TN': 32, 'FP':  3, 'FN': 19, 'TP':  3},
    'ESM-2 MLP (1280-dim)':          {'auroc': 0.529, 'bal_acc': 0.491, 'cv_auroc': 0.645, 'behaviour': 'Near-chance', 'TN': 28, 'FP':  7, 'FN': 18, 'TP':  4},
    'ESMDance LR (480-dim)':         {'auroc': 0.494, 'bal_acc': 0.523, 'cv_auroc': 0.598, 'behaviour': 'Near-chance', 'TN':  8, 'FP': 27, 'FN':  4, 'TP': 18},
    'ESMDance RF (480-dim)':         {'auroc': 0.523, 'bal_acc': 0.497, 'cv_auroc': 0.570, 'behaviour': 'Near-chance', 'TN': 30, 'FP':  5, 'FN': 19, 'TP':  3},
    'ESMDance MLP (480-dim)':        {'auroc': 0.500, 'bal_acc': 0.531, 'cv_auroc': 0.638, 'behaviour': 'Degenerate',  'TN': 34, 'FP':  1, 'FN': 20, 'TP':  2},
}

print("=" * 70)
print("CROSS-FAMILY RESULTS SUMMARY")
print("=" * 70)
print(f"{'Label':<35} {'AUROC':>6} {'BalAcc':>7} {'CV AUROC':>9} {'Behaviour'}")
print("-" * 70)
for label, m in cross_family.items():
    bal = f"{m['bal_acc']:.3f}" if m['bal_acc'] else '  --  '
    cv  = f"{m['cv_auroc']:.3f}" if m['cv_auroc'] else '  --  '
    print(f"{label:<35} {m['auroc']:>6.3f} {bal:>7} {cv:>9}  {m['behaviour']}")

print()
print("=" * 70)
print("RECEPTOR-LEVEL HOLDOUT RESULTS (fill in after experiments complete)")
print("=" * 70)
for r in all_results:
    bal = f"{r['bal_acc_mean']:.3f}" if r['bal_acc_mean'] else '--'
    print(f"  {r['label']}: AUROC {r['auroc_mean']:.3f} ± {r['auroc_std']:.3f} "
          f"| BalAcc {bal} [{r['behaviour']}]")

print()
print("=" * 70)
print("LaTeX TABLE ROWS (receptor AUROC | family AUROC)")
print("Fill in TBD values from results_df above")
print("=" * 70)
print()


# FINAL RECEPTOR-LEVEL RESULTS
#    model         classifier    auroc  balanced_accuracy  TN  FP  FN  TP
# ESMDance LogisticRegression 0.553922           0.612745  19  15   3   6
# ESMDance       RandomForest 0.576797           0.537582  29   5   7   2
# ESMDance                MLP 0.619281           0.500000  34   0   9   0
#    ESM-2 LogisticRegression 0.687908           0.686275  24  10   3   6
#    ESM-2       RandomForest 0.560458           0.537582  29   5   7   2
#    ESM-2                MLP 0.521242           0.467320  28   6   8   1


# Template — fill in receptor_auroc values from results_df after running
# (features, model, dim, receptor_auroc, family_auroc, behaviour)
rows = [
    ('Scalar',               'TCN',     '3',    '0.682', '0.500', 'Degenerate'),
    ('TICA projections',     'TCN',     '5',    '0.782', '0.500', 'Degenerate'),
    ('Combined',             'TCN',     '58',   '0.564', '0.543', 'Degenerate'),
    ('ESM-2',                'LR',        '1280', '0.688',  '0.541', 'Near-chance'),
    ('ESM-2',                'RF',        '1280', '0.560',  '0.513', 'Near-chance'),
    ('ESM-2',                'MLP',       '1280', '0.521',  '0.529', 'Near-chance'),
    ('ESMDance',             'LR',        '480',  '0.554',  '0.494', 'Near-chance'),
    ('ESMDance',             'RF',        '480',  '0.577',  '0.523', 'Near-chance'),
    ('ESMDance',             'MLP',       '480',  '0.619',  '0.500', 'Degenerate'),
    ('ESM-IF (mean-pooled)', 'LR', '512',  '--', '0.541', 'Near-chance'),
    ('ESM-IF (mean-pooled)', 'RF', '512',  '--', '0.513', 'Near-chance'),
    ('ESM-IF (mean-pooled)', 'MLP', '512', '--', '0.529', 'Near-chance'),
    ('Oracle (10\\%)',       'TCN',       '7',    '0.836', '0.783', 'Real signal'),
    ('Oracle (50\\%)',       'TCN',       '7',    '0.862', '0.811', 'Real signal'),
    ('Oracle (90\\%)',       'TCN',       '7',    '0.974', '0.933', 'Real signal'),
]

print(r'\midrule')
for feat, model, dim, rec_auroc, fam_auroc, beh in rows:
    print(f'{feat} & {model} & {dim} & {rec_auroc} & {fam_auroc} & {beh} \\\\')
print(r'\midrule')

======================================================================
CROSS-FAMILY RESULTS SUMMARY
======================================================================
Label                                AUROC  BalAcc  CV AUROC Behaviour
----------------------------------------------------------------------
Scalar (TCN, 3-dim)                  0.500    --        --    Degenerate
TICA projections (TCN, 5-dim)        0.500    --        --    Degenerate
Combined (TCN, 58-dim)               0.543    --        --    Degenerate
Oracle 10% (TCN, 7-dim)              0.783    --        --    Real signal
Oracle 50% (TCN, 7-dim)              0.811    --        --    Real signal
Oracle 90% (TCN, 7-dim)              0.933    --        --    Real signal
ESM-2 LR (1280-dim)                  0.541   0.495     0.597  Near-chance
ESM-2 RF (1280-dim)                  0.513   0.525     0.551  Near-chance
ESM-2 MLP (1280-dim)                 0.529   0.491     0.645  Near-chance
ESMDance LR (480-dim)                0.494   0.523     0.598  Near-chance
ESMDance RF (480-dim)                0.523   0.497     0.570  Near-chance
ESMDance MLP (480-dim)               0.500   0.531     0.638  Degenerate

======================================================================
RECEPTOR-LEVEL HOLDOUT RESULTS (fill in after experiments complete)
======================================================================
  Scalar (50%): AUROC 0.682 ± 0.151 | BalAcc 0.500 [Degenerate]
  TICA (50%): AUROC 0.782 ± 0.022 | BalAcc 0.582 [Degenerate]
  Handcrafted (combined, 50%): AUROC 0.564 ± 0.091 | BalAcc 0.500 [Degenerate]
  Oracle (10%): AUROC 0.836 ± 0.022 | BalAcc 0.690 [Real signal]
  Oracle (50%): AUROC 0.862 ± 0.005 | BalAcc 0.708 [Real signal]
  Oracle (90%): AUROC 0.974 ± 0.005 | BalAcc 0.863 [Real signal]

======================================================================
LaTeX TABLE ROWS (receptor AUROC | family AUROC)
Fill in TBD values from results_df above
======================================================================

\midrule
Scalar & TCN & 3 & 0.682 & 0.500 & Degenerate \\
TICA projections & TCN & 5 & 0.782 & 0.500 & Degenerate \\
Combined & TCN & 58 & 0.564 & 0.543 & Degenerate \\
ESM-2 & LR & 1280 & 0.688 & 0.541 & Near-chance \\
ESM-2 & RF & 1280 & 0.560 & 0.513 & Near-chance \\
ESM-2 & MLP & 1280 & 0.521 & 0.529 & Near-chance \\
ESMDance & LR & 480 & 0.554 & 0.494 & Near-chance \\
ESMDance & RF & 480 & 0.577 & 0.523 & Near-chance \\
ESMDance & MLP & 480 & 0.619 & 0.500 & Degenerate \\
ESM-IF (mean-pooled) & LR & 512 & -- & 0.541 & Near-chance \\
ESM-IF (mean-pooled) & RF & 512 & -- & 0.513 & Near-chance \\
ESM-IF (mean-pooled) & MLP & 512 & -- & 0.529 & Near-chance \\
Oracle (10\%) & TCN & 7 & 0.836 & 0.783 & Real signal \\
Oracle (50\%) & TCN & 7 & 0.862 & 0.811 & Real signal \\
Oracle (90\%) & TCN & 7 & 0.974 & 0.933 & Real signal \\
\midrule

## Step 5: Notes and Observations
Record any unexpected findings, degenerate prediction behavior, or follow-up actions here as experiments complete.

-